from typing import List
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
import os
from app.core.logging import logger

class LinesheetService:
    def __init__(self, output_dir: str = "static/linesheets"):
        self.output_dir = output_dir
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    async def generate(self, linesheet_id: int, title: str, skus: List[str]) -> str:
        filename = f"LS-{linesheet_id}-{title.replace(' ', '_')}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        
        try:
            c = canvas.Canvas(filepath, pagesize=A4)
            width, height = A4
            
            # Header
            c.setFont("Helvetica-Bold", 20)
            c.drawString(50, height - 50, f"LINESHEET: {title}")
            
            c.setFont("Helvetica", 12)
            c.drawString(50, height - 70, f"ID: {linesheet_id}")
            
            # Product List
            y_position = height - 120
            c.setFont("Helvetica-Bold", 14)
            c.drawString(50, y_position, "Included Products:")
            y_position -= 30
            
            c.setFont("Helvetica", 12)
            for sku in skus:
                if y_position < 50:
                    c.showPage()
                    y_position = height - 50
                c.drawString(70, y_position, f"• {sku}")
                y_position -= 20
            
            # Footer
            c.setFont("Helvetica-Oblique", 10)
            c.drawString(50, 30, "Generated by Synth-1 Fashion OS")
            
            c.save()
            logger.info(f"Linesheet generated: {filepath}")
            return f"/static/linesheets/{filename}"
            
        except Exception as e:
            logger.error(f"Error generating linesheet {linesheet_id}: {str(e)}")
            raise e
