/**
 * @generated split from platform-core-readiness-sections.ts — do not edit monolith; edit role file.
 */
import type { CoreHubPillarId } from '@/lib/platform-core-hub-matrix';
import {
  brandLinesheetsHrefForDemo,
  brandShowroomHrefForDemo,
  factoryHandoffQueueHrefForDemo,
  factoryMaterialsHrefForDemo,
  factoryMaterialsProcurementHrefForDemo,
  platformCoreRolePillarHref,
  shopShowroomHrefForDemo,
} from '@/lib/platform-core-hub-matrix';
import {
  ROUTES,
  brandB2bOrderChainContextHref,
  brandB2bOrderDossierContextHref,
  brandB2bOrderHandoffContextHref,
  brandB2bOrderHref,
  brandB2bOrdersAwaitingHandoffRegistryHref,
  brandB2bOrdersProductionRegistryHref,
  brandCoreOrderProductionCabinetHref,
  brandCalendarB2bOrderContextHref,
  brandMessagesB2bOrderContextHref,
  brandMessagesWorkshop2ArticleContextHref,
  brandW2ProductionTzHref,
  factoryMessagesB2bOrderContextHref,
  factoryMessagesWorkshop2ArticleContextHref,
  factoryCoreOrderProductionCabinetHref,
  factorySupplierCoreOrderProductionCabinetHref,
  factoryProductionDossierContextHref,
  factoryProductionDossierHref,
  factoryProductionOrdersOrderContextHref,
  factorySupplierMessagesB2bOrderContextHref,
  factorySupplierMessagesWorkshop2ArticleContextHref,
  shopB2bOrderHref,
  shopB2bOrderProductionContextHref,
  shopB2bOrdersProductionRegistryHref,
  shopB2bTrackingOrderHref,
  shopCalendarB2bOrderContextHref,
  shopMessagesB2bOrderContextHref,
} from '@/lib/routes';
import { PILLAR_CAPABILITY_FEATURE_PARAM } from '@/lib/platform/pillar-capability-workspaces';
import { WORKSHOP2_COL_PARAM, workshop2ArticleHref } from '@/lib/production/workshop2-url';
import type { SectionAuditTemplate } from './types';

export const BRAND_SECTION_AUDIT: Partial<
  Record<CoreHubPillarId, readonly SectionAuditTemplate[]>
> = {
  development: [
    {
      id: 'brand-dev-w2-hub',
      label: 'Цех разработки · коллекция',
      order: 1,
      staticScore: 7.3,
      liveScore: 8.0,
      summary: 'Hub артикулов, PG-hydrate, EMPTY27 onboarding.',
      good: [
        'PG-authoritative SS27/FW27',
        'brand-dev-w2-hub-panel + golden path strip (`brand-sample-lifecycle-golden-path-strip`)',
        'Peer: range/linesheets/showroom/factory dossier/sample queue',
        'UI «Создать артикул» (`brand-w2-create-article-btn`)',
        'Bulk-import SKU (`brand-w2-bulk-import-*`, core-30 e2e)',
        'Create-article wizard UI round-trip (core-37 e2e)',
        'PG sync hint (`workshop2-core-pg-sync-hint`)',
        'e2e core-01 + core-02 smoke',
        'EMPTY27 onboarding (`brand-dev-empty-onboarding`, core-44)',
        'core-52 TZ export + composition label e2e',
        'core-53 investor brief PDF export (`brief.pdf`)',
        'Investor summary strip on hub (`brand-dev-w2-hub-investor-summary-strip`)',
        'Publish release peer strip (`brand-sc-publish-release-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.productionWorkshop2}?${WORKSHOP2_COL_PARAM}=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-dev-dossier',
      label: 'Досье артикула · техзадание',
      order: 2,
      staticScore: 7.4,
      liveScore: 8.0,
      summary: 'Паспорт, persist API — все секции ТЗ + составник 4 шага (core-02 e2e).',
      good: [
        'brand-dev-dossier-panel + context/cross strips',
        'Investor summary deep-link (`brand-dev-dossier-investor-summary-link`)',
        'PUT/GET dossier PG',
        'e2e UI 4 поля general + API 3 поля passportProductionBrief (core-02)',
        'e2e material: BOM + composition wizard 1–4 + fiber constructor UI/API (core-02)',
        'e2e construction: smartRoutingSequence equipment UI + API round-trip (core-02)',
        'e2e assignment: PG chip + factory handoff gate (core-02)',
        'brand-dossier-article-chat-link',
        'Gates ТЗ link (`brand-w2-gates-summary-link`)',
        'BOM/sample badges в wayfinding',
        'Скачать пакет ТЗ (`brand-w2-tz-export-btn`) + статус gate',
        'Отправить ТЗ в чат (`brand-w2-tz-attach-chat-btn`) + e2e core-02',
        'core-52 export-tz-bundle gate/ZIP + composition panel e2e',
        'core-53 investor-readiness + investor-brief page e2e',
        'core-53 investor brief PDF export',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        workshop2ArticleHref(d.collectionId, d.demoArticleId, { w2sec: 'general' }),
    },
    {
      id: 'brand-dev-range',
      label: 'Планировщик ассортимента',
      order: 3,
      staticScore: 7.3,
      liveScore: 8.0,
      summary: 'Tier, бюджет, маржа из PG — EMPTY27 onboarding в cabinet.',
      good: [
        'brand-dev-range-panel + context strip (W2/dossier/factory/showroom/linesheets)',
        'budgetFromPg на SS27/FW27 e2e',
        'Tier SKU counts из PG',
        'Сводка маржи (`range-planner-margin-summary`)',
        'Ссылка tier → W2 (`range-planner-tier-w2-link`)',
        'Quick-create + e2e tier-w2 deep link',
        'Peer links витрина/лайншиты',
        'Редактирование маржи/бюджета (`range-planner-tier-plan-save-*`)',
        'EMPTY27 баннер (`range-planner-empty-chain-notice`)',
        'Назначение tier (`range-planner-tier-assign-panel`)',
        'Cabinet EMPTY27 plan CTA (`brand-dev-empty-range-link`, core-44)',
        'core-52 tier assign panel smoke',
        'core-53 PATCH margin core/trend/novelty + tier assign API',
        'Drag-reorder tier columns (`range-planner-tier-article-board`, core-58 e2e)',
        'Shop matrix + checkout peers (`brand-dev-range-shop-matrix-link`, `brand-dev-range-shop-checkout-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.rangePlanner}?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-dev-pg-sync',
      label: 'Статус разработки · PG',
      order: 4,
      staticScore: 7.1,
      liveScore: 8.0,
      summary: 'development-status API, peers + SLA ops panel на W2 hub.',
      good: [
        'API development-status',
        'Published-articles для витрины',
        'Sample queue в factory',
        'Бейдж статуса образца в DevelopmentPillarCard',
        'Позиция в очереди (`development-sample-queue-position`)',
        'workshop2-core-pg-sync-hint на W2 hub (core mode)',
        'Workshop2HubSlaOpsPanel compact на W2 hub (`workshop2-hub-sla-ops-panel`)',
        'PG sync peer strip (`brand-dev-pg-sync-peer-strip`: range/samples/factory/comms)',
        'core-02 столп 1 hub→W2→range→factory',
        'Прогресс % (`development-progress-pct`)',
        'Sample status → comms inbox bump (`sample_order.status_changed`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.productionWorkshop2}?${WORKSHOP2_COL_PARAM}=${encodeURIComponent(d.collectionId)}&article=${encodeURIComponent(d.demoArticleId)}`,
    },
    {
      id: 'brand-dev-cabinet',
      label: 'Кабинет · карточка столпа',
      order: 5,
      staticScore: 7.1,
      liveScore: 8.0,
      summary: 'DevelopmentPillarCard + EMPTY27 + sample/schema/BOM peers.',
      good: [
        'brand-dev-cabinet-panel + context/cross strips',
        'Progress/BOM/sample queue badges',
        'e2e development-bom-ready-badge + cabinet links',
        'Create-article deep-link через W2 hub (core-37)',
        'EMPTY27 onboarding strip (`brand-dev-empty-onboarding`, core-44)',
        'Sample lifecycle + attribute schema cabinet links (`brand-dev-cabinet-sample-lifecycle-link`, `brand-dev-cabinet-attribute-schema-link`)',
        'Supplier BOM peer when PG (`brand-dev-cross-supplier-bom-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.coreCabinet}?pillar=development&collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-dev-cross',
      label: 'Связь · цех и поставщик',
      order: 6,
      staticScore: 7.2,
      liveScore: 8.0,
      summary: 'Горизонталь к dossier цеха и supplier BOM; sample/schema peers в cabinet.',
      good: [
        'brand-dev-cross-context-strip в кабинете',
        'Sample peer: W2 plan / factory dossier read-only (platform-core-brand-sample-peer)',
        'Factory dossier + supplier BOM links с testids',
        'BOM + sample queue badges',
        'EMPTY27 onboarding в cabinet (core-44)',
        'Sample status → comms inbox bump (`sample_order.status_changed` + COMMS_INBOX_BUMP)',
        'Sample lifecycle comms peer strip (`brand-sample-lifecycle-comms-peer-strip`)',
        'Cabinet peers: sample lifecycle, attribute schema, supplier BOM',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        factoryProductionDossierHref(d.demoArticleId, { collectionId: d.collectionId }),
    },
    {
      id: 'brand-dev-attribute-schema',
      label: 'Attribute schema · health',
      order: 8,
      staticScore: 7.2,
      liveScore: 8.0,
      summary: 'PG schema + size-chart grade feed; golden path → material passport → release.',
      good: [
        'brand-attribute-schema workspace',
        'Golden path strip (`brand-attribute-schema-golden-path-strip`)',
        'PG schema feed API + sync catalog',
        'PG size-chart grade PATCH + handbook scale',
        'W2 fix links на attribute gaps',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.attributeHealth}?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-dev-material-passport',
      label: 'Material passport · rollup',
      order: 7,
      staticScore: 7.2,
      liveScore: 8.0,
      summary: 'Rollup/certs/release + golden path → release gate.',
      good: [
        'brand-material-passport workspace (rollup/certs/release)',
        'Golden path strip (`brand-material-passport-golden-path-strip`)',
        'PG rollup API + dossier composition overlay + sync',
        'PG certs patch ready + release blocked badge',
        'Certs toggle API + CSV export',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.fabricPassportRollup}?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-dev-rfq-supplier',
      label: 'Centric RFQ · upstream',
      order: 9,
      staticScore: 7.3,
      liveScore: 8.0,
      summary: 'Centric import/registry/quote award PG + golden path → supplier BOM.',
      good: [
        'brand-rfq-supplier workspace',
        'Golden path strip (`brand-rfq-supplier-golden-path-strip`)',
        'Centric import/registry/quote panels',
        'PG quote award API + supplier MRP cross-link',
        'Entity threads на comms tab',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.integrationsCentric}?collection=${encodeURIComponent(d.collectionId)}&${PILLAR_CAPABILITY_FEATURE_PARAM}=upstream`,
    },
    {
      id: 'brand-dev-supplier-bom',
      label: 'Supplier BOM · procurement',
      order: 10,
      staticScore: 7.3,
      liveScore: 8.0,
      summary: 'PG BOM lines seed + snapshot merge; golden path → Centric RFQ → forecast.',
      good: [
        'brand-supplier-bom workspace',
        'Golden path strip (`brand-supplier-bom-golden-path-strip`)',
        'PG BOM lines API + snapshot merge + default seed',
        'SupplierBomPreview + sync BOM',
        'Procurement entity threads',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.suppliersRfq}?collection=${encodeURIComponent(d.collectionId)}&${PILLAR_CAPABILITY_FEATURE_PARAM}=bom`,
    },
  ],
  sample_collection: [
    {
      id: 'brand-sc-linesheets',
      label: 'Лайншиты · коллекция',
      order: 1,
      staticScore: 7.0,
      liveScore: 8.5,
      summary: 'PG read-only, PDF, batch publish + audit log + unified audit path.',
      good: [
        'linesheets-core PG',
        'CTA → матрица на каждой строке + matrix qty badge + preview qty column',
        'Context strip PDF/showroom/W2/shop matrix/checkout',
        'e2e core-02',
        'Unpublish (`brand-sc-linesheets-unpublish-*`)',
        'Empty state CTA W2/витрина',
        'Empty fallback copy (`brand-sc-linesheets-empty-copy`, EMPTY27 honest)',
        'brand-sc-linesheets-batch-publish + readiness (core-28/41)',
        'brand-sc-publish-audit-log panel (core-29/41)',
        'Unified audit path на полной странице (core-46)',
        'Published sync badge W2 vs showroom (core-46)',
        'PDF disabled until publish (`brand-sc-linesheets-pdf-disabled`)',
        'Retail peer strip release→matrix→checkout (`brand-sc-linesheets-retail-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandLinesheetsHrefForDemo(d),
    },
    {
      id: 'brand-sc-showroom',
      label: 'Витрина бренда',
      order: 2,
      staticScore: 7.1,
      liveScore: 8.5,
      summary: 'Опубликованные артикулы, превью из досье — вход для магазина.',
      good: [
        'Published-articles API',
        'Showroom core chrome',
        'Release gate в unified audit path',
        'CTA «Матрица магазина» на карточке артикула',
        'Чат артикула с витрины (`brand-sc-showroom-article-chat-link-*`)',
        'Context strip: count + цепочка (`brand-sc-unified-audit-path`)',
        'Unified audit path на полной странице (core-45)',
        'Footer CTA matrix + linesheets',
        'e2e core-01 showroom cross-role',
        'Peer checkout e2e (`brand-sc-showroom-shop-checkout-link`, core-52)',
        'Golden path strip preview→shop matrix (`brand-showroom-buy-golden-path-strip`)',
        'Retail peer strip linesheets/release/platform/matrix/checkout (`brand-sc-showroom-retail-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandShowroomHrefForDemo(d),
    },
    {
      id: 'brand-sc-publish',
      label: 'Публикация · витрина',
      order: 3,
      staticScore: 7.1,
      liveScore: 8.5,
      summary: 'Связь W2 → published-articles — критично для витрины магазина.',
      good: [
        'Seed showroom SS27',
        'brand-sc-linesheets-batch-publish + publish audit (core-29/46)',
        'Кнопка «Снять с витрины» (`brand-sc-linesheets-unpublish-*`)',
        'PUT showroom published:false',
        'Workshop2HubShowroomPublishButton на W2 hub (`brand-dev-w2-hub-publish-strip`)',
        'Publish audit log на linesheets (core-29/46)',
        'Publish audit log на W2 hub (`brand-sc-publish-audit-log` в `brand-dev-w2-hub-panel`)',
        'Release golden path strip (`brand-release-golden-path-strip`)',
        'Release showroom-publish tab: bulk publish (`brand-sc-publish-button`, `brand-release-showroom-publish-panel`)',
        'Syndication push → publish strip CTA (`brand-release-syndication-push-publish-cta`)',
        'Publish release peer on W2 hub (`brand-sc-publish-release-peer-strip`)',
        'Publish peer shop matrix/checkout/platform/linesheets (`brand-sc-publish-shop-matrix-link`, `brand-sc-publish-platform-hub-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => `/brand/linesheets?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-sc-cross-matrix',
      label: 'Cross-role · матрица магазина',
      order: 4,
      staticScore: 7.1,
      liveScore: 8.5,
      summary: 'Инвест-перспектива: бренд видит путь ритейлера к заказу.',
      good: [
        'Единая цепочка в кабинете (`brand-sc-unified-audit-path`)',
        'Release gate в golden path (`brand-sc-audit-path-release-gate`)',
        'UAT cross-role strip (`brand-sc-cross-role-audit-uat-*`)',
        'Peer: matrix/checkout/showroom магазина',
        'Linesheets matrix qty badge',
        'Showroom/linesheets peer CTA',
        'e2e cabinet → shop matrix',
        'Peer checkout e2e (core-52)',
        'Cabinet retail peer platform/matrix/checkout (`brand-sc-cabinet-retail-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.shop.b2bMatrix}?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-sc-cabinet',
      label: 'Кабинет · лайншит и витрина',
      order: 5,
      staticScore: 7.1,
      liveScore: 8.5,
      summary: 'BrandSampleCollectionMini — counts и hub strips.',
      good: [
        'brand-sc-cabinet-panel + единая цепочка (`brand-sc-unified-audit-path`)',
        'Release gate step в audit path',
        'PG counts + published badge',
        'Error fallback с рабочими ссылками',
        'e2e core-01/06 cabinet',
        'core-02 + core-52 mini matrix + checkout deep-link e2e',
        'Published count sync badge mini↔live (`brand-sc-cabinet-published-sync`)',
        'Cabinet retail peer platform/matrix/checkout (`brand-sc-cabinet-retail-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.coreCabinet}?pillar=sample_collection&collection=${encodeURIComponent(d.collectionId)}`,
    },
  ],
  collection_order: [
    {
      id: 'brand-co-registry',
      label: 'Реестр оптовых заказов',
      order: 1,
      staticScore: 7.4,
      liveScore: 8.5,
      summary: 'Список B2B из PG + dynamic collections filter.',
      good: [
        'b2b-orders-core PG',
        'Legacy redirect B2B-00xx',
        'List chrome',
        'B2bChainPhaseBadge + фильтр коллекции',
        'Dynamic PG collections filter (`/api/workshop2/collections`, core-47)',
        'PG collections badge (`brand-co-registry-pg-collections-badge`)',
        'Экспорт CSV/JSON (`brand-co-registry-export-pg`, export-json)',
        'spineChannel в export (neutral RU)',
        'brand-co-registry-import-toolbar на core path',
        'core-32: JOOR import → export spineChannel e2e',
        'core-33 v1 operational PG-primary INT + native',
        'core-52 native B2B-DEMO in operational API',
        'core-43: checkout B2B-\\d+ в JSON export (clean PG)',
        'Context strip: заказ · в производстве · invite (без чата в strip)',
        'Канон panel/focus (`brand-co-registry-panel`, `brand-co-registry-focus-row`)',
        'SSE registry refetch при новом заказе (`registry-stream`)',
        'core-51 prebook row e2e (conditional seed)',
        'CRM invite (`brand-co-registry-invite-panel`, симметрия shop)',
        'Retail onboarding strip CRM/pricelist/showroom/matrix/checkout (`brand-co-registry-retail-onboarding-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (_d) => ROUTES.brand.b2bOrders,
    },
    {
      id: 'brand-co-detail',
      label: 'Карточка заказа',
      order: 2,
      staticScore: 7.2,
      liveScore: 8.5,
      summary: 'Факты PG — disclosure + comms section thread from detail chat (core-44/46).',
      good: [
        'PlatformCoreB2bOrderDetailFacts',
        'Цепочка заказа первым блоком — handoff без scroll',
        'POST confirm-order отдельно от handoff (`brand-b2b-confirm-order`)',
        'Amend approve/reject (`brand-b2b-amend-pending-panel`)',
        'PG lines table',
        'RU статусы',
        'e2e brand-b2b-factory-queue-link',
        'Panel + context strip (`brand-co-detail-panel`, `brand-co-detail-context-strip`)',
        'Shop disclosure preview strip (core-21/29/39)',
        'core-39 clean PG detail smoke',
        'core-44: disclosure → shop tracking на B2B-\\d+',
        'Order detail chat → ?pillar&section + auto-thread (core-46)',
        'Nav dedup: footer cross-links удалены',
        'brand-order-comms golden path strip + registry SoT (`brand-order-comms-golden-registry-link`)',
        'Досье до handoff (`brand-co-detail-dossier-card`)',
        'Production noise скрыт без `?pillar=order_production`',
        'core-51 prebook badge e2e (conditional seed)',
        'Retail onboarding strip на detail tab (`brand-co-registry-retail-onboarding-strip`)',
        'Golden path shop matrix + checkout (`brand-order-comms-golden-shop-matrix-link`, `brand-order-comms-golden-checkout-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandB2bOrderHref(d.demoOrderId),
    },
    {
      id: 'brand-co-retailers',
      label: 'Сеть ритейлеров',
      order: 3,
      staticScore: 7.1,
      liveScore: 8.0,
      summary: 'Партнёры B2B — PG tier + multi-buyer из W2 summary.',
      good: [
        'Retailers core path',
        'Panel + context strip (`brand-co-retailers-panel`)',
        'CRM segments + pricelist assign (`brand-co-retailers-crm-*-link`)',
        'Фильтр заказов через `brandB2bOrdersRegistryHref({ partner })`',
        'CTA «Заказы» + «Витрина» (`brand-co-retailers-showroom-link-*`)',
        'Карточка (`brand-co-retailer-detail-panel`, context strip)',
        'PG tier badge (`retailer-tier-badge-*`, data-tier-source=pg, core-47)',
        'Tier из order.tier + volume (`/api/brand/retailers/b2b-orders-summary`)',
        'Multi-buyer discovery из PG orders (не только shop1 preset)',
        'displayNameRu из PG summary + shopCoreBuyerLabelRu (`retailer-display-name-*`, core-52)',
      ],
      bad: [],
      fix: [],
      resolveHref: () => ROUTES.brand.retailers,
    },
    {
      id: 'brand-co-chain',
      label: 'Этапы цепочки · заказ',
      order: 4,
      staticScore: 7.3,
      liveScore: 8.5,
      summary: 'shop_sent / brand_confirmed — мост к производству.',
      good: [
        'chain-status API',
        'CollectionOrderPillarCard steps (`brand-co-chain-hub-steps`)',
        'Inline confirm + handoff buttons (`brand-b2b-confirm-order`, `brand-b2b-confirm-production-handoff`)',
        'Ритейлеры peer (`brand-co-chain-retailers-link`)',
        'Карточка заказа: `brand-co-chain-card` + context strip',
        'Шаги shop_sent/brand_confirmed без production noise',
        'Два CTA: confirm-order → handoff',
        'SLA бейдж «Ожидает подтверждения»',
        'CTA передача после confirm (`collection-order-handoff-link`)',
        'SSE/poll (`brand-co-chain-sse-live-badge`)',
        'Inline «Полная цепочка» в context strip (`brand-co-chain-full-link`)',
        'Системное сообщение в чат при checkout',
        'Shop matrix + checkout + CRM peers в context strip (`brand-co-chain-shop-matrix-link`, `brand-co-chain-crm-pricelist-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandB2bOrderHref(d.demoOrderId),
    },
    {
      id: 'brand-co-cabinet',
      label: 'Кабинет · приём заказов',
      order: 5,
      staticScore: 7.0,
      liveScore: 8.5,
      summary: 'Pillar card + CTA на реестр/заказ + PG partner count.',
      good: [
        'CollectionOrderPillarCard brand',
        'CommsNotificationCenterStrip compact (`brand-co-cabinet-panel`)',
        'Panel + CTA groups (`brand-co-cabinet-panel`, `cta-orders`/`cta-peer`)',
        'PG partner count badge (`brand-co-cabinet-partner-count`, core-47)',
        'Сводка qty и сумма заказа',
        'Handoff + SLA + hub steps',
        'e2e collection-order-qty-summary + retailers link',
        'Shop peer picker на checkout (`shop-co-checkout-buyer-picker`, `shop-b2b-buyer-switcher`)',
        'Cross-role checkout deep-link shop1/shop2 (`brand-co-cabinet-checkout-*-link`)',
        'Multi-buyer registry filter (`brand-co-cabinet-partner-filter`, partner links)',
        'Compact retail onboarding strip CRM→checkout (`brand-co-registry-retail-onboarding-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.coreCabinet}?pillar=collection_order&collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-co-wssi-plan',
      label: 'WSSI · OTB → shop buy',
      order: 6,
      staticScore: 7.2,
      liveScore: 8.0,
      summary: 'OTB/mix/capacity PG ledger + editable targets; golden path → shop matrix/showroom/checkout.',
      good: [
        'brand-wssi-plan workspace (otb/mix/capacity tabs)',
        'Golden path strip (`brand-wssi-golden-path-strip`)',
        'PG OTB ledger API + editable target % + sync catalog',
        'Shop matrix + showroom + checkout cross-links из golden path',
        'Capacity → W2 supply + production ops (без дубля showroom)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.assortmentMixPlanner}?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-co-crm-segmentation',
      label: 'CRM · сегменты → showroom',
      order: 7,
      staticScore: 7.3,
      liveScore: 8.0,
      summary: 'PG segments + PATCH net terms/discount; golden path → shop matrix.',
      good: [
        'brand-crm-segmentation workspace',
        'Golden path strip (`brand-crm-golden-path-strip`)',
        'PG segments fetch + PATCH net terms / first-order discount',
        'Pricelist/showroom panels trimmed (3 CTA max)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.customerGroups}?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-co-agent-rep',
      label: 'Agent rep · brand oversight',
      order: 8,
      staticScore: 7.3,
      liveScore: 8.0,
      summary: 'Persisted commission ledger seed + refresh; golden path ↔ shop co-agent-rep.',
      good: [
        'brand-agent-rep workspace',
        'Golden path strip (`brand-agent-rep-golden-path-strip`)',
        'PG/file commission ledger seed (no demo_stub fallback)',
        'Shop portal/commission cross-links',
      ],
      bad: [],
      fix: [],
      resolveHref: () => `${ROUTES.brand.distributor.commissions}`,
    },
    {
      id: 'brand-co-pricelist',
      label: 'Price lists · tier sync',
      order: 9,
      staticScore: 7.3,
      liveScore: 8.0,
      summary: 'Versions/tiers/shop-sync + golden path → matrix → CRM → checkout.',
      good: [
        'brand-pricelist workspace',
        'Golden path strip (`brand-pricelist-golden-path-strip`)',
        'PG pricelist versions API + editable multiplier + sync',
        'PG tier sync push (`brand-pricelist-shop-sync-panel`)',
        'Group filter + versions table',
        'Checkout step (`brand-pricelist-golden-checkout-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.priceLists}?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-co-pack-rules',
      label: 'Pack rules · MOQ',
      order: 10,
      staticScore: 7.2,
      liveScore: 8.0,
      summary: 'Rules/curve/shop-prepack + golden path → matrix prepack → checkout.',
      good: [
        'brand-pack-rules workspace',
        'Golden path strip (`brand-pack-rules-golden-path-strip`)',
        'PG pack rules API + editable MOQ/case pack + sync',
        'Curve + shop prepack cross-links',
        'Checkout step (`brand-pack-rules-golden-checkout-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.packRules}?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-co-landed-margin',
      label: 'Landed margin · brand',
      order: 11,
      staticScore: 7.2,
      liveScore: 8.0,
      summary: 'Simulator/pricelist/shop-rollup + golden path → shop matrix → checkout.',
      good: [
        'brand-landed-margin workspace',
        'Golden path strip (`brand-landed-margin-golden-path-strip`)',
        'PG margin feed · simulator defaults + shop rollup preview',
        'Bridge panels shop rollup/pricelist',
        'Checkout step (`brand-landed-margin-golden-checkout-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.marginSimulator}?collection=${encodeURIComponent(d.collectionId)}`,
    },
  ],
  order_production: [
    {
      id: 'brand-op-handoff',
      label: 'Передача в производство',
      order: 1,
      staticScore: 7.5,
      liveScore: 8.5,
      summary: 'confirm-order → handoff → ERP retry на clean PG (core-34 ✓).',
      good: [
        'Handoff API',
        'e2e core-02/03',
        'Retry UI (`brand-b2b-handoff-retry`) + error alert',
        'ERP retry UI (`brand-b2b-erp-retry`) + POST API',
        'core-34: clean PG ERP retry после handoff',
        'Кнопка gated на handedOff, не status',
        'Context strip cross-role (`brand-order-handoff-context-strip`)',
        'SSE/poll badge в chain card (`brand-op-chain-*`)',
        'Strip CTA канон (`brand-op-handoff-factory-queue-link`, `brand-op-handoff-prod-orders-link`)',
        'CTA «Передача» в реестре (`brand-b2b-order-handoff-*`)',
        'Bulk handoff (`brand-b2b-bulk-handoff`, `brand-b2b-order-select-*`)',
        'Deep link `brandB2bOrderHandoffContextHref` + awaiting registry',
        'Production ops handoff tab: manufacturer QC + factory-ack cross-links (`brand-production-handoff-*`)',
        'QC gate tab: chain SSE/poll + handoff/mfr QC cross-links (`brand-production-qc-chain-*`, `brand-qc-gate-*`)',
        'Chain SSE/poll badge на handoff tab (`brand-production-handoff-chain-*`)',
        'Golden path strip (`brand-production-ops-golden-path-strip`)',
        'Очередь цеха с order context (`brand-b2b-factory-queue-link`)',
        'PO → queue link в реестре (`brand-b2b-order-po-link-*`)',
        'ERP auto-retry backoff после factory bulk ack (erpNextRetryAt + queue poll)',
        'Inventory + order comms peer strip (`brand-op-handoff-inventory-peer-strip`)',
        'CO spine peer shop matrix/checkout/tracking/mfr (`brand-op-handoff-co-spine-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandB2bOrderHandoffContextHref(d.demoOrderId),
    },
    {
      id: 'brand-op-chain',
      label: 'Статус цепочки · PO',
      order: 2,
      staticScore: 7.2,
      liveScore: 8.5,
      summary: '5 шагов chain-status; SoT strip → dossier anchor.',
      good: [
        'B2bOrderChainStatusCard (`brand-order-chain-status-card`)',
        'brand-op-chain-sse/poll badge',
        'brand-order-chain-context-strip + poll badge',
        'Cross-links чат/календарь/трекинг магазина',
        'OrderProductionPillarCard (`brand-op-chain-steps`)',
        'PO id badge + materials step badges',
        'ERP retry (`brand-b2b-erp-retry`, core-34)',
        'SSE badge только на chain card (dedup strip)',
        'Dossier SoT strip (`brand-op-chain-dossier-sot-strip`, anchor #production-dossier)',
        'CO spine peer strip matrix/checkout/tracking/mfr (`brand-op-chain-co-spine-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandB2bOrderChainContextHref(d.demoOrderId),
    },
    {
      id: 'brand-op-dossier',
      label: 'Досье · W2 бренда',
      order: 3,
      staticScore: 7.0,
      liveScore: 8.0,
      summary: 'ТЗ на карточке заказа + deep-link W2 + production peers.',
      good: [
        'Карточка ТЗ на order detail (`brand-order-w2-dossier-card`, `#production-dossier`)',
        'W2 deep-link material (`brandW2ProductionTzHref`, `brand-op-w2-dossier-link`)',
        'Peer досье цеха после handoff (`brand-order-factory-dossier-link`)',
        'Бейдж фиксации + diff (`brand-order-w2-dossier-locked-badge`, `*-diff-*`)',
        'Production peer strip: chain/handoff/QC/cut-ticket/mfr QC/shop tracking (`brand-op-dossier-production-peer-strip`)',
        'Навигация handoff/chain — в chain card',
        'Core dossier strip без чата — comms pillar',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandB2bOrderDossierContextHref(d.demoOrderId),
    },
    {
      id: 'brand-op-registry',
      label: 'Реестр · контекст заказов',
      order: 4,
      staticScore: 7.0,
      liveScore: 8.0,
      summary: 'Реестр OP + production peer strip (QC/handoff/tracking).',
      good: ['Фильтры handoff/in_production', 'Context strip: трекинг (без чата в core)', 'OP registry production peers (`brand-op-registry-production-peer-strip`)'],
      bad: [],
      fix: [],
      resolveHref: (d) => brandB2bOrdersProductionRegistryHref(d.demoOrderId),
    },
    {
      id: 'brand-op-cabinet',
      label: 'Кабинет · заказ→производство',
      order: 5,
      staticScore: 7.0,
      liveScore: 8.5,
      summary: 'Hub insight: chain steps + BOM + peer CTA; clean PG PO badge (core-49).',
      good: [
        'Panel (`brand-op-cabinet-panel`)',
        'SoT strip → order detail + registry (`brand-op-cabinet-sot-strip`)',
        'CTA strip реестр/передача/трекинг (`brand-op-cabinet-cta-strip`, чат — comms)',
        'SSE/poll badge (`brand-op-cabinet-*-badge`)',
        'Registry с `?order=` · materials step link',
        'PO badge → prod-orders (`brand-op-po-id-badge`)',
        'Clean PG chain steps (core-49)',
        'WMS/materials badges + BOM count badge',
        'compact-only hub',
        'Cabinet spine peer handoff/QC/tracking/mfr/registry (`brand-op-cabinet-spine-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandCoreOrderProductionCabinetHref(d.collectionId),
    },
    {
      id: 'brand-op-inventory-ops',
      label: 'Inventory · brand ledger',
      order: 6,
      staticScore: 7.3,
      liveScore: 8.0,
      summary: 'PG ledger strip on overview/network + golden path → shop reconcile.',
      good: [
        'brand-inventory-ops workspace',
        'Golden path strip (`brand-inventory-ops-golden-path-strip`)',
        'PlatformCoreInventoryLedgerStrip (`brand-inventory-ledger-strip`)',
        'Shop reconcile/tracking cross-links',
        'Products matrix + legacy UI entry',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.inventory}?${PILLAR_CAPABILITY_FEATURE_PARAM}=overview&collection=${encodeURIComponent(d.collectionId)}`,
    },
  ],
  comms: [
    {
      id: 'brand-cm-order-chat',
      label: 'Чат · оптовый заказ',
      order: 1,
      staticScore: 7.1,
      liveScore: 8.5,
      summary: 'Контекстный тред B2B — координация с магазином; SSE unread + registry stream.',
      good: [
        'contextType b2b_order',
        'slim messages core',
        'Entity banner',
        'Чат из реестра заказов',
        'Превью треда в реестре',
        'Universal inbox: все заказы PG в sidebar',
        'B2B шаблоны (ship-window, qty-confirm) в slimCore',
        'core-14 e2e templates',
        'PG unread в ChatList + registry SSE bump',
        'comms-pillar-unread-badge на inbox',
        'brand-cm-order-context-strip',
        'brand-cm-order-chat-link в hub',
        'Server read receipts (PG workshop2_contextual_read_state)',
        'Read-state actor из session uid',
        'ContextualChatThread SSE live (`contextual-chat-sse-live-badge`) + poll fallback',
        'Сохранение своих шаблонов (`platform-core-b2b-message-template-save-draft`, localStorage)',
        'Order workspace notification bar + registry stream health (`brand-cm-order-registry-stream-health-strip`)',
        'Order context peer strip CO+monetization (`brand-cm-order-context-strip`, `brand-cm-order-shop-checkout-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandMessagesB2bOrderContextHref(d.demoOrderId),
    },
    {
      id: 'brand-cm-article-chat',
      label: 'Чат · артикул W2',
      order: 2,
      staticScore: 7.2,
      liveScore: 8.0,
      summary: 'Связь разработки с цехом/поставщиком по артикулу.',
      good: [
        'workshop2_article context',
        'brand-dossier-article-chat-link',
        'brand-cm-article-context-strip',
        'brand-cm-article-messages-link в W2 drawer',
        'Экспорт ТЗ рядом с чатом (`brand-w2-tz-export-btn`)',
        'Прикрепление ZIP ТЗ в тред (`brand-w2-tz-attach-chat-btn`)',
        'Ссылка на вложение в contextual chat (`contextual-chat-attachment-link`)',
        'ContextualChatThread SSE live на article context',
        'W2 drawer: usePlatformCoreCommsInboxPoll + poll badge (`workshop2-article-chat-poll-badge`)',
        'Investor summary + production QC + order comms peers (`brand-cm-article-investor-summary-link`, `brand-cm-article-production-ops-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandMessagesWorkshop2ArticleContextHref(d.collectionId, d.demoArticleId),
    },
    {
      id: 'brand-cm-calendar',
      label: 'Календарь · заказ',
      order: 3,
      staticScore: 7.0,
      liveScore: 8.5,
      summary: 'Слоты отгрузки, события chain — investor «план поставок» + CO spine peers.',
      good: [
        'Calendar B2B context',
        'Canonical URLs',
        'targetChatId в calendar-events API',
        'EventDialog «Чат» при клике на B2B-событие',
        'platform-core-comms-cross-nav + brand-cm-order-context-strip',
        'PG user-task create + refetch (core-23)',
        'GET user-task list strip (`brand-cm-calendar-user-tasks-strip`)',
        'Task deep-link + chat CTA (`brand-cm-calendar-user-tasks-task-*`)',
        'Task strip refetch после create (`reloadNonce`)',
        'Context peer handoff/registry/shop tracking/CRM (`brand-cm-calendar-context-peer-strip`)',
        'brand-cm-calendar-events-badge',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandCalendarB2bOrderContextHref(d.demoOrderId),
    },
    {
      id: 'brand-cm-banner',
      label: 'Контекст-баннер · URL',
      order: 4,
      staticScore: 7.1,
      liveScore: 8.0,
      summary: 'Dedupe баннеров при ?order= / ?chat=; SSE comms bump + registry stream.',
      good: [
        'CommunicationsEntityContextBanner',
        'brand-cm-banner testid',
        'Core B2B msg/cal hrefs (не syntha overlay)',
        'Policy strip off при URL и workspace',
        'core-14 banner dedupe e2e (4 роли)',
        'core-13 cross-nav',
        'Production-context banner → W2 article chat + dossier',
        'Registry SSE refetch unread',
        'Article workspace SSE inbox bump (`workshop2-article-chat-button` + inbox-stream)',
        'Order context registry stream on workspace bar (`brand-cm-order-registry-stream-health-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandMessagesB2bOrderContextHref(d.demoOrderId),
    },
    {
      id: 'brand-cm-section-groups',
      label: 'Группы по разделам',
      order: 5,
      staticScore: 7.5,
      liveScore: 8.1,
      summary: 'Section-groups: clean PG four-role deep-link + PG read SoT.',
      good: [
        'brand-cm-section-groups-picker UI',
        'Deep-link ?pillar=&section= (core-21 e2e)',
        'Clean PG B2B-\\d+ deep-link 4 roles (core-40)',
        'Section contextual auto-thread (core-30)',
        'Order detail / tracking chat → section deep-link (core-46)',
        'Registry SSE bump на contextual message',
        'comms-pillar-sse-live-badge на hub (core-35)',
        'Unread badge на section-group chip',
        'Section visit cursor local + POST section-read-state',
        'PG mirror в workshop2_contextual_read_state (b2b_order_section)',
        'PG-primary skip file mirror',
        'core-52 contextual POST→GET PG round-trip',
        'Audit guard comms-canon',
        'Исключение meta-section из picker',
        'Calendar user-task POST + fail-closed hint (`brand-cm-calendar-pg-required-hint`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.coreCabinet}?pillar=comms&collection=${encodeURIComponent(d.collectionId)}&section=brand-co-registry`,
    },
    {
      id: 'brand-cm-cabinet',
      label: 'Кабинет · связь',
      order: 6,
      staticScore: 7.2,
      liveScore: 8.5,
      summary: 'CommsPillarCard, PG unread + clean PG thread strip (core-40).',
      good: [
        'brand-cm-cabinet-po-inbox из реестра B2B',
        'CommsPillarCard compact-only',
        'Registry stream health + refresh (`brand-cm-cabinet-registry-stream-health-strip`)',
        'comms-pillar-unread-badge + SSE live (core-35)',
        'Clean PG order chat link (core-20/40)',
        'brand-cm-cabinet-thread-search hub',
        'brand-cm-thread-search workspace',
        'brand-cm-order/article/calendar-link hub (волны 68–70)',
        'CTA «Все треды» + unread на inbox',
        'Entity threads tab: inbox SSE/poll badge (`brand-comms-entity-threads-sse-*`)',
        'brand-comms-workspace golden path (`brand-comms-workspace-golden-path-strip`)',
        'Cabinet spine peer registry→checkout→CRM (`brand-cm-cabinet-spine-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.coreCabinet}?pillar=comms&collection=${encodeURIComponent(d.collectionId)}`,
    },
  ],
};
