/**
 * @generated split from platform-core-readiness-sections.ts — do not edit monolith; edit role file.
 */
import type { CoreHubPillarId } from '@/lib/platform-core-hub-matrix';
import {
  brandLinesheetsHrefForDemo,
  brandShowroomHrefForDemo,
  factoryHandoffQueueHrefForDemo,
  factoryMaterialsHrefForDemo,
  factoryMaterialsProcurementHrefForDemo,
  platformCoreRolePillarHref,
  shopShowroomHrefForDemo,
} from '@/lib/platform-core-hub-matrix';
import {
  ROUTES,
  brandB2bOrderChainContextHref,
  brandB2bOrderDossierContextHref,
  brandB2bOrderHandoffContextHref,
  brandB2bOrderHref,
  brandB2bOrdersAwaitingHandoffRegistryHref,
  brandB2bOrdersProductionRegistryHref,
  brandCoreOrderProductionCabinetHref,
  brandCalendarB2bOrderContextHref,
  brandMessagesB2bOrderContextHref,
  brandMessagesWorkshop2ArticleContextHref,
  brandW2ProductionTzHref,
  factoryMessagesB2bOrderContextHref,
  factoryMessagesWorkshop2ArticleContextHref,
  factoryCoreOrderProductionCabinetHref,
  factorySupplierCoreOrderProductionCabinetHref,
  factoryProductionDossierContextHref,
  factoryProductionDossierHref,
  factoryProductionOrdersOrderContextHref,
  factorySupplierMessagesB2bOrderContextHref,
  factorySupplierMessagesWorkshop2ArticleContextHref,
  shopB2bOrderHref,
  shopB2bOrderProductionContextHref,
  shopB2bOrdersProductionRegistryHref,
  shopB2bTrackingOrderHref,
  shopCalendarB2bOrderContextHref,
  shopMessagesB2bOrderContextHref,
} from '@/lib/routes';
import { WORKSHOP2_COL_PARAM, workshop2ArticleHref } from '@/lib/production/workshop2-url';
import type { SectionAuditTemplate } from './types';

export const BRAND_SECTION_AUDIT: Partial<Record<CoreHubPillarId, readonly SectionAuditTemplate[]>> = {
    development: [
      {
        id: 'brand-dev-w2-hub',
        label: 'Цех разработки · коллекция',
        order: 1,
        staticScore: 7.3,
        liveScore: 7.5,
        summary: 'Hub артикулов, PG-hydrate, EMPTY27 onboarding (волна 25).',
        good: [
          'PG-authoritative SS27/FW27',
          'brand-dev-w2-hub-panel + context strip',
          'Peer: range/linesheets/showroom/factory dossier/sample queue',
          'UI «Создать артикул» (`brand-w2-create-article-btn`)',
          'Bulk-import SKU (`brand-w2-bulk-import-*`, core-30 e2e)',
          'Create-article wizard UI round-trip (core-37 e2e)',
          'PG sync hint (`workshop2-core-pg-sync-hint`)',
          'e2e core-01 + core-02 smoke',
          'EMPTY27 onboarding (`brand-dev-empty-onboarding`, core-44)',
        ],
        bad: ['Investor PDF export артикула'],
        fix: ['E2E TZ PDF export на dossier'],
        resolveHref: (d) =>
          `${ROUTES.brand.productionWorkshop2}?${WORKSHOP2_COL_PARAM}=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'brand-dev-dossier',
        label: 'Досье артикула · техзадание',
        order: 2,
        staticScore: 7.4,
        liveScore: 7.2,
        summary: 'Паспорт, persist API — все секции ТЗ + составник 4 шага (core-02 e2e).',
        good: [
          'brand-dev-dossier-panel + context/cross strips',
          'PUT/GET dossier PG',
          'e2e UI 4 поля general + API 3 поля passportProductionBrief (core-02)',
          'e2e material: BOM + composition wizard 1–4 + fiber constructor UI/API (core-02)',
          'e2e construction: smartRoutingSequence equipment UI + API round-trip (core-02)',
          'e2e assignment: PG chip + factory handoff gate (core-02)',
          'brand-dossier-article-chat-link',
          'Gates ТЗ link (`brand-w2-gates-summary-link`)',
          'BOM/sample badges в wayfinding',
          'Скачать пакет ТЗ (`brand-w2-tz-export-btn`) + статус gate',
          'Отправить ТЗ в чат (`brand-w2-tz-attach-chat-btn`) + e2e core-02',
        ],
        bad: ['Investor-summary read-only отдельно', 'PDF/SVG export не в e2e'],
        fix: ['E2E PDF export composition label'],
        resolveHref: (d) =>
          workshop2ArticleHref(d.collectionId, d.demoArticleId, { w2sec: 'general' }),
      },
      {
        id: 'brand-dev-range',
        label: 'Планировщик ассортимента',
        order: 3,
        staticScore: 7.3,
        liveScore: 7.3,
        summary: 'Tier, бюджет, маржа из PG — EMPTY27 onboarding в cabinet (волна 25).',
        good: [
          'brand-dev-range-panel + context strip (W2/dossier/factory/showroom/linesheets)',
          'budgetFromPg на SS27/FW27 e2e',
          'Tier SKU counts из PG',
          'Сводка маржи (`range-planner-margin-summary`)',
          'Ссылка tier → W2 (`range-planner-tier-w2-link`)',
          'Quick-create + e2e tier-w2 deep link',
          'Peer links витрина/лайншиты',
          'Редактирование маржи/бюджета (`range-planner-tier-plan-save-*`)',
          'EMPTY27 баннер (`range-planner-empty-chain-notice`)',
          'Назначение tier (`range-planner-tier-assign-panel`)',
          'Cabinet EMPTY27 plan CTA (`brand-dev-empty-range-link`, core-44)',
        ],
        bad: ['Нет drag-reorder между tier'],
        fix: ['Drag-reorder SKU между колонками tier'],
        resolveHref: (d) =>
          `${ROUTES.brand.rangePlanner}?collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'brand-dev-pg-sync',
        label: 'Статус разработки · PG',
        order: 4,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'development-status API, шаги цепочки, опубликованные артикулы.',
        good: [
          'API development-status',
          'Published-articles для витрины',
          'Sample queue в factory',
          'Бейдж статуса образца в DevelopmentPillarCard',
          'Позиция в очереди (`development-sample-queue-position`)',
          'workshop2-core-pg-sync-hint на W2 hub (core mode)',
          'core-02 столп 1 hub→W2→range→factory',
          'Прогресс % (`development-progress-pct`)',
        ],
        bad: ['Нет push при смене статуса образца'],
        fix: ['Push при смене статуса образца'],
        resolveHref: (d) =>
          `${ROUTES.brand.productionWorkshop2}?${WORKSHOP2_COL_PARAM}=${encodeURIComponent(d.collectionId)}&article=${encodeURIComponent(d.demoArticleId)}`,
      },
      {
        id: 'brand-dev-cabinet',
        label: 'Кабинет · карточка столпа',
        order: 5,
        staticScore: 7.1,
        liveScore: 7.3,
        summary: 'DevelopmentPillarCard + EMPTY27 onboarding (core-44).',
        good: [
          'brand-dev-cabinet-panel + context/cross strips',
          'Progress/BOM/sample queue badges',
          'e2e development-bom-ready-badge + cabinet links',
          'Create-article deep-link через W2 hub (core-37)',
          'EMPTY27 onboarding strip (`brand-dev-empty-onboarding`, core-44)',
        ],
        bad: ['Quick-create без range tier assign e2e'],
        fix: ['E2E tier assign после create'],
        resolveHref: (d) =>
          `${ROUTES.brand.coreCabinet}?pillar=development&collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'brand-dev-cross',
        label: 'Связь · цех и поставщик',
        order: 6,
        staticScore: 7.0,
        liveScore: 7.1,
        summary: 'Горизонталь к manufacturer dossier и supplier BOM + EMPTY27 plan CTA.',
        good: [
          'brand-dev-cross-context-strip в кабинете',
          'W2 hub → factory dossier + sample queue',
          'Factory dossier + supplier BOM links с testids',
          'Sample handoff CTA',
          'BOM + sample queue badges',
          'EMPTY27 onboarding в cabinet (core-44)',
        ],
        bad: ['Нет push при смене статуса образца'],
        fix: ['SSE sample queue для бренда'],
        resolveHref: (d) =>
          factoryProductionDossierHref(d.demoArticleId, { collectionId: d.collectionId }),
      },
    ],
    sample_collection: [
      {
        id: 'brand-sc-linesheets',
        label: 'Лайншиты · коллекция',
        order: 1,
        staticScore: 7.0,
        liveScore: 7.6,
        summary: 'PG read-only, PDF, batch publish + audit log + unified audit path (волна 27).',
        good: [
          'linesheets-core PG',
          'CTA → матрица на каждой строке + matrix qty badge',
          'Context strip PDF/showroom/W2/shop matrix/checkout',
          'e2e core-02',
          'Unpublish (`brand-sc-linesheets-unpublish-*`)',
          'Empty state CTA W2/витрина',
          'brand-sc-linesheets-batch-publish + readiness (core-28/41)',
          'brand-sc-publish-audit-log panel (core-29/41)',
          'Unified audit path на полной странице (core-46)',
          'Published sync badge W2 vs showroom (core-46)',
        ],
        bad: ['Empty PDF edge cases'],
        fix: ['UAT linesheet→showroom diff'],
        resolveHref: (d) => brandLinesheetsHrefForDemo(d),
      },
      {
        id: 'brand-sc-showroom',
        label: 'Витрина бренда',
        order: 2,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'Опубликованные артикулы, превью из досье — вход для магазина.',
        good: [
          'Published-articles API',
          'Showroom core chrome',
          'CTA «Матрица магазина» на карточке артикула',
          'Чат артикула с витрины (`brand-sc-showroom-article-chat-link-*`)',
          'Context strip: count + matrix/checkout/linesheets/publish (`brand-sc-showroom-context-strip`)',
          'Unified audit path на полной странице (`brand-sc-unified-audit-path`, core-45)',
          'Footer CTA matrix + linesheets',
          'e2e core-01 showroom cross-role',
        ],
        bad: ['Дубль с linesheets по смыслу', 'Нет inline preview matrix'],
        fix: ['Preview qty в linesheet', 'UAT cross-role showroom→matrix via audit path'],
        resolveHref: (d) => brandShowroomHrefForDemo(d),
      },
      {
        id: 'brand-sc-publish',
        label: 'Публикация · витрина',
        order: 3,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'Связь W2 → published-articles — критично для витрины магазина.',
        good: [
          'Seed showroom SS27',
          'brand-sc-publish-panel на linesheets (W2/showroom/peer)',
          'Кнопка «Снять с витрины» (`brand-sc-linesheets-unpublish-*`)',
          'PUT showroom published:false',
          'Workshop2HubShowroomPublishButton на W2 hub (`brand-dev-w2-hub-publish-strip`)',
          'Publish audit log на linesheets (core-29/46)',
        ],
        bad: ['Audit log не на W2 hub'],
        resolveHref: (d) => `/brand/linesheets?collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'brand-sc-cross-matrix',
        label: 'Cross-role · матрица магазина',
        order: 4,
        staticScore: 7.1,
        liveScore: 7.1,
        summary: 'Инвест-перспектива: бренд видит путь ритейлера к заказу.',
        good: [
          'brand-sc-cross-matrix-context-strip в кабинете',
          'Unified audit path → shop matrix (core-26/45)',
          'Peer: matrix/checkout/showroom магазина',
          'Linesheets matrix qty badge',
          'Showroom/linesheets peer CTA',
          'e2e cabinet → shop matrix',
        ],
        bad: ['Нет read-only matrix peek modal'],
        fix: ['Inline qty preview modal', 'UAT brand peer → shop checkout'],
        resolveHref: (d) =>
          `${ROUTES.shop.b2bMatrix}?collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'brand-sc-cabinet',
        label: 'Кабинет · лайншит и витрина',
        order: 5,
        staticScore: 7.1,
        liveScore: 7.1,
        summary: 'BrandSampleCollectionMini — counts и hub strips.',
        good: [
          'brand-sc-cabinet-panel + context strip (linesheets/showroom/W2)',
          'Unified audit path cabinet + full showroom (core-26/45)',
          'PG counts + published badge',
          'Error fallback с рабочими ссылками',
          'Cross-matrix strip (peer shop)',
          'e2e core-01/06 cabinet',
        ],
        bad: ['Дубль mini vs полная страница'],
        fix: ['Синхрон counts mini/page', 'UAT cabinet → full pages'],
        resolveHref: (d) =>
          `${ROUTES.brand.coreCabinet}?pillar=sample_collection&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
    collection_order: [
      {
        id: 'brand-co-registry',
        label: 'Реестр оптовых заказов',
        order: 1,
        staticScore: 7.4,
        liveScore: 7.8,
        summary: 'Список B2B из PG + dynamic collections filter (волна 28).',
        good: [
          'b2b-orders-core PG',
          'Legacy redirect B2B-00xx',
          'List chrome',
          'B2bChainPhaseBadge + фильтр коллекции',
          'Dynamic PG collections filter (`/api/workshop2/collections`, core-47)',
          'PG collections badge (`brand-co-registry-pg-collections-badge`)',
          'Экспорт CSV/JSON (`brand-co-registry-export-pg`, export-json)',
          'spineChannel в export (neutral RU, волна 11–12)',
          'brand-co-registry-import-toolbar на core path',
          'core-32: JOOR import → export spineChannel e2e',
          'core-33: v1 operational list/detail INT-* из PG (PG-primary)',
          'core-43: checkout B2B-\\d+ в JSON export (clean PG)',
          'Context strip столп 3 (`brand-co-registry-context-strip`)',
          'Канон panel/focus (`brand-co-registry-panel`, `brand-co-registry-focus-row`)',
          'SSE registry refetch при новом заказе (`registry-stream`)',
        ],
        bad: ['Pre-orders отдельный маршрут вне golden chain'],
        fix: ['Prebook row e2e при появлении seed'],
        resolveHref: () => ROUTES.brand.b2bOrders,
      },
      {
        id: 'brand-co-detail',
        label: 'Карточка заказа',
        order: 2,
        staticScore: 7.2,
        liveScore: 7.8,
        summary: 'Факты PG — disclosure + comms section thread from detail chat (core-44/46).',
        good: [
          'PlatformCoreB2bOrderDetailFacts',
          'Цепочка заказа первым блоком — handoff без scroll',
          'POST confirm-order отдельно от handoff (`brand-b2b-confirm-order`)',
          'Amend approve/reject (`brand-b2b-amend-pending-panel`, волна 98)',
          'PG lines table',
          'RU статусы',
          'e2e brand-b2b-factory-queue-link',
          'Panel + context strip (`brand-co-detail-panel`, `brand-co-detail-context-strip`)',
          'Shop disclosure preview strip (core-21/29/39)',
          'core-39 clean PG detail smoke',
          'core-44: disclosure → shop tracking на B2B-\\d+',
          'Order detail chat → ?pillar&section + auto-thread (core-46)',
          'Nav dedup: footer cross-links удалены (волна 17)',
          'Досье до handoff (`brand-co-detail-dossier-card`)',
          'Production noise скрыт без `?pillar=order_production` (волна 84)',
        ],
        bad: ['Pre-orders отдельный маршрут вне golden chain'],
        fix: ['Prebook row e2e при появлении seed'],
        resolveHref: (d) => brandB2bOrderHref(d.demoOrderId),
      },
      {
        id: 'brand-co-retailers',
        label: 'Сеть ритейлеров',
        order: 3,
        staticScore: 7.1,
        liveScore: 7.3,
        summary: 'Партнёры B2B — PG tier + multi-buyer из W2 summary (волна 28).',
        good: [
          'Retailers core path',
          'Panel + context strip (`brand-co-retailers-panel`, волна 87)',
          'Фильтр заказов через `brandB2bOrdersRegistryHref({ partner })`',
          'CTA «Заказы» + «Витрина» (`brand-co-retailers-showroom-link-*`)',
          'Карточка (`brand-co-retailer-detail-panel`, context strip)',
          'PG tier badge (`retailer-tier-badge-*`, data-tier-source=pg, core-47)',
          'Tier из order.tier + volume (`/api/brand/retailers/b2b-orders-summary`)',
          'Multi-buyer discovery из PG orders (не только shop1 preset)',
        ],
        bad: ['Display names частично preset для shop1'],
        fix: ['Partner display names из PG CRM metadata'],
        resolveHref: () => ROUTES.brand.retailers,
      },
      {
        id: 'brand-co-chain',
        label: 'Этапы цепочки · заказ',
        order: 4,
        staticScore: 7.3,
        liveScore: 7.1,
        summary: 'shop_sent / brand_confirmed — мост к производству.',
        good: [
          'chain-status API',
          'CollectionOrderPillarCard steps (`brand-co-chain-hub-steps`)',
          'Карточка заказа: `brand-co-chain-card` + context strip (волна 85)',
          'Шаги shop_sent/brand_confirmed без production noise',
          'Два CTA: confirm-order → handoff (волна 95)',
          'SLA бейдж «Ожидает подтверждения»',
          'CTA передача после confirm (`collection-order-handoff-link`)',
          'SSE/poll (`brand-co-chain-sse-live-badge`)',
          'Системное сообщение в чат при checkout',
        ],
        bad: ['Полная цепочка — только по ссылке «Полная цепочка» / pillar'],
        fix: [],
        resolveHref: (d) => brandB2bOrderHref(d.demoOrderId),
      },
      {
        id: 'brand-co-cabinet',
        label: 'Кабинет · приём заказов',
        order: 5,
        staticScore: 7.0,
        liveScore: 7.2,
        summary: 'Pillar card + CTA на реестр/заказ + PG partner count (волна 28).',
        good: [
          'CollectionOrderPillarCard brand',
          'Panel + CTA groups (`brand-co-cabinet-panel`, `cta-orders`/`cta-peer`, волна 86)',
          'PG partner count badge (`brand-co-cabinet-partner-count`, core-47)',
          'Сводка qty и сумма заказа',
          'Handoff + SLA + hub steps',
          'e2e collection-order-qty-summary + retailers link',
        ],
        bad: ['Multi-buyer shop registry filter в hub'],
        fix: ['Shop peer picker при multi-buyer checkout'],
        resolveHref: (d) =>
          `${ROUTES.brand.coreCabinet}?pillar=collection_order&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
    order_production: [
      {
        id: 'brand-op-handoff',
        label: 'Передача в производство',
        order: 1,
        staticScore: 7.5,
        liveScore: 7.6,
        summary: 'confirm-order → handoff → ERP retry на clean PG (core-34 ✓).',
        good: [
          'Handoff API',
          'e2e core-02/03',
          'Retry UI (`brand-b2b-handoff-retry`) + error alert',
          'ERP retry UI (`brand-b2b-erp-retry`) + POST API',
          'core-34: clean PG ERP retry после handoff',
          'Кнопка gated на handedOff, не status (волна 55)',
          'Context strip cross-role (`brand-order-handoff-context-strip`)',
          'SSE/poll badge в chain card (`brand-op-chain-*`, волна 76)',
          'Strip CTA канон (`brand-op-handoff-factory-queue-link`, `brand-op-handoff-prod-orders-link`, волна 77)',
          'CTA «Передача» в реестре (`brand-b2b-order-handoff-*`)',
          'Bulk handoff (`brand-b2b-bulk-handoff`, `brand-b2b-order-select-*`)',
          'Deep link `brandB2bOrderHandoffContextHref` + awaiting registry',
          'Очередь цеха с order context (`brand-b2b-factory-queue-link`, волна 49)',
          'PO → queue link в реестре (`brand-b2b-order-po-link-*`, волна 55)',
        ],
        bad: ['Нет auto-retry ERP после bulk handoff'],
        fix: ['ERP auto-retry backoff после bulk handoff (P1)'],
        resolveHref: (d) => brandB2bOrderHandoffContextHref(d.demoOrderId),
      },
      {
        id: 'brand-op-chain',
        label: 'Статус цепочки · PO',
        order: 2,
        staticScore: 7.2,
        liveScore: 7.5,
        summary: '5 шагов chain-status, production PO id, ERP retry на карточке (core-34 ✓).',
        good: [
          'B2bOrderChainStatusCard (`brand-order-chain-status-card`)',
          'brand-op-chain-sse/poll badge (волна 76)',
          'brand-order-chain-context-strip + poll badge (волна 76)',
          'Cross-links чат/календарь/трекинг магазина',
          'OrderProductionPillarCard (`brand-op-chain-steps`)',
          'PO id badge + materials step badges',
          'ERP retry (`brand-b2b-erp-retry`, core-34)',
        ],
        bad: ['Дубль strip: chain card + order facts (осознанный)'],
        fix: ['Свести SSE badge к одному месту на карточке'],
        resolveHref: (d) => brandB2bOrderChainContextHref(d.demoOrderId),
      },
      {
        id: 'brand-op-dossier',
        label: 'Досье · W2 бренда',
        order: 3,
        staticScore: 7.0,
        liveScore: 7.1,
        summary:
          'Контекст ТЗ на карточке заказа + deep-link W2 material; factory dossier — peer read.',
        good: [
          'Карточка ТЗ на order detail (`brand-order-w2-dossier-card`, `#production-dossier`)',
          'Context strip handoff/chain/chat/factory (`brand-order-dossier-context-strip`)',
          'Канон href: `brandB2bOrderDossierContextHref`, `factoryProductionDossierHref`',
          'W2 deep-link material (`brandW2ProductionTzHref`, `brand-op-w2-dossier-link`)',
          'Pillar: `brand-op-order-dossier-link` → карточка заказа',
          'Peer досье цеха после handoff (`brand-order-factory-dossier-link`)',
          'Бейдж фиксации + diff (`brand-order-w2-dossier-locked-badge`, `*-diff-*`)',
          'b2bEditLock → tzWriteDisabled в W2 editor (волна 96)',
        ],
        bad: ['Дубль «Досье цеха» в context strip и CTA справа (осознанно: strip + primary CTA)'],
        fix: [],
        resolveHref: (d) => brandB2bOrderDossierContextHref(d.demoOrderId),
      },
      {
        id: 'brand-op-registry',
        label: 'Реестр · контекст заказов',
        order: 4,
        staticScore: 7.0,
        liveScore: 7.3,
        summary:
          'Реестр order_production: фильтры handoff/in_production, PO, chat section context (core-49).',
        good: [
          'ListChrome `?pillar=order_production`',
          'Фильтры + URL sync (`brand-op-registry-filter-*`, волна 78)',
          'Focus row `?order=` (`brand-op-registry-focus-row`, волна 78)',
          'Context strip трекинг/календарь/чат (`brand-registry-production-context-strip`)',
          'Clean PG production registry focus + handoff CTA (core-49)',
          'Registry chat → section auto-thread (`brand-op-registry-chat-link`, core-49)',
          'Колонка ПЗ → prod-orders (`brand-b2b-order-po-link-*`)',
          'HandedOff → chain context (`brandB2bOrderChainContextHref`)',
          'Bulk handoff + CSV export',
          '`brandB2bOrdersRegistryHref` — единый builder URL',
        ],
        bad: ['Дубль аудита с brand-co-registry (один экран)'],
        fix: ['Merge section scores в hub matrix (P2)'],
        resolveHref: () => brandB2bOrdersProductionRegistryHref(),
      },
      {
        id: 'brand-op-cabinet',
        label: 'Кабинет · заказ→производство',
        order: 5,
        staticScore: 7.0,
        liveScore: 7.3,
        summary: 'Hub insight: chain steps + BOM + peer CTA; clean PG PO badge (core-49).',
        good: [
          'Panel (`brand-op-cabinet-panel`, волна 82)',
          'CTA groups production/comms (`brand-op-cabinet-cta-*`, волна 82)',
          'SSE/poll badge (`brand-op-cabinet-*-badge`, волна 74)',
          'Registry с `?order=` · materials step link (волна 82)',
          'PO badge → prod-orders (`brand-op-po-id-badge`)',
          'Clean PG chain steps + order link (core-49)',
          'WMS/materials badges + BOM preview',
          'compact-only hub (волна 48)',
        ],
        bad: ['Дубль данных с order detail / registry'],
        fix: ['Свести BOM preview к одной строке в hub (P2)'],
        resolveHref: (d) => brandCoreOrderProductionCabinetHref(d.collectionId),
      },
    ],
    comms: [
      {
        id: 'brand-cm-order-chat',
        label: 'Чат · оптовый заказ',
        order: 1,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'Контекстный тред B2B — координация с магазином; SSE unread.',
        good: [
          'contextType b2b_order',
          'slim messages core',
          'Entity banner',
          'Чат из реестра заказов',
          'Превью треда в реестре',
          'Universal inbox: все заказы PG в sidebar',
          'B2B шаблоны (ship-window, qty-confirm) в slimCore',
          'core-14 e2e templates',
          'PG unread в ChatList + registry SSE bump (волна 15)',
          'comms-pillar-unread-badge на inbox (волна 68)',
          'brand-cm-order-context-strip (волна 68)',
          'brand-cm-order-chat-link в hub',
          'Server read receipts (PG workshop2_contextual_read_state)',
          'Read-state actor из session uid (волна 36)',
        ],
        bad: ['Нет пользовательских шаблонов'],
        fix: ['Сохранение своих шаблонов'],
        resolveHref: (d) => brandMessagesB2bOrderContextHref(d.demoOrderId),
      },
      {
        id: 'brand-cm-article-chat',
        label: 'Чат · артикул W2',
        order: 2,
        staticScore: 7.2,
        liveScore: 7.2,
        summary: 'Связь разработки с цехом/поставщиком по артикулу.',
        good: [
          'workshop2_article context',
          'brand-dossier-article-chat-link',
          'brand-cm-article-context-strip (волна 69)',
          'brand-cm-article-messages-link в W2 drawer',
          'Экспорт ТЗ рядом с чатом (`brand-w2-tz-export-btn`)',
          'Прикрепление ZIP ТЗ в тред (`brand-w2-tz-attach-chat-btn`)',
          'Ссылка на вложение в contextual chat (`contextual-chat-attachment-link`)',
        ],
        bad: ['Poll-only unread в W2 drawer (30s)'],
        fix: ['SSE unread bump в article workspace panel'],
        resolveHref: (d) =>
          brandMessagesWorkshop2ArticleContextHref(d.collectionId, d.demoArticleId),
      },
      {
        id: 'brand-cm-calendar',
        label: 'Календарь · заказ',
        order: 3,
        staticScore: 7.0,
        liveScore: 7.2,
        summary: 'Слоты отгрузки, события chain — investor «план поставок».',
        good: [
          'Calendar B2B context',
          'Canonical URLs',
          'targetChatId в calendar-events API',
          'EventDialog «Чат» при клике на B2B-событие',
          'brand-cm-calendar-context-strip + chain/tracking (волна 70)',
          'brand-cm-calendar-link в hub + events count',
          'brand-cm-calendar-events-badge',
        ],
        bad: ['Нет drag слотов'],
        fix: ['Создание слота → чат'],
        resolveHref: (d) => brandCalendarB2bOrderContextHref(d.demoOrderId),
      },
      {
        id: 'brand-cm-banner',
        label: 'Контекст-баннер · URL',
        order: 4,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'Dedupe баннеров при ?order= / ?chat=; SSE comms bump.',
        good: [
          'CommunicationsEntityContextBanner',
          'brand-cm-banner testid (волна 71)',
          'Core B2B msg/cal hrefs (не syntha overlay)',
          'Policy strip off при URL и workspace',
          'core-14 banner dedupe e2e (4 роли)',
          'core-13 cross-nav',
          'Production-context banner → W2 article chat + dossier (волна 95)',
          'Registry SSE refetch unread (волна 15)',
        ],
        bad: ['Article workspace unread poll-only'],
        fix: ['SSE unread bump в W2 drawer panel'],
        resolveHref: (d) => brandMessagesB2bOrderContextHref(d.demoOrderId),
      },
      {
        id: 'brand-cm-section-groups',
        label: 'Группы по разделам',
        order: 5,
        staticScore: 7.5,
        liveScore: 8.1,
        summary: 'Section-groups: clean PG four-role deep-link + PG read SoT (волна 22).',
        good: [
          'brand-cm-section-groups-picker UI',
          'Deep-link ?pillar=&section= (core-21 e2e)',
          'Clean PG B2B-\\d+ deep-link 4 roles (core-40)',
          'Section contextual auto-thread (core-30)',
          'Order detail / tracking chat → section deep-link (core-46)',
          'Registry SSE bump на contextual message (волна 15)',
          'comms-pillar-sse-live-badge на hub (core-35)',
          'Unread badge на section-group chip (волна 16)',
          'Section visit cursor local + POST section-read-state (волна 18–21)',
          'PG mirror в workshop2_contextual_read_state (b2b_order_section)',
          'PG-primary skip file mirror (волна 22)',
          'Audit guard comms-canon',
          'Исключение meta-section из picker',
        ],
        bad: ['Calendar tasks still memory-only when PG URL unset in dev'],
        fix: ['PG calendar task store prod (волна 23 migration 030)'],
        resolveHref: (d) =>
          `${ROUTES.brand.coreCabinet}?pillar=comms&collection=${encodeURIComponent(d.collectionId)}&section=brand-co-registry`,
      },
      {
        id: 'brand-cm-cabinet',
        label: 'Кабинет · связь',
        order: 6,
        staticScore: 7.2,
        liveScore: 7.4,
        summary: 'CommsPillarCard, PG unread + clean PG thread strip (core-40).',
        good: [
          'brand-cm-cabinet-po-inbox из реестра B2B (волна 73)',
          'CommsPillarCard compact-only (волна 47)',
          'comms-pillar-unread-badge + SSE live (core-35)',
          'Clean PG order chat link (core-20/40)',
          'brand-cm-cabinet-thread-search hub (волна 72)',
          'brand-cm-thread-search workspace (волна 72)',
          'brand-cm-order/article/calendar-link hub (волны 68–70)',
          'CTA «Все треды» + unread на inbox (волна 68)',
        ],
        bad: ['Poll fallback если SSE недоступен'],
        fix: ['Redis registry bump в prod SSE'],
        resolveHref: (d) =>
          `${ROUTES.brand.coreCabinet}?pillar=comms&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
};
