/**
 * @generated split from platform-core-readiness-sections.ts — do not edit monolith; edit role file.
 */
import type { CoreHubPillarId } from '@/lib/platform-core-hub-matrix';
import {
  brandLinesheetsHrefForDemo,
  brandShowroomHrefForDemo,
  factoryHandoffQueueHrefForDemo,
  factoryMaterialsHrefForDemo,
  factoryMaterialsProcurementHrefForDemo,
  platformCoreRolePillarHref,
  shopShowroomHrefForDemo,
} from '@/lib/platform-core-hub-matrix';
import {
  ROUTES,
  brandB2bOrderChainContextHref,
  brandB2bOrderDossierContextHref,
  brandB2bOrderHandoffContextHref,
  brandB2bOrderHref,
  brandB2bOrdersAwaitingHandoffRegistryHref,
  brandB2bOrdersProductionRegistryHref,
  brandCoreOrderProductionCabinetHref,
  brandCalendarB2bOrderContextHref,
  brandMessagesB2bOrderContextHref,
  brandMessagesWorkshop2ArticleContextHref,
  brandW2ProductionTzHref,
  factoryMessagesB2bOrderContextHref,
  factoryMessagesWorkshop2ArticleContextHref,
  factoryCoreOrderProductionCabinetHref,
  factorySupplierCoreOrderProductionCabinetHref,
  factoryProductionDossierContextHref,
  factoryProductionDossierHref,
  factoryProductionOrdersOrderContextHref,
  factorySupplierMessagesB2bOrderContextHref,
  factorySupplierMessagesWorkshop2ArticleContextHref,
  shopB2bOrderHref,
  shopB2bOrderProductionContextHref,
  shopB2bOrdersProductionRegistryHref,
  shopB2bTrackingOrderHref,
  shopCalendarB2bOrderContextHref,
  shopMessagesB2bOrderContextHref,
} from '@/lib/routes';
import { WORKSHOP2_COL_PARAM, workshop2ArticleHref } from '@/lib/production/workshop2-url';
import type { SectionAuditTemplate } from './types';

export const MANUFACTURER_SECTION_AUDIT: Partial<Record<CoreHubPillarId, readonly SectionAuditTemplate[]>> = {
    development: [
      {
        id: 'mfr-dev-dossier',
        label: 'Досье · read-only',
        order: 1,
        staticScore: 7.4,
        liveScore: 7.4,
        summary: 'ТЗ и BOM из PG — основа выпуска.',
        good: [
          'mfr-dev-dossier-panel + context strip (brand W2/queue/materials/cabinet)',
          'Export SKU strip',
          'PG dossier API read-only',
          'Article chat (`mfr-dev-dossier-article-chat-link`)',
        ],
        bad: ['Цех не редактирует состав', 'Нет e2e export meta'],
        fix: ['E2E export TZ', 'Comment-only annotations'],
        resolveHref: (d) =>
          factoryProductionDossierHref(d.demoArticleId, { collectionId: d.collectionId }),
      },
      {
        id: 'mfr-dev-sample-queue',
        label: 'Очередь образцов',
        order: 2,
        staticScore: 7.2,
        liveScore: 7.4,
        summary: 'Sample queue PG — один canonical entry в context strip (волна 21).',
        good: [
          'Sample queue card',
          'SAMPLE-DEMO в e2e',
          'Priority sort overdue→due',
          '#sample-queue hash-scroll (волна 94)',
          'pillarId development на карточке очереди',
          'Один CTA образцы/ack в mfr-dev-cabinet strip',
        ],
        bad: ['Factory dossier duplicate queue slot'],
        fix: ['Collapse dossier sample slot P2'],
        resolveHref: () => `${ROUTES.factory.production}#sample-queue`,
      },
      {
        id: 'mfr-dev-status',
        label: 'Статус коллекции · PG',
        order: 3,
        staticScore: 7.0,
        liveScore: 7.1,
        summary: 'development-status read — связь с бренд W2.',
        good: ['Read-only steps', 'Empty panels manufacturer sample_collection'],
        bad: ['Brand development на карточке шумит', 'Нет factory-scoped filter'],
        fix: ['Только factory articles', 'Скрыть brand-only steps'],
        resolveHref: (d) =>
          factoryProductionDossierHref(d.demoArticleId, { collectionId: d.collectionId }),
      },
      {
        id: 'mfr-dev-cabinet',
        label: 'Кабинет · досье/образцы',
        order: 4,
        staticScore: 7.1,
        liveScore: 7.3,
        summary: 'DevelopmentPillarCard manufacturer.',
        good: [
          'mfr-dev-cabinet-panel + context strip',
          'ТЗ бренда · досье · образцы',
          'e2e core-01 manufacturer development pillar',
        ],
        bad: ['Дубль nav'],
        fix: ['Compact nav'],
        resolveHref: (d) =>
          `${ROUTES.factory.productionCoreCabinet}?pillar=development&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
    order_production: [
      {
        id: 'mfr-op-handoff-queue',
        label: 'Очередь передачи',
        order: 1,
        staticScore: 7.3,
        liveScore: 7.6,
        summary: 'Входящие PO после бренда — shop-floor bundle + row chat section context (волна 29).',
        good: [
          'Handoff queue PG',
          'e2e core-02',
          'Golden CTA',
          'bulk-acknowledge API + panel (`mfr-op-handoff-queue-panel`)',
          'B2bChainPhaseBadge на строках очереди',
          'RU статусы PO (`factoryHandoffPoStatusLabelRu`, волна 77)',
          'Registry link + row CTA (`mfr-op-handoff-queue-registry-link`, `mfr-op-handoff-queue-orders-link-*`)',
          'Shop-floor bundle per PG row (`mfr-op-handoff-shop-floor-bundle-*`, core-42)',
          'Poll refresh registry tick + refresh button (волна 77)',
          'ERP alert banner (`mfr-op-handoff-queue-erp-alert`)',
          'Canonical handoff href с order context (волна 49)',
          'Row chat → section auto-thread (`mfr-op-handoff-queue-chat-link-*`, core-48)',
        ],
        bad: ['Дубль bulk-ack с реестром /orders — осознанный: panel=быстро, orders=MES/ERP'],
        fix: ['Navigate to registry после bulk ack (P1)'],
        resolveHref: (d) => factoryHandoffQueueHrefForDemo(d),
      },
      {
        id: 'mfr-op-production-orders',
        label: 'Производственные заказы',
        order: 2,
        staticScore: 7.2,
        liveScore: 7.4,
        summary: 'Реестр серий цеха; clean PG focus row (core-49).',
        good: [
          'production-orders core PG',
          'scroll-to-row + focus-row testid (волна 75)',
          'ERP alert banner + retry CTA (волна 75)',
          'hub link → factoryCoreOrderProductionCabinetHref',
          'Copy: panel=ack, registry=MES/ERP',
          'Bulk accept + MES strip + per-row CTA',
          'Context strip при ?order=',
          'e2e MES FW27 (`core-11`)',
          'Clean PG focus row (`factory-production-orders-focus-row`, core-49)',
        ],
        bad: ['Нет e2e MES на EMPTY27', 'Дубль bulk-ack с handoff panel на /production'],
        fix: ['EMPTY27 честный skip MES в core-06', 'Bulk ERP retry для всех attention rows'],
        resolveHref: (d) =>
          factoryProductionOrdersOrderContextHref(d.demoOrderId, { factoryId: d.factoryId }),
      },
      {
        id: 'mfr-op-dossier',
        label: 'Досье · техзадание',
        order: 3,
        staticScore: 7.2,
        liveScore: 7.7,
        summary: 'Read-only ТЗ + shop-floor bundle; interaction chat → section auto-thread (волна 29).',
        good: [
          'factory-dossier-core-chrome + `?pillar=order_production`',
          'Context strip prod-orders/queue/procurement (`mfr-op-dossier-context-strip`)',
          'Version badge из chain-status (`mfr-op-dossier-version-badge`)',
          'Печать ТЗ (`mfr-op-dossier-print-btn`)',
          'Shop-floor bundle download (`mfr-op-shop-floor-bundle-btn`, core-36)',
          'Handoff queue shop-floor link для B2B-\\d+ (core-42)',
          'Канон href: `factoryProductionDossierContextHref`',
          'Peer: shop tracking, order chat',
          'Order chat → section context (`mfr-op-dossier-order-chat-link`, core-48)',
        ],
        bad: ['Sample queue скрыт в production pillar'],
        fix: ['PDF bundle (сейчас plain-text)'],
        resolveHref: (d) =>
          factoryProductionDossierContextHref(d.demoArticleId, {
            collectionId: d.collectionId,
            orderId: d.demoOrderId,
          }),
      },
      {
        id: 'mfr-op-materials',
        label: 'Закупка · поставщик',
        order: 4,
        staticScore: 7.0,
        liveScore: 7.2,
        summary: 'Цех: BOM×PO read + chain; подтверждение — у поставщика (`role=supplier`).',
        good: [
          'manufacturer chrome + context strip (`mfr-op-materials-context-strip`)',
          'BOM×PO table (`materials-procurement-bom-table`)',
          'materials_supplied badge (`mfr-op-materials-supplied-badge`)',
          'Peer: prod-orders, dossier, shop tracking',
          'Разделение write: confirm только при role=supplier',
        ],
        bad: ['WMS reserve live push слабый', 'Один article per procurement view'],
        fix: ['SSE/poll badge materials_supplied', 'Multi-article wizard'],
        resolveHref: (d) => factoryMaterialsProcurementHrefForDemo(d),
      },
      {
        id: 'mfr-op-cabinet',
        label: 'Кабинет · выпуск',
        order: 5,
        staticScore: 7.2,
        liveScore: 7.4,
        summary:
          'Hub insight: filtered chain steps + queue snippet + peer CTA (parity brand/shop).',
        good: [
          'Panel (`mfr-op-cabinet-panel`, волна 82)',
          'CTA groups production/comms (волна 82)',
          'SSE/poll badge (`mfr-op-cabinet-*-badge`, волна 74)',
          'WMS badge канон (`mfr-op-cabinet-wms-reserve-badge`, волна 82)',
          'Queue snippet + materials step link (волна 82)',
          'compact-only hub (волна 48)',
        ],
        bad: ['Queue snippet max 3 (po-inbox в comms)'],
        fix: ['Inline expand queue в op-cabinet (P2)'],
        resolveHref: (d) => factoryCoreOrderProductionCabinetHref(d.collectionId),
      },
    ],
    comms: [
      {
        id: 'mfr-cm-order',
        label: 'Чат · заказ',
        order: 1,
        staticScore: 7.2,
        liveScore: 7.3,
        summary: 'Координация с брендом/магазином по PO.',
        good: [
          'factory messages slim',
          'e2e core-01',
          'Чат из очереди PO (`mfr-op-queue-chat-*`, волна 39)',
          'Чат из prod-orders (`factory-production-order-chat-*`)',
          'mfr-cm-order-context-strip (волна 68)',
          'mfr-cm-order-chat-link + supplier link в hub',
          'comms-pillar-inbox-all (manufacturer)',
        ],
        bad: ['Нет единого inbox по всем PO в списке производства', 'Нет attach TZ из досье'],
        fix: ['Inbox merge всех PO в sidebar', 'Attach from dossier'],
        resolveHref: (d) =>
          factoryMessagesB2bOrderContextHref(d.demoOrderId, { role: 'manufacturer' }),
      },
      {
        id: 'mfr-cm-article',
        label: 'Чат · артикул',
        order: 2,
        staticScore: 7.1,
        liveScore: 7.3,
        summary: 'Уточнения по ТЗ и образцам.',
        good: [
          'workshop2 article context',
          'factory-dossier-article-chat-link',
          'mfr-cm-article-context-strip (волна 69)',
          'mfr-cm-article-chat-link в hub',
          'Шаблоны article-tz / article-sample',
        ],
        bad: ['Нет e2e dedupe strict', 'Read-only: нет attach TZ (только бренд)'],
        fix: ['E2E dedupe assert', 'Reply template «уточнение состава»'],
        resolveHref: (d) =>
          factoryMessagesWorkshop2ArticleContextHref(d.collectionId, d.demoArticleId),
      },
      {
        id: 'mfr-cm-calendar',
        label: 'Календарь · производство',
        order: 3,
        staticScore: 7.3,
        liveScore: 7.8,
        summary: 'Этапы производства + user tasks + handoff queue PO + mfr auto-thread (волна 24–25).',
        good: [
          'role=manufacturer layers',
          'mfr-cm-calendar-context-strip (волна 70)',
          'mfr-cm-calendar-link + events count в hub',
          'href layers=tasks,orders,production (волна 46)',
          'User tasks merged в calendar-events API (волна 18)',
          'core-22 unified PO inbox',
          'Handoff queue PO в collection calendar (`b2b-po-queue-*`, core-43)',
          'Mfr calendar create task → auto-thread (core-44)',
        ],
        bad: ['Нет Gantt'],
        fix: ['Milestone Gantt view P2'],
        resolveHref: () =>
          `${ROUTES.factory.productionCalendar}?role=manufacturer&layers=tasks,orders,production`,
      },
      {
        id: 'mfr-cm-cabinet',
        label: 'Кабинет · связь',
        order: 4,
        staticScore: 7.4,
        liveScore: 7.5,
        summary: 'CommsPillarCard manufacturer, clean PG handoff section-group (core-40).',
        good: [
          'mfr-cm-cabinet-po-inbox из handoff queue (волна 73)',
          'Clean PG mfr-op-handoff-queue section-group (core-40)',
          'mfr-cm-cabinet-thread-search (волна 72)',
          'mfr-cm-thread-search workspace (волна 72)',
          'mfr-cm-banner canonical calendar (волна 71)',
          'mfr-cm-* hub links (волны 68–70)',
          'Ссылка на тред поставщика',
          'Очередь передачи в hub card',
        ],
        bad: ['Queue snippet max 3 в order_production hub'],
        fix: ['Сводка очереди в comms po-inbox'],
        resolveHref: (d) =>
          `${ROUTES.factory.productionCoreCabinet}?pillar=comms&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
};
