/**
 * @generated split from platform-core-readiness-sections.ts — do not edit monolith; edit role file.
 */
import type { CoreHubPillarId } from '@/lib/platform-core-hub-matrix';
import {
  brandLinesheetsHrefForDemo,
  brandShowroomHrefForDemo,
  factoryHandoffQueueHrefForDemo,
  factoryMaterialsHrefForDemo,
  factoryMaterialsProcurementHrefForDemo,
  platformCoreRolePillarHref,
  shopShowroomHrefForDemo,
} from '@/lib/platform-core-hub-matrix';
import {
  ROUTES,
  brandB2bOrderChainContextHref,
  brandB2bOrderDossierContextHref,
  brandB2bOrderHandoffContextHref,
  brandB2bOrderHref,
  brandB2bOrdersAwaitingHandoffRegistryHref,
  brandB2bOrdersProductionRegistryHref,
  brandCoreOrderProductionCabinetHref,
  brandCalendarB2bOrderContextHref,
  brandMessagesB2bOrderContextHref,
  brandMessagesWorkshop2ArticleContextHref,
  brandW2ProductionTzHref,
  factoryMessagesB2bOrderContextHref,
  factoryMessagesWorkshop2ArticleContextHref,
  factoryCoreOrderProductionCabinetHref,
  factorySupplierCoreOrderProductionCabinetHref,
  factoryProductionDossierContextHref,
  factoryProductionDossierHref,
  factoryProductionOrdersOrderContextHref,
  factorySupplierMessagesB2bOrderContextHref,
  factorySupplierMessagesWorkshop2ArticleContextHref,
  shopB2bOrderHref,
  shopB2bOrderProductionContextHref,
  shopB2bOrdersProductionRegistryHref,
  shopB2bTrackingOrderHref,
  shopCalendarB2bOrderContextHref,
  shopMessagesB2bOrderContextHref,
} from '@/lib/routes';
import { WORKSHOP2_COL_PARAM, workshop2ArticleHref } from '@/lib/production/workshop2-url';
import type { SectionAuditTemplate } from './types';

export const MANUFACTURER_SECTION_AUDIT: Partial<
  Record<CoreHubPillarId, readonly SectionAuditTemplate[]>
> = {
  development: [
    {
      id: 'mfr-dev-dossier',
      label: 'Досье · read-only',
      order: 1,
      staticScore: 7.4,
      liveScore: 8.5,
      summary: 'ТЗ и BOM из PG — основа выпуска.',
      good: [
        'mfr-dev-dossier-panel + context strip (brand W2/queue/materials/cabinet)',
        'Export SKU strip',
        'PG dossier API read-only',
        'Article chat (`mfr-dev-dossier-article-chat-link`)',
        'core-52 export SKU meta + print btn e2e',
        'Comment-only peer strip → chat template (`mfr-dev-dossier-comment-peer-strip`)',
        'Production spine + attach TZ (`mfr-dev-dossier-production-spine-peer-strip`, `mfr-cm-article-attach-tz-peer-strip`)',
      ],
      bad: ['Цех не редактирует состав'],
      fix: ['Comment-only annotations — peer strip ✓'],
      resolveHref: (d) =>
        factoryProductionDossierHref(d.demoArticleId, { collectionId: d.collectionId }),
    },
    {
      id: 'mfr-dev-sample-queue',
      label: 'Очередь образцов',
      order: 2,
      staticScore: 7.2,
      liveScore: 8.5,
      summary: 'Sample queue PG — один canonical entry в context strip.',
      good: [
        'Sample queue card',
        'SAMPLE-DEMO в e2e',
        'Priority sort overdue→due',
        '#sample-queue hash-scroll',
        'pillarId development на карточке очереди',
        'Один CTA образцы/ack в mfr-dev-cabinet strip',
        'Dossier peer strip → handoff sample-queue tab (`dossier-sample-queue-handoff-tab-link`)',
        'Handoff/orders/QC spine peer (`mfr-dev-sample-queue-handoff-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: () => `${ROUTES.factory.production}#sample-queue`,
    },
    {
      id: 'mfr-dev-status',
      label: 'Статус коллекции · PG',
      order: 3,
      staticScore: 7.0,
      liveScore: 8.0,
      summary: 'development-status read + factory-scoped filter strip.',
      good: [
        'Read-only steps',
        'Empty panels manufacturer sample_collection',
        'Factory scope strip (`mfr-dev-factory-scope-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        factoryProductionDossierHref(d.demoArticleId, { collectionId: d.collectionId }),
    },
    {
      id: 'mfr-dev-cabinet',
      label: 'Кабинет · досье/образцы',
      order: 4,
      staticScore: 7.1,
      liveScore: 8.0,
      summary: 'DevelopmentPillarCard manufacturer + factory scope peers.',
      good: [
        'mfr-dev-cabinet-panel + context strip',
        'ТЗ бренда · досье · образцы',
        'Factory scope strip on hub (`mfr-dev-factory-scope-strip`)',
        'e2e core-01 manufacturer development pillar',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.factory.productionCoreCabinet}?pillar=development&collection=${encodeURIComponent(d.collectionId)}`,
    },
  ],
  order_production: [
    {
      id: 'mfr-op-handoff-queue',
      label: 'Очередь передачи',
      order: 1,
      staticScore: 7.3,
      liveScore: 8.5,
      summary: 'Входящие PO после бренда — shop-floor bundle + row chat section context.',
      good: [
        'Handoff queue PG',
        'e2e core-02',
        'Golden CTA',
        'bulk-acknowledge API + panel (`mfr-op-handoff-queue-panel`)',
        'B2bChainPhaseBadge на строках очереди',
        'RU статусы PO (`factoryHandoffPoStatusLabelRu`)',
        'Registry link + row CTA (`mfr-op-handoff-queue-registry-link`, `mfr-op-handoff-queue-orders-link-*`)',
        'Shop-floor bundle per PG row (`mfr-op-handoff-shop-floor-bundle-*`, core-42)',
        'Poll refresh registry tick + refresh button',
        'ERP alert banner (`mfr-op-handoff-queue-erp-alert`)',
        'Canonical handoff href с order context',
        'Row chat → section auto-thread (`mfr-op-handoff-queue-chat-link-*`, core-48)',
        'Navigate to registry после bulk ack (`factory-handoff-bulk-acknowledge` → `/factory/production/orders?order=`, core-03)',
        'Bulk ERP retry для attention rows (`factory-handoff-bulk-erp-retry`, bulk-retry-erp API)',
        'core-55 clean PG factory ERP retry e2e (handoff + registry)',
        'Factory-ack tab (`manufacturer-handoff-feature-techpack-ack`) → POST handoff/factory-ack',
        'Handoff queue SSE + poll fallback (`mfr-op-handoff-queue-sse-*`)',
        'Golden path strip (`manufacturer-handoff-queue-golden-path-strip`)',
        'QC gate tab chain SSE/poll (`mfr-qc-gate-chain-*`) + brand QC peer link',
        'Registry SoT strip panel vs orders (`mfr-op-handoff-queue-registry-sot-strip`)',
        'CO spine peer brand/shop/prod-orders/techpack/cut-ticket (`mfr-op-handoff-queue-co-spine-peer-strip`)',
      ],
      bad: [
        'Дубль bulk-ack с реестром /orders — осознанный: panel=быстро, orders=MES/ERP; SoT strip поясняет',
      ],
      fix: [],
      resolveHref: (d) => factoryHandoffQueueHrefForDemo(d),
    },
    {
      id: 'mfr-op-production-orders',
      label: 'Производственные заказы',
      order: 2,
      staticScore: 7.2,
      liveScore: 8.5,
      summary: 'Реестр серий цеха; clean PG focus row (core-49).',
      good: [
        'production-orders core PG',
        'scroll-to-row + focus-row testid',
        'ERP alert banner + retry CTA',
        'hub link → factoryCoreOrderProductionCabinetHref',
        'Copy: panel=ack, registry=MES/ERP',
        'Bulk accept + MES strip + per-row CTA',
        'Context strip при ?order=',
        'e2e MES FW27 (`core-11`)',
        'Clean PG focus row (`factory-production-orders-focus-row`, core-49)',
        'core-06 EMPTY27 empty-state e2e (no MES SS27)',
        'EMPTY27 честный skip MES в core-06',
        'Bulk ERP retry alert (`factory-production-orders-bulk-erp-retry`, bulk-retry-erp API)',
        'core-55 clean PG ERP alert на focus row (`factory-production-orders-erp-alert`)',
        'Golden path strip orders→handoff→tracking (`manufacturer-production-ops-golden-path-strip`)',
        'Attach TZ strip на orders/wip/cut-ticket (`mfr-op-production-attach-tz-*`)',
        'Handoff/sample/QC spine peer (`mfr-op-production-orders-handoff-peer-strip`)',
      ],
      bad: ['Дубль bulk-ack с handoff panel на /production'],
      fix: [],
      resolveHref: (d) =>
        factoryProductionOrdersOrderContextHref(d.demoOrderId, { factoryId: d.factoryId }),
    },
    {
      id: 'mfr-op-dossier',
      label: 'Досье · техзадание',
      order: 3,
      staticScore: 7.2,
      liveScore: 8.0,
      summary: 'Read-only ТЗ + shop-floor bundle; interaction chat → section auto-thread.',
      good: [
        'factory-dossier-core-chrome + `?pillar=order_production`',
        'Context strip prod-orders/queue/procurement (`mfr-op-dossier-context-strip`)',
        'Version badge из chain-status (`mfr-op-dossier-version-badge`)',
        'Печать ТЗ (`mfr-op-dossier-print-btn`)',
        'Shop-floor bundle download (`mfr-op-shop-floor-bundle-btn`, core-36)',
        'Handoff queue shop-floor link для B2B-\\d+ (core-42)',
        'Канон href: `factoryProductionDossierContextHref`',
        'Peer: shop tracking, order chat',
        'Core dossier strip: golden path без inline чата',
        'export-tz-bundle ZIP + tz-handoff-summary.pdf (jsPDF)',
        'Sample queue visible from OP dossier (`mfr-op-dossier-sample-queue-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        factoryProductionDossierContextHref(d.demoArticleId, {
          collectionId: d.collectionId,
          orderId: d.demoOrderId,
        }),
    },
    {
      id: 'mfr-op-materials',
      label: 'Закупка · поставщик',
      order: 4,
      staticScore: 7.0,
      liveScore: 8.0,
      summary: 'BOM×PO + handoff/tracking peer strip на procurement.',
      good: [
        'manufacturer chrome + context strip (`mfr-op-materials-context-strip`)',
        'BOM×PO peer strip (`mfr-op-materials-bom-po-peer-strip`)',
        'BOM×PO table (`materials-procurement-bom-table`)',
        'materials_supplied badge (`mfr-op-materials-supplied-badge`)',
        'SSE/poll chain-status на procurement (`mfr-op-materials-*`, `PlatformCoreChainStatusRefreshBadge`)',
        'Multi-article nav (`mfr-op-procurement-article-wizard`)',
        'Peer: prod-orders, dossier, shop tracking',
        'Разделение write: confirm только при role=supplier',
        'WMS reserve strip на procurement (`mfr-op-materials-wms-reserve-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => factoryMaterialsProcurementHrefForDemo(d),
    },
    {
      id: 'mfr-op-cabinet',
      label: 'Кабинет · выпуск',
      order: 5,
      staticScore: 7.2,
      liveScore: 8.5,
      summary:
        'Hub insight: filtered chain steps + queue snippet + unified PO inbox peer in comms.',
      good: [
        'Panel (`mfr-op-cabinet-panel`)',
        'CTA groups production/comms',
        'SSE/poll badge (`mfr-op-cabinet-*-badge`)',
        'WMS badge compact + SSE (`mfr-op-cabinet-wms-reserve-badge`, data-reserve-sse-live)',
        'Queue snippet + materials step link',
        'Unified PO inbox in comms pillar (`mfr-cm-unified-po-inbox-strip`)',
        'compact-only hub',
        'Cabinet spine peer handoff/brand/tracking/cut-ticket/materials/comms (`mfr-op-cabinet-spine-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => factoryCoreOrderProductionCabinetHref(d.collectionId),
    },
  ],
  comms: [
    {
      id: 'mfr-cm-order',
      label: 'Чат · заказ',
      order: 1,
      staticScore: 7.2,
      liveScore: 8.5,
      summary: 'Координация с брендом/магазином по PO; unified inbox strip.',
      good: [
        'factory messages slim',
        'e2e core-01',
        'Чат из очереди PO (`mfr-op-queue-chat-*`)',
        'Чат из prod-orders (`factory-production-order-chat-*`)',
        'mfr-cm-order-context-strip',
        'Order context peer handoff/QC/brand/tracking/cut-ticket (`mfr-cm-order-handoff-link`, `mfr-cm-order-entities-link`)',
        'mfr-cm-order-chat-link + supplier link в hub',
        'comms-pillar-inbox-all (manufacturer)',
        'core-14 factory messages dedupe e2e',
        'Golden path strip inbox→handoff→tracking (`manufacturer-comms-workspace-golden-path-strip`)',
        'Attach TZ из production ops (`mfr-op-production-attach-tz-strip`, entities tab)',
        'Unified PO inbox strip (`mfr-cm-unified-po-inbox-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        factoryMessagesB2bOrderContextHref(d.demoOrderId, { role: 'manufacturer' }),
    },
    {
      id: 'mfr-cm-article',
      label: 'Чат · артикул',
      order: 2,
      staticScore: 7.1,
      liveScore: 8.0,
      summary: 'Уточнения по ТЗ и образцам; attach TZ peer + brand W2 read-only.',
      good: [
        'workshop2 article context',
        'factory-dossier-article-chat-link',
        'mfr-cm-article-context-strip',
        'mfr-cm-article-chat-link в hub',
        'Шаблоны article-tz / article-sample',
        'core-14 article+order dedupe e2e',
        'Attach TZ peer strip (`mfr-cm-article-attach-tz-peer-strip`, `mfr-cm-article-brand-w2-peer-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        factoryMessagesWorkshop2ArticleContextHref(d.collectionId, d.demoArticleId),
    },
    {
      id: 'mfr-cm-calendar',
      label: 'Календарь · производство',
      order: 3,
      staticScore: 7.3,
      liveScore: 8.2,
      summary: 'Этапы производства + user tasks + handoff queue PO + mfr auto-thread.',
      good: [
        'role=manufacturer layers',
        'mfr-cm-calendar-context-strip',
        'mfr-cm-calendar-link + events count в hub',
        'href layers=tasks,orders,production',
        'User tasks merged в calendar-events API',
        'GET user-task strip (`mfr-cm-calendar-user-tasks-strip`)',
        'Gantt bridge (`mfr-cm-calendar-gantt-link`) → brand production Gantt',
        'core-22 unified PO inbox',
        'Handoff queue PO в collection calendar (`b2b-po-queue-*`, core-43)',
        'Mfr calendar create task → auto-thread (core-44)',
      ],
      bad: [],
      fix: [],
      resolveHref: () =>
        `${ROUTES.factory.productionCalendar}?role=manufacturer&layers=tasks,orders,production`,
    },
    {
      id: 'mfr-cm-cabinet',
      label: 'Кабинет · связь',
      order: 4,
      staticScore: 7.4,
      liveScore: 8.0,
      summary: 'CommsPillarCard manufacturer, unified PO inbox + handoff queue.',
      good: [
        'mfr-cm-cabinet-po-inbox из handoff queue',
        'Unified PO inbox strip (`mfr-cm-unified-po-inbox-strip`, all PO link)',
        'Clean PG mfr-op-handoff-queue section-group (core-40)',
        'mfr-cm-cabinet-thread-search',
        'mfr-cm-thread-search workspace',
        'mfr-cm-banner canonical calendar',
        'mfr-cm-* hub links (волны 68–70)',
        'Ссылка на тред поставщика',
        'Очередь передачи в hub card',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.factory.productionCoreCabinet}?pillar=comms&collection=${encodeURIComponent(d.collectionId)}`,
    },
  ],
};
