/**
 * @generated split from platform-core-readiness-sections.ts — do not edit monolith; edit role file.
 */
import type { CoreHubPillarId } from '@/lib/platform-core-hub-matrix';
import {
  brandLinesheetsHrefForDemo,
  brandShowroomHrefForDemo,
  factoryHandoffQueueHrefForDemo,
  factoryMaterialsHrefForDemo,
  factoryMaterialsProcurementHrefForDemo,
  platformCoreRolePillarHref,
  shopShowroomHrefForDemo,
} from '@/lib/platform-core-hub-matrix';
import {
  ROUTES,
  brandB2bOrderChainContextHref,
  brandB2bOrderDossierContextHref,
  brandB2bOrderHandoffContextHref,
  brandB2bOrderHref,
  brandB2bOrdersAwaitingHandoffRegistryHref,
  brandB2bOrdersProductionRegistryHref,
  brandCoreOrderProductionCabinetHref,
  brandCalendarB2bOrderContextHref,
  brandMessagesB2bOrderContextHref,
  brandMessagesWorkshop2ArticleContextHref,
  brandW2ProductionTzHref,
  factoryMessagesB2bOrderContextHref,
  factoryMessagesWorkshop2ArticleContextHref,
  factoryCoreOrderProductionCabinetHref,
  factorySupplierCoreOrderProductionCabinetHref,
  factoryProductionDossierContextHref,
  factoryProductionDossierHref,
  factoryProductionOrdersOrderContextHref,
  factorySupplierMessagesB2bOrderContextHref,
  factorySupplierMessagesWorkshop2ArticleContextHref,
  shopB2bOrderHref,
  shopB2bOrderProductionContextHref,
  shopB2bOrdersProductionRegistryHref,
  shopB2bTrackingOrderHref,
  shopCalendarB2bOrderContextHref,
  shopMessagesB2bOrderContextHref,
} from '@/lib/routes';
import { WORKSHOP2_COL_PARAM, workshop2ArticleHref } from '@/lib/production/workshop2-url';
import type { SectionAuditTemplate } from './types';

export const SHOP_SECTION_AUDIT: Partial<Record<CoreHubPillarId, readonly SectionAuditTemplate[]>> = {
    sample_collection: [
      {
        id: 'shop-sc-showroom',
        label: 'Витрина коллекции',
        order: 1,
        staticScore: 7.4,
        liveScore: 7.5,
        summary: 'Published-articles + empty onboarding → partners/matrix (волна 20).',
        good: [
          'PG articles',
          'Shop empty onboarding (`shop-sc-showroom-empty-onboarding`, core-38)',
          'core-06 hero e2e',
          'Чат по артикулу (`shop-sc-showroom-article-chat-link-*`)',
          'Context strip matrix/checkout/registry/partners',
          'Orders CTA → collection registry (`shopB2bOrdersCollectionRegistryHref`)',
          'Footer matrix + checkout CTA',
        ],
        bad: ['Cover hero vs partner PG'],
        fix: ['E2E partner badge на showroom card'],
        resolveHref: (d) => shopShowroomHrefForDemo(d),
      },
      {
        id: 'shop-sc-partners',
        label: 'Каталог партнёров',
        order: 2,
        staticScore: 7.1,
        liveScore: 7.3,
        summary: 'Партнёрства PG — масштаб сети брендов.',
        good: [
          'partnerships API',
          'Discover core guard',
          'Бейджи коллекций на карточке партнёра',
          'Context strip showroom/matrix/checkout/registry',
          'CTA витрина/матрица per brand (`shop-sc-partners-showroom-*`)',
          'e2e partners collections + showroom/matrix',
          'Profile бренды каталога + invite CTA (`shop-sc-partners-invite-*`)',
        ],
        bad: ['Не все партнёры с live коллекциями в PG'],
        fix: ['PG onboarding для profile→connected', 'UAT partners→showroom golden path'],
        resolveHref: () => ROUTES.shop.b2bPartnersDiscover,
      },
      {
        id: 'shop-sc-matrix-entry',
        label: 'Переход · матрица',
        order: 3,
        staticScore: 7.3,
        liveScore: 7.3,
        summary: 'Витрина → матрица — вертикаль столпа.',
        good: [
          'CTA матрица на showroom (`shop-sc-matrix-entry-link-*`)',
          'Entry panel + strip при `?article=` (`shop-sc-matrix-entry-*`)',
          'MOQ + cart qty на витрине',
          'Quick add + deep link `?article=`',
          'Scroll к артикулу в CoreWholesaleMatrix',
          'Back link витрина + checkout из entry strip',
        ],
        bad: ['Нет inline qty edit на карточке витрины'],
        fix: ['Inline size picker на витрине P2', 'UAT showroom quick-add → matrix scroll'],
        resolveHref: (d) =>
          `${ROUTES.shop.b2bMatrix}?collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-sc-cabinet',
        label: 'Кабинет · витрина',
        order: 4,
        staticScore: 7.1,
        liveScore: 7.3,
        summary: 'ShopShowroomMini, partner logo, published count.',
        good: [
          'shop-sc-cabinet-panel + context strip (showroom/matrix/partners/registry/checkout)',
          'Partner logo PG + hero strip',
          'Empty state при 0 published',
          'e2e EMPTY27 + core-02 partner row',
        ],
        bad: ['Дубль mini vs полная страница'],
        fix: ['Синхрон counts mini/page', 'UAT cabinet → showroom golden path'],
        resolveHref: (d) =>
          `${ROUTES.shop.coreCabinet}?pillar=sample_collection&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
    collection_order: [
      {
        id: 'shop-co-matrix',
        label: 'Матрица оптового заказа',
        order: 1,
        staticScore: 7.6,
        liveScore: 7.5,
        summary: 'CoreWholesaleMatrix, W2 PG цены — core golden path (e2e волна 99).',
        good: [
          'PG matrix rows',
          'Panel + context strip (`shop-co-matrix-panel`, волна 85)',
          'Канон testids `shop-co-matrix-*` + legacy',
          'e2e matrix→checkout→новый B2B order (волна 99)',
          'Cart session file-store при HMR (волна 99)',
          'Без JOOR/NuOrder на core',
        ],
        bad: ['Зависимость от seed', 'Нет multi-collection matrix'],
        fix: ['E2E без seed', 'Сводная матрица сезона'],
        resolveHref: (d) =>
          `${ROUTES.shop.b2bMatrix}?collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-co-checkout',
        label: 'Checkout · отправка бренду',
        order: 2,
        staticScore: 7.5,
        liveScore: 7.5,
        summary: 'Синхронизация в PG B2B order — monetization moment (CELL 7.6).',
        good: [
          'POST create order',
          'resolveHref → `/shop/b2b/checkout` (не matrix)',
          'Panel + context strip (`shop-co-checkout-panel`, волна 86)',
          'Buyer label + канон testids `shop-co-checkout-*`',
          'Честный бейдж резерва',
          'Статус submitted + системное сообщение в чат заказа при checkout',
          'Multi-tenant buyer (`shop-b2b-buyer-switcher`, cookie `shop_b2b_buyer_id`)',
          'Buyer из `activeOrganizationId` + `x-w2-organization-id` (org→shop1/shop2 map)',
          'Org приоритетнее cookie при onboarding (волна 35)',
          'Расширенный org map: shop1/shop2, org-shop-002, retail_spb_*',
          'Session uid → buyer (`shop-001`/`shop-002`, волна 38)',
        ],
        bad: ['Резерв фейк на checkout (до handoff)'],
        fix: ['Production JWT middleware на API (сейчас uid + header)'],
        resolveHref: (d) =>
          `${ROUTES.shop.b2bCheckout}?collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-co-registry',
        label: 'Реестр оптовых заказов',
        order: 3,
        staticScore: 7.3,
        liveScore: 7.4,
        summary: 'Список PG заказов, guards legacy.',
        good: [
          'orders-core',
          'B2bChainPhaseBadge',
          'withShopB2bCoreLegacyGuard',
          'Экспорт CSV (`shop-co-registry-export-csv`)',
          'Context strip столп 3 (`shop-co-registry-context-strip`: matrix/showroom/tracking)',
          'Канон panel/focus (`shop-co-registry-panel`, `shop-co-registry-focus-row`)',
          'Превью треда (`shop-b2b-order-chat-preview-*`)',
          'SSE registry refetch при checkout/submit',
          'Onboarding empty (`shop-co-registry-empty-onboarding`, волна 83)',
        ],
        bad: [
          'Новый buyer без заказов — только onboarding CTA (не CRM depth)',
          'Дубль аудита с shop-op-registry',
        ],
        fix: ['CRM/invite flow для новых партнёров'],
        resolveHref: () => ROUTES.shop.b2bOrders,
      },
      {
        id: 'shop-co-detail',
        label: 'Карточка заказа',
        order: 4,
        staticScore: 7.3,
        liveScore: 7.4,
        summary: 'Факты PG, этапы, без dead-link на handoff бренда.',
        good: [
          'shop-order-detail-core',
          'Трекинг link на PO card',
          'Panel + context strip (`shop-co-detail-panel`, `shop-co-detail-context-strip`)',
          'Cross-links столп 3 (`shop-co-detail-cross-links`)',
          'Amend card до handoff (`shop-co-detail-amend-card`) + повтор в матрице',
          'Structured amend API (`shop-b2b-amend-request-submit`, волна 98)',
          'PO/ETA strips только в `?pillar=order_production` (волна 84)',
        ],
        bad: ['Дубль аудита с shop-op-order-status'],
        fix: [],
        resolveHref: (d) => shopB2bOrderHref(d.demoOrderId),
      },
      {
        id: 'shop-co-buyer-tracking',
        label: 'Трекинг покупателя · PO',
        order: 5,
        staticScore: 7.8,
        liveScore: 8.1,
        summary: 'Canonical buyer path — visibility policy в chain-status-batch buyerView (волна 25).',
        good: [
          'shopB2bTrackingOrderHref / #shop-co-buyer-tracking',
          'ShopProductionVisibility none/milestones/full (core-16 e2e)',
          'Brand disclosure preview strip (core-21/29/44)',
          'core-19 clean PG buyer-tracking после handoff',
          'core-44: brand disclosure link → tracking chain steps на B2B-\\d+',
          'chain-status-batch buyerView + PG order testids (волна 25)',
          'Tracking chat link ?pillar&section=shop-co-buyer-tracking (core-46)',
          'Legacy ?pillar=order_production redirect',
          'Materials/PO strips по visibility policy',
          'e2e core-01/06: shop-co primary testids (волна 26)',
          'SSE chain status на tracking panel',
        ],
        bad: ['Acknowledge delivery batch отсутствует'],
        fix: ['Batch acknowledge delivery (P1)'],
        resolveHref: (d) => shopB2bTrackingOrderHref(d.demoOrderId),
      },
      {
        id: 'shop-co-cabinet',
        label: 'Кабинет · формирование заказа',
        order: 6,
        staticScore: 7.4,
        liveScore: 7.4,
        summary: 'CollectionOrderPillarCard со steps shop_sent/brand_confirmed.',
        good: [
          'Pillar card steps',
          'Panel + CTA groups (`shop-co-cabinet-panel`, волна 86)',
          'Checkout из hub (`shop-co-cabinet-checkout-link`)',
          'Amend CTA (`shop-co-cabinet-amend-link`) до confirm бренда',
          'Трекинг read (`shop-co-cabinet-tracking-link`)',
          'Cart qty badge (`shop-collection-order-cart-qty-badge`)',
        ],
        bad: ['Amend hub link только до brand_confirmed'],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.coreCabinet}?pillar=collection_order&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
    order_production: [
      {
        id: 'shop-op-tracking',
        label: 'Трекинг цепочки',
        order: 1,
        staticScore: 7.2,
        liveScore: 7.4,
        summary: 'Read-only 5 шагов + live WMS reserve badge при PG WMS.',
        good: [
          '5 steps + materials done/pending badges (волна 81)',
          'Канон testids `shop-co-tracking-*` (legacy shop-op-* audit-only, core-45)',
          'shop-co-tracking-sse/poll badge',
          'e2e core-01/06: shop-co primary testids (helper, волна 26)',
          'Reserve badge честный + WMS e2e',
          'Выпуск + registry с `?order=` в strip/rows (волна 81)',
          'B2bChainPhaseBadge + CSV export',
          'Tracking→calendar/chat/production CTA',
          'platform-core-chain-step-* на шагах',
        ],
        bad: ['Нет acknowledge delivery batch'],
        fix: ['Acknowledge delivery batch (P1)'],
        resolveHref: (d) => shopB2bTrackingOrderHref(d.demoOrderId),
      },
      {
        id: 'shop-op-order-status',
        label: 'Карточка · статус PO',
        order: 2,
        staticScore: 7.2,
        liveScore: 7.3,
        summary: 'PO id, этапы, ссылка на трекинг (не handoff бренда).',
        good: [
          'platform-core-shop-chain-steps',
          'SSE/poll badge (`shop-op-order-status-*-badge`, волна 79)',
          'materials_supplied badge + step link (волна 79)',
          'Context strip канон (`shop-op-order-status-context-strip`)',
          'Registry → `shopB2bOrdersProductionRegistryHref(orderId)`',
          'Hash `#order-production` + scroll (волна 79)',
          'Cross-links чат/трекинг/календарь/реестр',
        ],
        bad: ['Read-only only (корректно)', 'Дубль аудита с shop-co-detail'],
        fix: ['Acknowledge delivery batch (P1)', 'Push notification при materials (P2)'],
        resolveHref: (d) => shopB2bOrderProductionContextHref(d.demoOrderId),
      },
      {
        id: 'shop-op-registry',
        label: 'Реестр · контекст',
        order: 3,
        staticScore: 7.3,
        liveScore: 7.3,
        summary: 'Навигация между заказами в производстве.',
        good: [
          'Chain batch API + B2bChainPhaseBadge',
          'Колонка ПЗ → tracking link',
          'Фильтр + URL sync (`shop-op-registry-filter-in-production`, волна 78)',
          'Focus row `?order=` (`shop-op-registry-focus-row`, волна 78)',
          'pillar=order_production + context strip (волна 53)',
          'PO/трекинг/выпуск на строке без дубля «Карточка»',
          'CSV export + error retry',
          'Filter-empty CTA (волна 53)',
          '`shopB2bOrdersRegistryHref` — единый builder URL',
        ],
        bad: ['Нет batch acknowledge', 'Один URL с shop-co-registry'],
        fix: ['Acknowledge delivery batch (P1)'],
        resolveHref: () => shopB2bOrdersProductionRegistryHref(),
      },
      {
        id: 'shop-op-cabinet',
        label: 'Кабинет · после отправки',
        order: 4,
        staticScore: 7.2,
        liveScore: 7.3,
        summary: 'OrderProductionPillarCard shop variant.',
        good: [
          'Panel (`shop-op-cabinet-panel`, волна 82)',
          'CTA groups + канон tracking/calendar links (волна 82)',
          'PO badge → tracking (`shop-op-cabinet-po-badge`)',
          'Registry с `?order=` (волна 82)',
          'SSE/poll badge (`shop-op-cabinet-*-badge`, волна 74)',
          'compact-only hub (волна 48)',
        ],
        bad: ['Read-only — ETA на карточке заказа, не в hub'],
        fix: ['Acknowledge delivery batch (P1)'],
        resolveHref: (d) =>
          `${ROUTES.shop.coreCabinet}?pillar=order_production&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
    comms: [
      {
        id: 'shop-cm-order-chat',
        label: 'Чат · заказ',
        order: 1,
        staticScore: 7.4,
        liveScore: 7.3,
        summary: 'Связь с брендом по B2B заказу.',
        good: [
          'threads API',
          'contextual chat= URL',
          'Чат из реестра заказов',
          'placeholder тред',
          'Превью треда в реестре',
          'Universal inbox: все заказы PG в sidebar',
          'B2B шаблоны в slimCore',
          'Article-chat витрина/матрица (`shop-showroom-article-chat-link-*`, `shop-b2b-matrix-article-chat-*`)',
          'shopMessagesWorkshop2ArticleContextHref',
          'PG unread + registry SSE bump в shop messages',
          'shop-cm-order-context-strip (волна 68)',
          'shop-cm-order-chat-link в hub',
          'Server read receipts (shop-buyer actor)',
        ],
        bad: ['Notification center отсутствует'],
        fix: ['EventDialog preview в hub'],
        resolveHref: (d) => shopMessagesB2bOrderContextHref(d.demoOrderId),
      },
      {
        id: 'shop-cm-calendar-order',
        label: 'Календарь · заказ',
        order: 2,
        staticScore: 7.1,
        liveScore: 7.4,
        summary: 'Окна отгрузки, клик → чат.',
        good: [
          'externalEventsOnly → chat',
          'shop-cm-calendar-context-strip всегда с order links (волна 70)',
          'shop-cm-calendar-link в hub',
          'href layers=orders,logistics в core (волна 46)',
        ],
        bad: ['Нет preview треда (fast-nav shop, в отличие от brand EventDialog)'],
        fix: ['Opt-in EventDialog preview без ломания golden'],
        resolveHref: (d) => shopCalendarB2bOrderContextHref(d.demoOrderId),
      },
      {
        id: 'shop-cm-calendar-logistics',
        label: 'Календарь · закупки',
        order: 3,
        staticScore: 7.0,
        liveScore: 7.4,
        scoreAliasOf: 'shop-cm-calendar-order',
        summary: 'Слой logistics на том же экране — окна поставки и materials_supplied.',
        good: [
          'layers=orders,logistics',
          'shop-cm-calendar-logistics-badge',
          'materials_supplied → b2b-materials-* event',
          'Единый strip с order+logistics (волна 70)',
        ],
        bad: ['Дубль audit-раздела: слой logistics на том же экране что order'],
        fix: ['Объединить scoring с shop-cm-calendar-order или popover thread'],
        resolveHref: () => `${ROUTES.shop.b2bCalendar}?layers=orders,logistics`,
      },
      {
        id: 'shop-cm-cabinet',
        label: 'Кабинет · связь',
        order: 4,
        staticScore: 7.2,
        liveScore: 7.4,
        summary: 'CommsPillarCard shop, clean PG section-groups (core-40).',
        good: [
          'shop-cm-cabinet-po-inbox из buyer registry (волна 73)',
          'CommsPillarCard',
          'Clean PG buyer-tracking section-group (core-40)',
          'shop-cm-cabinet-thread-search (волна 72)',
          'shop-cm-thread-search workspace (волна 72)',
          'shop-cm-banner dedupe (волна 71)',
          'shop-cm-* hub links (волны 68–70)',
        ],
        bad: ['Нет notifications center'],
        fix: ['Notification prefs'],
        resolveHref: (d) =>
          `${ROUTES.shop.coreCabinet}?pillar=comms&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
};
