/**
 * @generated split from platform-core-readiness-sections.ts — do not edit monolith; edit role file.
 */
import type { CoreHubPillarId } from '@/lib/platform-core-hub-matrix';
import {
  brandLinesheetsHrefForDemo,
  brandShowroomHrefForDemo,
  factoryHandoffQueueHrefForDemo,
  factoryMaterialsHrefForDemo,
  factoryMaterialsProcurementHrefForDemo,
  platformCoreRolePillarHref,
  shopShowroomHrefForDemo,
} from '@/lib/platform-core-hub-matrix';
import {
  ROUTES,
  brandB2bOrderChainContextHref,
  brandB2bOrderDossierContextHref,
  brandB2bOrderHandoffContextHref,
  brandB2bOrderHref,
  brandB2bOrdersAwaitingHandoffRegistryHref,
  brandB2bOrdersProductionRegistryHref,
  brandCoreOrderProductionCabinetHref,
  brandCalendarB2bOrderContextHref,
  brandMessagesB2bOrderContextHref,
  brandMessagesWorkshop2ArticleContextHref,
  brandW2ProductionTzHref,
  factoryMessagesB2bOrderContextHref,
  factoryMessagesWorkshop2ArticleContextHref,
  factoryCoreOrderProductionCabinetHref,
  factorySupplierCoreOrderProductionCabinetHref,
  factoryProductionDossierContextHref,
  factoryProductionDossierHref,
  factoryProductionOrdersOrderContextHref,
  factorySupplierMessagesB2bOrderContextHref,
  factorySupplierMessagesWorkshop2ArticleContextHref,
  shopB2bOrderHref,
  shopB2bOrderProductionContextHref,
  shopB2bOrdersProductionRegistryHref,
  shopB2bTrackingOrderHref,
  shopCalendarB2bOrderContextHref,
  shopMessagesB2bOrderContextHref,
} from '@/lib/routes';
import { PILLAR_CAPABILITY_FEATURE_PARAM } from '@/lib/platform/pillar-capability-workspaces';
import { WORKSHOP2_COL_PARAM, workshop2ArticleHref } from '@/lib/production/workshop2-url';
import type { SectionAuditTemplate } from './types';

export const SHOP_SECTION_AUDIT: Partial<Record<CoreHubPillarId, readonly SectionAuditTemplate[]>> =
  {
    sample_collection: [
      {
        id: 'shop-sc-showroom',
        label: 'Витрина коллекции',
        order: 1,
        staticScore: 7.4,
        liveScore: 8.5,
        summary: 'Published-articles + empty onboarding → partners/matrix.',
        good: [
          'PG articles',
          'Shop empty onboarding (`shop-sc-showroom-empty-onboarding`, core-38)',
          'core-06 hero e2e',
          'Чат по артикулу (`shop-sc-showroom-article-chat-link-*`)',
          'Context strip matrix/checkout/registry/partners',
          'Orders CTA → collection registry (`shopB2bOrdersCollectionRegistryHref`)',
          'Footer matrix + checkout CTA',
          'core-06 SS27 hero + partners-link e2e',
          'core-52 eligible badge + matrix CTA on article card',
          'Cross-role audit path (shop showroom context strip)',
          '3D stream tab (`shop-showroom-feature-3d-stream`, `b2b-3d-stream-panel`)',
          'Cover hero dossier-first (`shop-showroom-cover-hero`)',
          'Inline size + qty (`shop-sc-showroom-inline-size-*`, `shop-sc-showroom-inline-qty-*`)',
          'Golden path strip B2B spine (`shop-showroom-buy-golden-path-strip`)',
          'Monetization peer strip linesheet/partners/replenishment (`shop-sc-showroom-monetization-peer-strip`)',
          'B2B peer strip platform/marketroom/partners/checkout (`shop-sc-showroom-b2b-peer-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) => shopShowroomHrefForDemo(d),
      },
      {
        id: 'shop-sc-partners',
        label: 'Каталог партнёров',
        order: 2,
        staticScore: 7.1,
        liveScore: 8.5,
        summary: 'Партнёрства PG — масштаб сети брендов.',
        good: [
          'partnerships API',
          'Discover core guard',
          'Бейджи коллекций на карточке партнёра',
          'Golden path strip (`shop-sc-cabinet-golden-path`) — без дубля context strip',
          'Shop partners workspace golden path (`shop-b2b-partners-golden-path-strip`)',
          'CTA витрина/матрица per connected brand',
          'e2e partners collections + showroom/matrix',
          'Profile: invite panel + чат (`shop-sc-partners-invite-*`)',
          'Бейдж PG на connected row (`shop-sc-partners-source-pg-*`)',
          'Live PG collections на profile (`shop-sc-partners-live-pg-collection-*`)',
          'Greenfield buyer: profile rows без empty API (`shop-sc-partners-panel`)',
          'B2B peer strip platform/marketroom/matrix/checkout (`shop-sc-partners-b2b-peer-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: () => ROUTES.shop.b2bPartnersDiscover,
      },
      {
        id: 'shop-sc-matrix-entry',
        label: 'Переход · матрица',
        order: 3,
        staticScore: 7.3,
        liveScore: 8.5,
        summary: 'Витрина → матрица — вертикаль столпа.',
        good: [
          'CTA матрица на showroom (`shop-sc-matrix-entry-link-*`)',
          'Quick-add → matrix scroll (`shop-sc-showroom-matrix-quick-add-*`, core-52)',
          'Entry panel + strip при `?article=` (`shop-sc-matrix-entry-*`)',
          'MOQ + cart qty на витрине',
          'Quick add + deep link `?article=`',
          'Scroll к артикулу в CoreWholesaleMatrix',
          'Back link витрина + checkout из entry strip',
          'Inline size + qty (`shop-sc-showroom-inline-size-*`, `shop-sc-showroom-inline-qty-*`)',
          'Published badge + tracking on entry strip (`shop-sc-matrix-entry-published-*`, `shop-sc-matrix-entry-tracking-link`)',
          'CO peer strip platform/collaborative/ATP (`shop-sc-matrix-entry-co-peer-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.b2bMatrix}?collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-sc-cabinet',
        label: 'Кабинет · витрина',
        order: 4,
        staticScore: 7.1,
        liveScore: 8.5,
        summary: 'ShopShowroomMini + honest full-showroom CTA.',
        good: [
          'shop-sc-cabinet-panel + golden path strip',
          'Partner logo PG + hero strip',
          'Empty state при 0 published',
          'e2e EMPTY27 + core-02 partner row',
          'core-38 SS27 cabinet partner + matrix CTA e2e',
          'Golden path UAT (`shop-sc-cabinet-golden-path`)',
          'Published sync badge (`shop-sc-cabinet-published-sync`)',
          '3D panel hub + CTA (`shop-sc-cabinet-3d-panel`, `shop-sc-3d-stream-cta`)',
          'Honest mini→full strip (`shop-sc-cabinet-full-showroom-honest-strip`)',
          'B2B peer strip platform/marketroom/checkout (`shop-sc-cabinet-b2b-peer-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.coreCabinet}?pillar=sample_collection&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
    collection_order: [
      {
        id: 'shop-co-matrix',
        label: 'Матрица оптового заказа',
        order: 1,
        staticScore: 7.7,
        liveScore: 8.5,
        summary: 'CoreWholesaleMatrix; cart hydrate+upsert PG (P0); checkout golden path.',
        good: [
          'PG matrix rows',
          'Panel + context strip (`shop-co-matrix-panel`)',
          'Канон testids `shop-co-matrix-*` + legacy',
          'e2e matrix→checkout→новый B2B order',
          'Matrix spine peer strip collaborative/replenishment/tracking (`shop-co-matrix-spine-peer-strip`)',
          'core-15 clean PG checkout без B2B-DEMO pin',
          'GET/upsert cart lines PG + cookie session (workshop2-cart-bridge, P0)',
          'Без JOOR/NuOrder на core',
          'Сводная матрица сезона (`shop-co-season-matrix-strip`)',
          'Golden path strip B2B spine (`shop-wholesale-matrix-golden-path-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.b2bMatrix}?collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-co-checkout',
        label: 'Checkout · отправка бренду',
        order: 2,
        staticScore: 7.5,
        liveScore: 8.5,
        summary: 'Синхронизация в PG B2B order — monetization moment (CELL 7.6).',
        good: [
          'POST create order',
          'resolveHref → `/shop/b2b/checkout` (не matrix)',
          'Panel + context strip (`shop-co-checkout-panel`)',
          'Buyer label + канон testids `shop-co-checkout-*`',
          'Честный бейдж резерва',
          'Статус submitted + системное сообщение в чат заказа при checkout',
          'Multi-tenant buyer (`shop-b2b-buyer-switcher`, cookie `shop_b2b_buyer_id`)',
          'Inline peer picker на checkout (`shop-co-checkout-buyer-picker`)',
          'Buyer из `activeOrganizationId` + `x-w2-organization-id` (org→shop1/shop2 map)',
          'Org приоритетнее cookie при onboarding',
          'Расширенный org map: shop1/shop2, org-shop-002, retail_spb_*',
          'Session uid → buyer (`shop-001`/`shop-002`)',
          'Production JWT guard на checkout (`guardShopB2bCheckoutRoute`, `WORKSHOP2_B2B_CHECKOUT_REQUIRE_JWT`)',
          'Working order tabs: PlatformCoreWmsReserveStrip (`shop-working-order-reserve-copy`)',
          'Checkout monetization peer CRM/collaborative/comms (`shop-co-checkout-monetization-peer-strip`)',
          'Registry post-checkout link (`shop-co-checkout-registry-link`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.b2bCheckout}?collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-co-registry',
        label: 'Реестр оптовых заказов',
        order: 3,
        staticScore: 7.3,
        liveScore: 8.5,
        summary: 'Список PG заказов, guards legacy + greenfield CRM/pricelist onboarding.',
        good: [
          'orders-core',
          'B2bChainPhaseBadge',
          'withShopB2bCoreLegacyGuard',
          'Экспорт CSV (`shop-co-registry-export-csv`)',
          'Context strip столп 3 (`shop-co-registry-context-strip`: matrix/заказ/tracking)',
          'Канон panel/focus (`shop-co-registry-panel`, `shop-co-registry-focus-row`)',
          'Превью треда (`shop-b2b-order-chat-preview-*`)',
          'SSE registry refetch при checkout/submit',
          'Onboarding empty (`shop-co-registry-empty-onboarding`)',
          'Buyer CRM onboarding strip (`shop-co-registry-buyer-crm-onboarding`, PG segment/terms)',
          'Checkout + brand pricelist CTA (`shop-co-registry-onboarding-checkout`, `shop-co-registry-onboarding-brand-pricelist`)',
          'Invite panel на partners discover (`shop-sc-partners-invite-panel-*`)',
        ],
        bad: [],
        fix: [],
        resolveHref: () => ROUTES.shop.b2bOrders,
      },
      {
        id: 'shop-co-detail',
        label: 'Карточка заказа',
        order: 4,
        staticScore: 7.3,
        liveScore: 8.5,
        summary: 'Факты PG, этапы, ETA peek + tracking cross-link.',
        good: [
          'shop-order-detail-core',
          'Трекинг link на PO card',
          'Panel + context strip (`shop-co-detail-panel`, `shop-co-detail-context-strip`)',
          'Cross-links столп 3 (`shop-co-detail-cross-links`)',
          'Amend card до handoff (`shop-co-detail-amend-card`) + повтор в матрице',
          'Structured amend API (`shop-b2b-amend-request-submit`)',
          'ETA peek strip после confirm (`shop-co-detail-eta-peek-strip`, tracking API)',
          'B2B invoice PDF (`schet-offerta.pdf?format=pdf`, jsPDF pipeline)',
          'CO spine peer matrix→replenishment (`shop-co-detail-context-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) => shopB2bOrderHref(d.demoOrderId),
      },
      {
        id: 'shop-co-buyer-tracking',
        label: 'Трекинг покупателя · PO',
        order: 5,
        staticScore: 7.8,
        liveScore: 8.1,
        summary: 'Canonical buyer path — visibility policy в chain-status-batch buyerView.',
        good: [
          'shopB2bTrackingOrderHref / #shop-co-buyer-tracking',
          'ShopProductionVisibility none/milestones/full (core-16 e2e)',
          'Brand disclosure preview strip (core-21/29/44)',
          'core-19 clean PG buyer-tracking после handoff',
          'core-44: brand disclosure link → tracking chain steps на B2B-\\d+',
          'chain-status-batch buyerView + PG order testids',
          'Tracking chat link ?pillar&section=shop-co-buyer-tracking (core-46)',
          'Legacy ?pillar=order_production redirect',
          'Materials/PO strips по visibility policy',
          'e2e core-01/06: shop-co primary testids',
          'SSE chain status на tracking panel',
          'Batch delivery ack (`shop-co-buyer-delivery-batch-ack`)',
          'delivery_received chain step + ack badges',
          'Reserve push via chain SSE (`shop-co-tracking-reserve-*`, data-reserve-sse-live)',
          'PG logistics ТТН cross-role (`brand-co-logistics-tracking`, `shop-co-tracking-shipment-*`, core-56)',
          'Factory ack peer mirror (`shop-co-chain-peer-po-synced`, core-56)',
          'PO status SSE second-actor live (`shop-co-chain-peer-po-pending`, core-57)',
          'Brand confirm → shop mirror live без reload (core-57)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) => shopB2bTrackingOrderHref(d.demoOrderId),
      },
      {
        id: 'shop-co-cabinet',
        label: 'Кабинет · формирование заказа',
        order: 6,
        staticScore: 7.4,
        liveScore: 8.5,
        summary: 'CollectionOrderPillarCard со steps shop_sent/brand_confirmed.',
        good: [
          'Pillar card steps',
          'Panel + CTA groups (`shop-co-cabinet-panel`)',
          'Checkout из hub (`shop-co-cabinet-checkout-link`)',
          'Amend CTA (`shop-co-cabinet-amend-link`) до confirm бренда',
          'Post-confirm bulk amend (`shop-co-cabinet-working-order-amend-link`)',
          'Трекинг read (`shop-co-cabinet-tracking-link`)',
          'Cart qty badge (`shop-collection-order-cart-qty-badge`)',
          'Compact CO spine peer matrix→pricelist→ATP (`shop-co-cabinet-co-spine-peer-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.coreCabinet}?pillar=collection_order&collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-co-replenishment',
        label: 'Replenishment workspace',
        order: 7,
        staticScore: 6.2,
        liveScore: 8.5,
        summary:
          'Onfinity-style ops: ATP/reorder; cross-links → matrix, working order, inventory (pillar-capability-registry).',
        good: [
          'SmartReplenishment + B2bOrderUrlContextBanner',
          'Golden path strip (`shop-replenishment-golden-path-strip`)',
          'PillarCapabilityWorkspaceChrome (alerts · stock-atp · rules — live tabs)',
          'Stock·ATP table (`shop-replenishment-feature-stock-atp`)',
          'Intake allocate CTA (`shop-replenishment-intake-allocate-run`) → POST /api/b2b/intake/allocate',
          'Rules save+allocate one-click (`shop-replenishment-rules-save-allocate-run`)',
          'Supplier forecast ↔ replenishment cross-spine (`shop-replenishment-supplier-forecast-link`, `supplier-forecast-replenishment-atp-link`)',
          'Rule presets PG API (`/api/shop/b2b/replenishment/rules`, storageMode pg/file)',
          'Rules panel buyer-scoped save (`shop-replenishment-rules-save`)',
          'PillarCapabilityCrossLinksStrip',
          'Shop inventory workspace (`shop-inventory-ops`)',
          'B2bPriorityWorkflowPanel: Replenishment в analytics-shop group',
          'Golden path checkout step + CO spine peer (`shop-replenishment-golden-checkout-link`, `shop-replenishment-co-spine-peer-strip`)',
        ],
        bad: [],
        fix: ['Saved filter slices sidebar'],
        resolveHref: (d) =>
          `${ROUTES.shop.b2bReplenishment}?collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-co-agent-rep',
        label: 'Agent / sales rep',
        order: 8,
        staticScore: 6.8,
        liveScore: 8.5,
        summary: 'Rep portal · commission · matrix · checkout · tracking.',
        good: [
          'shop-agent-rep workspace (portal/commission/matrix)',
          'Golden path strip (`shop-agent-rep-golden-path-strip`)',
          'Checkout + tracking monetization links in golden path',
          'Commission preview/payout API + PG ledger fetch',
          'Brand ledger cross-link',
          'Offline draft API (`/api/shop/b2b/rep/offline-drafts`, file/memory badge)',
          'Brand CRM + collaborative peer strip (`shop-agent-rep-brand-co-peer-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: () => ROUTES.shop.b2bSalesRepPortal,
      },
      {
        id: 'shop-co-landed-margin',
        label: 'Landed margin · shop',
        order: 9,
        staticScore: 7.2,
        liveScore: 8.5,
        summary: 'Hub/rollup/pricelist + golden path → matrix → checkout.',
        good: [
          'shop-landed-margin workspace',
          'Golden path strip (`shop-landed-margin-golden-path-strip`)',
          'PG margin feed API + B2B order rollup + sync',
          'PG tier sync read on pricelist tab',
          'Hub tools: calculator/report/landed cost',
          'CO spine peer matrix/checkout/ATP/comms/pricelist (`shop-co-landed-margin-spine-peer-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.b2bMarginAnalysis}?collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-co-collaborative-order',
        label: 'Collaborative order · session',
        order: 10,
        staticScore: 6.9,
        liveScore: 8.5,
        summary: 'Session/approvals/comms + golden path → matrix → tracking.',
        good: [
          'shop-collaborative-order workspace',
          'Golden path strip (`shop-collaborative-order-golden-path-strip`)',
          'Working order step in golden path (`shop-collaborative-golden-working-order-link`)',
          'Extended peer strip working order/replenishment (`shop-collaborative-order-extended-peer-strip`)',
          'Participants + approval chain panels',
          'PG approval workflow API (`/api/shop/b2b/collaborative/approvals`)',
          'Advance buttons (`shop-collaborative-approval-advance-*`)',
          'Brand order chat/handoff bridges на approvals/comms',
          'Extended peer checkout link (`shop-collaborative-checkout-link`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.b2bCollaborativeOrder}?collection=${encodeURIComponent(d.collectionId)}&${PILLAR_CAPABILITY_FEATURE_PARAM}=session`,
      },
      {
        id: 'shop-co-working-order',
        label: 'Working order · versions',
        order: 11,
        staticScore: 6.9,
        liveScore: 8.5,
        summary: 'Versions/bulk/handoff + native order honest strip + tracking href.',
        good: [
          'shop-working-order workspace',
          'Golden path strip (`shop-working-order-golden-path-strip`)',
          'Native order honest strip (`shop-working-order-native-order-honest-strip`)',
          'Tracking via shopB2bTrackingOrderHref in golden path',
          'PlatformCoreWmsReserveStrip на tabs',
          'Spine panel INT-* imported orders',
          'CO spine peer ATP/collaborative/brand chat (`shop-working-order-co-spine-peer-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.b2bWorkingOrder}?collection=${encodeURIComponent(d.collectionId)}&${PILLAR_CAPABILITY_FEATURE_PARAM}=versions`,
      },
    ],
    order_production: [
      {
        id: 'shop-op-tracking',
        label: 'Трекинг цепочки',
        order: 1,
        staticScore: 7.2,
        liveScore: 8.0,
        summary: 'Read-only 5 шагов + live WMS reserve badge при PG WMS.',
        good: [
          '5 steps + materials done/pending badges',
          'Канон testids `shop-co-tracking-*` (legacy shop-op-* audit-only, core-45)',
          'shop-co-tracking-sse/poll badge',
          'e2e core-01/06: shop-co primary testids (helper)',
          'Reserve badge честный + WMS e2e',
          'Выпуск + registry с `?order=` в strip/rows',
          'B2bChainPhaseBadge + CSV export',
          'Tracking→calendar/chat/production CTA',
          'platform-core-chain-step-* на шагах',
          'Batch delivery ack panel (`shop-co-buyer-delivery-batch-ack`)',
          'shop-order-comms golden path (`shop-order-comms-golden-path-strip`)',
          'Working order + replenishment on context strip (`shop-co-tracking-working-order-link`, `shop-co-tracking-replenishment-link`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) => shopB2bTrackingOrderHref(d.demoOrderId),
      },
      {
        id: 'shop-op-order-status',
        label: 'Карточка · статус PO',
        order: 2,
        staticScore: 7.2,
        liveScore: 8.0,
        scoreAliasOf: 'shop-co-detail',
        summary: 'Тот же заказ с `?pillar=order_production`.',
        good: ['Chain card: steps + SSE + materials badge'],
        bad: [],
        fix: [],
        resolveHref: (d) => shopB2bOrderProductionContextHref(d.demoOrderId),
      },
      {
        id: 'shop-op-registry',
        label: 'Реестр · контекст',
        order: 3,
        staticScore: 7.3,
        liveScore: 8.0,
        scoreAliasOf: 'shop-co-registry',
        summary: 'Тот же реестр с `?pillar=order_production`.',
        good: ['Фильтр in_production + focus row'],
        bad: [],
        fix: [],
        resolveHref: (d) => shopB2bOrdersProductionRegistryHref(d.demoOrderId),
      },
      {
        id: 'shop-op-cabinet',
        label: 'Кабинет · после отправки',
        order: 4,
        staticScore: 7.2,
        liveScore: 8.5,
        summary: 'CollectionOrder hub (alias shop-op): ETA peek + tracking CTA.',
        good: [
          'Panel (`shop-co-cabinet-panel`, audit alias `shop-op-cabinet-panel`)',
          'shop-co-tracking-context-strip: заказ · чат · реестр (без calendar)',
          'PO/ETA peek в hub (`shop-op-cabinet-eta-peek-strip`, tracking API + PO badge)',
          'Registry с `?order=`',
          'SSE/poll badge (`shop-op-cabinet-*-badge`)',
          'compact-only hub',
          'OP spine peer handoff/tracking/margin/inventory/comms (`shop-op-cabinet-spine-peer-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.coreCabinet}?pillar=order_production&collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-op-inventory-ops',
        label: 'Inventory · overview',
        order: 5,
        staticScore: 7.3,
        liveScore: 8.0,
        summary: 'PG ledger strip on overview + reconcile tab + golden path.',
        good: [
          'shop-inventory-ops workspace',
          'Golden path strip (`shop-inventory-ops-golden-path-strip`)',
          'PlatformCoreInventoryLedgerStrip (`shop-inventory-ledger-strip`)',
          'Reconcile panel + InventoryPageContent',
          'Brand inventory cross-link',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.inventory}?${PILLAR_CAPABILITY_FEATURE_PARAM}=overview&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
    comms: [
      {
        id: 'shop-cm-order-chat',
        label: 'Чат · заказ',
        order: 1,
        staticScore: 7.4,
        liveScore: 8.5,
        summary: 'Связь с брендом по B2B заказу; registry stream on order workspace.',
        good: [
          'threads API',
          'contextual chat= URL',
          'Universal inbox: все заказы PG в sidebar',
          'B2B шаблоны в slimCore',
          'Article-chat витрина/матрица (`shop-showroom-article-chat-link-*`, `shop-b2b-matrix-article-chat-*`)',
          'shopMessagesWorkshop2ArticleContextHref',
          'PG unread + registry SSE bump в shop messages',
          'shop-cm-order-context-strip',
          'Order context peer registry/matrix/checkout/handoff/collaborative (`shop-cm-order-brand-handoff-link`)',
          'shop-cm-order-chat-link в hub',
          'Server read receipts (shop-buyer actor)',
          'Core: чат на карточке заказа, не в реестре',
          'Hub collection_order compact: CommsNotificationCenterStrip (`shop-co-cabinet-panel`)',
          'Order workspace registry stream (`shop-cm-order-registry-stream-health-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) => shopMessagesB2bOrderContextHref(d.demoOrderId),
      },
      {
        id: 'shop-cm-calendar-order',
        label: 'Календарь · заказ',
        order: 2,
        staticScore: 7.1,
        liveScore: 8.5,
        summary: 'Окна отгрузки, клик → чат; PG user tasks + monetization + brand CRM peers.',
        good: [
          'externalEventsOnly → chat',
          'Hub compact: notification center на collection_order + full comms pillar',
          'Статус одной строкой в hub comms card',
          'shop-cm-calendar-link в hub',
          'Context peer strip tracking/chat/replenishment/checkout/brand CRM (`shop-cm-calendar-context-peer-strip`)',
          'PG user tasks strip + refetch on create (`shop-cm-calendar-user-tasks`)',
          'Role-correct order chat href (shop/brand/mfr/supplier)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) => shopCalendarB2bOrderContextHref(d.demoOrderId),
      },
      {
        id: 'shop-cm-calendar-logistics',
        label: 'Календарь · закупки',
        order: 3,
        staticScore: 7.0,
        liveScore: 8.5,
        scoreAliasOf: 'shop-cm-calendar-order',
        summary: 'Слой logistics на том же экране — окна поставки и materials_supplied.',
        good: [
          'layers=orders,logistics',
          'materials_supplied → b2b-materials-* event',
          'Alias scoring — скрыт из разворота hub (scoreAliasOf)',
        ],
        bad: [],
        fix: [],
        resolveHref: () => `${ROUTES.shop.b2bCalendar}?layers=orders,logistics`,
      },
      {
        id: 'shop-cm-cabinet',
        label: 'Кабинет · связь',
        order: 4,
        staticScore: 7.2,
        liveScore: 8.5,
        summary: 'CommsPillarCard shop, clean PG section-groups (core-40).',
        good: [
          'shop-cm-cabinet-po-inbox из buyer registry',
          'Registry stream health strip (`shop-cm-cabinet-registry-stream-health-strip`)',
          'CommsPillarCard',
          'Clean PG buyer-tracking section-group (core-40)',
          'shop-cm-cabinet-thread-search',
          'shop-cm-thread-search workspace',
          'shop-cm-banner dedupe',
          'shop-cm-* hub links (волны 68–70)',
          'CommsNotificationCenterStrip compact/full (`shop-cm-notification-center*`)',
          'Cabinet spine peer registry/matrix/checkout/pricelist/ATP (`shop-cm-cabinet-spine-peer-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.coreCabinet}?pillar=comms&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
  };
