/**
 * @generated split from platform-core-readiness-sections.ts — do not edit monolith; edit role file.
 */
import type { CoreHubPillarId } from '@/lib/platform-core-hub-matrix';
import {
  brandLinesheetsHrefForDemo,
  brandShowroomHrefForDemo,
  factoryHandoffQueueHrefForDemo,
  factoryMaterialsHrefForDemo,
  factoryMaterialsProcurementHrefForDemo,
  platformCoreRolePillarHref,
  shopShowroomHrefForDemo,
} from '@/lib/platform-core-hub-matrix';
import {
  ROUTES,
  brandB2bOrderChainContextHref,
  brandB2bOrderDossierContextHref,
  brandB2bOrderHandoffContextHref,
  brandB2bOrderHref,
  brandB2bOrdersAwaitingHandoffRegistryHref,
  brandB2bOrdersProductionRegistryHref,
  brandCoreOrderProductionCabinetHref,
  brandCalendarB2bOrderContextHref,
  brandMessagesB2bOrderContextHref,
  brandMessagesWorkshop2ArticleContextHref,
  brandW2ProductionTzHref,
  factoryMessagesB2bOrderContextHref,
  factoryMessagesWorkshop2ArticleContextHref,
  factoryCoreOrderProductionCabinetHref,
  factorySupplierCoreOrderProductionCabinetHref,
  factoryProductionDossierContextHref,
  factoryProductionDossierHref,
  factoryProductionOrdersOrderContextHref,
  factorySupplierMessagesB2bOrderContextHref,
  factorySupplierMessagesWorkshop2ArticleContextHref,
  shopB2bOrderHref,
  shopB2bOrderProductionContextHref,
  shopB2bOrdersProductionRegistryHref,
  shopB2bTrackingOrderHref,
  shopCalendarB2bOrderContextHref,
  shopMessagesB2bOrderContextHref,
} from '@/lib/routes';
import { WORKSHOP2_COL_PARAM, workshop2ArticleHref } from '@/lib/production/workshop2-url';
import type { SectionAuditTemplate } from './types';

export const SUPPLIER_SECTION_AUDIT: Partial<Record<CoreHubPillarId, readonly SectionAuditTemplate[]>> = {
    development: [
      {
        id: 'sup-dev-bom',
        label: 'BOM · спецификация',
        order: 1,
        staticScore: 7.2,
        liveScore: 7.3,
        summary: 'Материалы из dossier PG — основа RFQ-free core.',
        good: ['SupplierBomPreview', 'UoM в preview', 'Drawer expand'],
        bad: ['Legacy suppliers hub вне core', 'Нет каталога в nav'],
        fix: ['Core redirect suppliers', 'Material catalog nav'],
        resolveHref: (d) => factoryMaterialsHrefForDemo(d),
      },
      {
        id: 'sup-dev-materials',
        label: 'Материалы · разработка',
        order: 2,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'view=development — workspace столпа.',
        good: [
          'materials-core development',
          'List chrome',
          'materials-price-journal из dossier_events',
          'materials-price-history fallback из unitCostNet',
        ],
        bad: ['Журнал пуст без событий с ценами в PG'],
        fix: ['Compare suppliers P2', 'Price delta alert'],
        resolveHref: (d) => {
          const params = new URLSearchParams({
            collection: d.collectionId,
            article: d.demoArticleId,
            view: 'development',
          });
          return `${ROUTES.factory.productionMaterials}?${params.toString()}`;
        },
      },
      {
        id: 'sup-dev-comms-peer',
        label: 'Чат · уточнение цены',
        order: 3,
        staticScore: 7.0,
        liveScore: 7.3,
        summary: 'Alias entry sup-cm-article (столп 1 development).',
        good: [
          'RFQ→[] в core',
          'sup-cm-article-chat-link unified (волна 69)',
          'Шаблон article-price-quote (волна 45)',
        ],
        bad: ['Дубль nav столп 1 vs 5 (осознанный alias)', 'Нет SLA ответа'],
        fix: ['SLA timer P2'],
        resolveHref: (d) =>
          factorySupplierMessagesWorkshop2ArticleContextHref(d.collectionId, d.demoArticleId),
      },
      {
        id: 'sup-dev-cabinet',
        label: 'Кабинет · BOM образца',
        order: 4,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'SupplierBomPreview compact в кабинете.',
        good: [
          'Только BOM без пустого RFQ',
          'Primary → materials',
          'materials-bom-fill-rate',
          'materials-alt-materials из substitutes',
        ],
        bad: ['Fill-rate без весов по критичности строк'],
        fix: ['Weighted BOM completeness', 'Alt materials approval flow'],
        resolveHref: (d) =>
          `${ROUTES.factory.supplierCoreCabinet}?pillar=development&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
    order_production: [
      {
        id: 'sup-op-procurement',
        label: 'Закупка · PATCH',
        order: 1,
        staticScore: 7.0,
        liveScore: 7.4,
        summary: 'material-request confirm — monetization supply; brand chat section context (волна 29).',
        good: [
          'PATCH API',
          'e2e core-02',
          'Confirm gated on PO queue',
          'Канон panel (`sup-op-procurement-panel`, волна 80)',
          'RU статус PO + handoff poll refresh (волна 80)',
          'Success strip → tracking/chat (волна 80)',
          'Context strip + tracking cross-role (волна 80)',
          'bulk-confirm API (все BOM строки)',
          'role=supplier canonical href + cabinet back',
          'Multi-article wizard + confirmAllArticles API (волна 97)',
          'Brand chat → section auto-thread (`sup-op-procurement-brand-chat-link`, core-48)',
        ],
        bad: ['Нет WMS reserve на checkout'],
        fix: ['Inventory reserve post-handoff'],
        resolveHref: (d) => factoryMaterialsProcurementHrefForDemo(d, { role: 'supplier' }),
      },
      {
        id: 'sup-op-bom-po',
        label: 'BOM × PO · прогресс',
        order: 2,
        staticScore: 7.2,
        liveScore: 7.4,
        summary: 'Прогресс BOM по заполненным строкам досье — без искусственного cap.',
        good: [
          'supplier-procurement-bom-progress',
          'sup-op-bom-po-progress на workspace (волна 64)',
          'PO qty из queue',
          'bomPct без cap 40%',
        ],
        bad: ['Multi-article wizard только demo article'],
        fix: ['PO bundle PDF'],
        resolveHref: (d) => factoryMaterialsProcurementHrefForDemo(d, { role: 'supplier' }),
      },
      {
        id: 'sup-op-chain',
        label: 'Этап · materials_supplied',
        order: 3,
        staticScore: 7.0,
        liveScore: 7.3,
        summary: 'Видимость WMS + materials шагов цепочки для поставщика.',
        good: [
          'sup-op-chain-steps + workspace mirror',
          'sup-op-chain-sse/poll badge workspace (волна 76)',
          'WMS reserve в chainSteps + badge (`sup-op-cabinet-wms-reserve-badge`, core-43)',
          'Чат бренду на шаге (`sup-op-chain-workspace-brand-chat-link`, section context)',
          'materials badges на procurement workspace',
        ],
        bad: ['Push notification бренду'],
        fix: ['SSE push вместо poll-only UX'],
        resolveHref: (d) => factorySupplierCoreOrderProductionCabinetHref(d.collectionId),
      },
      {
        id: 'sup-op-handoff-read',
        label: 'Очередь передачи · read',
        order: 4,
        staticScore: 7.0,
        liveScore: 7.4,
        summary: 'Контекст PO до закупки.',
        good: [
          'Handoff queue fetch + refresh на chain poll',
          'order= в procurement href',
          'PO deep-link (`sup-op-handoff-read-po-link`)',
          'Strip (`sup-op-handoff-read-strip`) + счётчик (`sup-op-handoff-read-queue-count`, волна 77)',
          'CTA очередь (`sup-op-handoff-read-queue-link`)',
        ],
        bad: ['Нет dedicated handoff-queue SSE (poll через chain tick)'],
        fix: ['Subscribe handoff-queue SSE (P2)'],
        resolveHref: (d) => factoryHandoffQueueHrefForDemo(d),
      },
      {
        id: 'sup-op-cabinet',
        label: 'Кабинет · закупка',
        order: 5,
        staticScore: 7.0,
        liveScore: 7.6,
        summary: 'SupplierProcurementPillarCard — hub агрегатор столпа 4 + WMS badge.',
        good: [
          'Panel (`sup-op-cabinet-panel`, волна 82)',
          'CTA groups production/comms (волна 82)',
          'Tracking peer link всегда (`sup-op-cabinet-tracking-link`)',
          'SSE/poll badge (`sup-op-cabinet-*-badge`, волна 74)',
          'WMS reserve badge (`sup-op-cabinet-wms-reserve-badge`, core-43)',
          'BOM + chain + handoff в одной карточке',
          'Multi-article wizard на procurement workspace (волна 97)',
        ],
        bad: ['Три nav столпа order_production'],
        fix: [],
        resolveHref: (d) => factorySupplierCoreOrderProductionCabinetHref(d.collectionId),
      },
    ],
    comms: [
      {
        id: 'sup-cm-order',
        label: 'Чат · заказ',
        order: 1,
        staticScore: 7.1,
        liveScore: 7.4,
        summary: 'Связь с брендом/цехом по B2B.',
        good: [
          'supplier role messages',
          'Redirect /factory/supplier→core',
          'Universal inbox merge',
          'sup-cm-order-context-strip (волна 68)',
          'sup-cm-order-chat-link в hub',
        ],
        bad: ['Нет e2e order= dedupe', 'Тонкий CRM'],
        fix: ['E2E supplier messages banner dedupe', 'Quote templates'],
        resolveHref: (d) => factorySupplierMessagesB2bOrderContextHref(d.demoOrderId),
      },
      {
        id: 'sup-cm-article',
        label: 'Чат · артикул',
        order: 2,
        staticScore: 7.0,
        liveScore: 7.2,
        summary: 'Уточнение материалов по артикулу.',
        good: [
          'Article context `/factory/supplier/messages`',
          'sup-cm-article-context-strip (волна 69)',
          'sup-cm-article-chat-link в hub + BOM workspace',
          'Шаблон article-price-quote',
          'supplier-procurement-*-article-chat',
        ],
        bad: ['sup-dev-comms-peer alias тот же URL (документировано)'],
        fix: ['Quote card UI (не только template)'],
        resolveHref: (d) =>
          factorySupplierMessagesWorkshop2ArticleContextHref(d.collectionId, d.demoArticleId),
      },
      {
        id: 'sup-cm-calendar',
        label: 'Календарь · логистика',
        order: 3,
        staticScore: 7.2,
        liveScore: 7.5,
        summary: 'Logistics layer + delivery confirm event (core-36).',
        good: [
          'role=supplier calendar',
          'sup-cm-calendar-context-strip + procurement role=supplier (волна 70)',
          'sup-cm-calendar-link в hub',
          'Canonical `/factory/calendar` (не production ACL)',
          'sup-cm-delivery-confirm-btn + POST delivery-confirm (волна 17)',
        ],
        bad: ['Нет map/logistics'],
        fix: ['ETA/map overlay на delivery window'],
        resolveHref: () => `${ROUTES.factory.calendar}?role=supplier&layers=tasks,orders,logistics`,
      },
      {
        id: 'sup-cm-cabinet',
        label: 'Кабинет · связь',
        order: 4,
        staticScore: 7.1,
        liveScore: 7.4,
        summary: 'CommsPillarCard supplier, clean PG procurement section-group (core-40).',
        good: [
          'sup-cm-cabinet-po-inbox parity (волна 73)',
          'Clean PG sup-op-procurement section-group (core-40)',
          'sup-cm-cabinet-thread-search (волна 72)',
          'sup-cm-thread-search workspace (волна 72)',
          'sup-cm-banner + inbox parity (волна 71)',
          'sup-cm-* hub links (волны 68–70)',
          'Insight card',
          'Core redirect preserve hash',
          'comms-pillar-inbox-all supplier (волна 45)',
          'CommsPillarCard compact-only (волна 47)',
          'Очередь передачи в hub card (волна 47)',
        ],
        bad: ['Нет push'],
        fix: ['Push notifications'],
        resolveHref: (d) =>
          `${ROUTES.factory.supplierCoreCabinet}?pillar=comms&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
};
