/**
 * @generated split from platform-core-readiness-sections.ts — do not edit monolith; edit role file.
 */
import type { CoreHubPillarId } from '@/lib/platform-core-hub-matrix';
import {
  brandLinesheetsHrefForDemo,
  brandShowroomHrefForDemo,
  factoryHandoffQueueHrefForDemo,
  factoryMaterialsHrefForDemo,
  factoryMaterialsProcurementHrefForDemo,
  platformCoreRolePillarHref,
  shopShowroomHrefForDemo,
} from '@/lib/platform-core-hub-matrix';
import {
  ROUTES,
  brandB2bOrderChainContextHref,
  brandB2bOrderDossierContextHref,
  brandB2bOrderHandoffContextHref,
  brandB2bOrderHref,
  brandB2bOrdersAwaitingHandoffRegistryHref,
  brandB2bOrdersProductionRegistryHref,
  brandCoreOrderProductionCabinetHref,
  brandCalendarB2bOrderContextHref,
  brandMessagesB2bOrderContextHref,
  brandMessagesWorkshop2ArticleContextHref,
  brandW2ProductionTzHref,
  factoryMessagesB2bOrderContextHref,
  factoryMessagesWorkshop2ArticleContextHref,
  factoryCoreOrderProductionCabinetHref,
  factorySupplierCoreOrderProductionCabinetHref,
  factoryProductionDossierContextHref,
  factoryProductionDossierHref,
  factoryProductionOrdersOrderContextHref,
  factorySupplierMessagesB2bOrderContextHref,
  factorySupplierMessagesWorkshop2ArticleContextHref,
  shopB2bOrderHref,
  shopB2bOrderProductionContextHref,
  shopB2bOrdersProductionRegistryHref,
  shopB2bTrackingOrderHref,
  shopCalendarB2bOrderContextHref,
  shopMessagesB2bOrderContextHref,
} from '@/lib/routes';
import { WORKSHOP2_COL_PARAM, workshop2ArticleHref } from '@/lib/production/workshop2-url';
import type { SectionAuditTemplate } from './types';

export const SUPPLIER_SECTION_AUDIT: Partial<
  Record<CoreHubPillarId, readonly SectionAuditTemplate[]>
> = {
  development: [
    {
      id: 'sup-dev-bom',
      label: 'BOM · спецификация',
      order: 1,
      staticScore: 7.2,
      liveScore: 8.5,
      summary: 'Материалы из dossier PG — основа RFQ-free core.',
      good: [
        'SupplierBomPreview',
        'UoM в preview',
        'Drawer expand',
        'Brand BOM peer (`sup-dev-bom-brand-peer-link`)',
        'Dev BOM chain peer on procurement (`sup-op-bom-po-chain-peer-strip`)',
        'Mfr dev peer strip brand W2/dossier/comms (`sup-dev-bom-mfr-dev-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => factoryMaterialsHrefForDemo(d),
    },
    {
      id: 'sup-dev-materials',
      label: 'Материалы · разработка',
      order: 2,
      staticScore: 7.1,
      liveScore: 8.0,
      summary: 'view=development — workspace столпа; honest empty price journal strip.',
      good: [
        'materials-core development',
        'List chrome',
        'materials-price-journal из dossier_events',
        'materials-price-history fallback из unitCostNet',
        'Honest empty journal strip + RFQ/BOM/comms peers (`sup-dev-materials-price-journal-honest-strip`)',
      ],
      bad: [],
      fix: ['Compare suppliers P2', 'Price delta alert'],
      resolveHref: (d) => {
        const params = new URLSearchParams({
          collection: d.collectionId,
          article: d.demoArticleId,
          view: 'development',
        });
        return `${ROUTES.factory.productionMaterials}?${params.toString}`;
      },
    },
    {
      id: 'sup-dev-comms-peer',
      label: 'Чат · уточнение цены',
      order: 3,
      staticScore: 7.0,
      liveScore: 8.0,
      summary: 'Alias entry sup-cm-article (столп 1 development).',
      good: [
        'RFQ→[] в core',
        'sup-cm-article-chat-link unified',
        'Шаблон article-price-quote',
        'SLA response strip on RFQ (`sup-dev-sla-response-strip`)',
      ],
      bad: ['Дубль nav столп 1 vs 5 (осознанный alias)'],
      fix: ['SLA timer P2'],
      resolveHref: (d) =>
        factorySupplierMessagesWorkshop2ArticleContextHref(d.collectionId, d.demoArticleId),
    },
    {
      id: 'sup-dev-cabinet',
      label: 'Кабинет · BOM образца',
      order: 4,
      staticScore: 7.1,
      liveScore: 8.0,
      summary: 'SupplierBomPreview compact в кабинете.',
      good: [
        'Только BOM без пустого RFQ',
        'Primary → materials',
        'materials-bom-fill-rate',
        'materials-bom-weighted-fill-rate',
        'materials-alt-materials из substitutes',
        'core-53 materials-bom-fill-rate e2e',
        'Dev cabinet spine peer BOM/RFQ/CRM (`sup-dev-cabinet-spine-peer-strip`)',
      ],
      bad: [],
      fix: ['Alt materials approval flow'],
      resolveHref: (d) =>
        `${ROUTES.factory.supplierCoreCabinet}?pillar=development&collection=${encodeURIComponent(d.collectionId)}`,
    },
  ],
  order_production: [
    {
      id: 'sup-op-procurement',
      label: 'Закупка · PATCH',
      order: 1,
      staticScore: 7.0,
      liveScore: 8.0,
      summary: 'material-request confirm — monetization supply; brand chat section context.',
      good: [
        'PATCH API',
        'e2e core-02',
        'Confirm gated on PO queue',
        'Канон panel (`sup-op-procurement-panel`)',
        'RU статус PO + handoff poll refresh',
        'Success strip → tracking/chat',
        'Context strip + tracking cross-role',
        'bulk-confirm API (все BOM строки)',
        'role=supplier canonical href + cabinet back',
        'Multi-article wizard + confirmAllArticles API',
        'Brand chat → section auto-thread (`sup-op-procurement-brand-chat-link`, core-48)',
        'Brand push strip после confirm (`sup-op-procurement-brand-push-strip`)',
        'WMS reserve strip на procurement (`sup-op-procurement-wms-reserve-strip`)',
        'Golden path strip (`supplier-procurement-golden-path-strip`)',
        'Forecast/supply spine peer (`sup-op-procurement-forecast-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => factoryMaterialsProcurementHrefForDemo(d, { role: 'supplier' }),
    },
    {
      id: 'sup-op-bom-po',
      label: 'BOM × PO · прогресс',
      order: 2,
      staticScore: 7.2,
      liveScore: 8.0,
      summary: 'Прогресс BOM по заполненным строкам досье — без искусственного cap.',
      good: [
        'supplier-procurement-bom-progress',
        'sup-op-bom-po-progress на workspace',
        'PO qty из queue',
        'bomPct без cap 40%',
        'PO bundle PDF (`po-bundle.pdf`, sup-op-bom-po-bundle-pdf)',
        'Chain spine peer handoff/forecast/tracking (`sup-op-bom-po-chain-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => factoryMaterialsProcurementHrefForDemo(d, { role: 'supplier' }),
    },
    {
      id: 'sup-op-chain',
      label: 'Этап · materials_supplied',
      order: 3,
      staticScore: 7.0,
      liveScore: 8.0,
      summary: 'Видимость WMS + materials шагов цепочки для поставщика.',
      good: [
        'sup-op-chain-steps + workspace mirror',
        'sup-op-chain-sse/poll badge workspace',
        'WMS reserve в chainSteps + badge (`sup-op-cabinet-wms-reserve-badge`, core-43)',
        'Чат бренду на шаге (`sup-op-chain-workspace-brand-chat-link`, section context)',
        'materials badges на procurement workspace',
        'chain-status SSE bump на materials confirm (materials_supplied step)',
        'Brand notify strip + order chat deep-link (`sup-op-procurement-brand-push-*`)',
        'Workspace peer forecast/tracking/supply (`sup-op-chain-workspace-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => factorySupplierCoreOrderProductionCabinetHref(d.collectionId),
    },
    {
      id: 'sup-op-handoff-read',
      label: 'Очередь передачи · read',
      order: 4,
      staticScore: 7.0,
      liveScore: 8.0,
      summary: 'Контекст PO до закупки.',
      good: [
        'Handoff queue fetch + refresh на chain poll',
        'order= в procurement href',
        'PO deep-link (`sup-op-handoff-read-po-link`)',
        'Strip (`sup-op-handoff-read-strip`) + счётчик (`sup-op-handoff-read-queue-count`)',
        'CTA очередь (`sup-op-handoff-read-queue-link`)',
        'Peer strip manufacturer SSE (`supplier-manufacturer-handoff-peer-strip`)',
        'Spine peer mfr queue/forecast/tracking (`sup-op-handoff-read-spine-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => factoryHandoffQueueHrefForDemo(d),
    },
    {
      id: 'sup-op-cabinet',
      label: 'Кабинет · закупка',
      order: 5,
      staticScore: 7.0,
      liveScore: 8.0,
      summary: 'SupplierProcurementPillarCard — unified spine nav strip.',
      good: [
        'Panel (`sup-op-cabinet-panel`)',
        'Unified spine nav (`sup-op-cabinet-spine-nav-strip`)',
        'CTA groups production/comms',
        'Tracking peer link всегда (`sup-op-cabinet-tracking-link`)',
        'SSE/poll badge (`sup-op-cabinet-*-badge`)',
        'WMS reserve badge compact + SSE (`sup-op-cabinet-wms-reserve-badge`, data-reserve-sse-live)',
        'BOM + chain + handoff в одной карточке',
        'Multi-article wizard на procurement workspace',
        'Manufacturer read-only article tabs (`mfr-op-procurement-article-wizard`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => factorySupplierCoreOrderProductionCabinetHref(d.collectionId),
    },
  ],
  comms: [
    {
      id: 'sup-cm-order',
      label: 'Чат · заказ',
      order: 1,
      staticScore: 7.1,
      liveScore: 8.5,
      summary: 'Связь с брендом/цехом; CRM peer strip.',
      good: [
        'supplier role messages',
        'Redirect /factory/supplier→core',
        'Universal inbox merge',
        'sup-cm-order-context-strip',
        'sup-cm-order-chat-link в hub',
        'core-14 supplier messages dedupe e2e',
        'Quote templates via slimCore + custom save (shared with brand B2B bar)',
        'Entities tab: inbox SSE/poll + manufacturer handoff peer (`supplier-comms-entity-*`)',
        'CRM peer strip (`sup-cm-crm-peer-strip`)',
        'Order context spine procurement→tracking (`sup-cm-order-context-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => factorySupplierMessagesB2bOrderContextHref(d.demoOrderId),
    },
    {
      id: 'sup-cm-article',
      label: 'Чат · артикул',
      order: 2,
      staticScore: 7.0,
      liveScore: 8.0,
      summary: 'Уточнение материалов по артикулу.',
      good: [
        'Article context `/factory/supplier/messages`',
        'sup-cm-article-context-strip',
        'sup-cm-article-chat-link в hub + BOM workspace',
        'Шаблон article-price-quote',
        'supplier-procurement-*-article-chat',
        'Quote card UI on comms pillar (`sup-cm-article-quote-honest-strip`)',
      ],
      bad: ['sup-dev-comms-peer alias тот же URL (документировано)'],
      fix: ['Quote card UI — honest strip ✓'],
      resolveHref: (d) =>
        factorySupplierMessagesWorkshop2ArticleContextHref(d.collectionId, d.demoArticleId),
    },
    {
      id: 'sup-cm-calendar',
      label: 'Календарь · логистика',
      order: 3,
      staticScore: 7.2,
      liveScore: 8.5,
      summary: 'Logistics layer + delivery confirm + procurement spine peers.',
      good: [
        'role=supplier calendar',
        'sup-cm-calendar-context-strip + procurement role=supplier',
        'Context peer procurement/forecast/mfr handoff/tracking (`sup-cm-calendar-context-peer-strip`)',
        'Logistics peer strip (`sup-cm-calendar-logistics-peer-strip`)',
        'PG user tasks strip + refetch (`sup-cm-calendar-user-tasks`)',
        'sup-cm-calendar-link в hub',
        'Canonical `/factory/calendar` (не production ACL)',
        'sup-cm-delivery-confirm-btn + POST delivery-confirm',
      ],
      bad: [],
      fix: ['ETA/map overlay на delivery window'],
      resolveHref: () => `${ROUTES.factory.calendar}?role=supplier&layers=tasks,orders,logistics`,
    },
    {
      id: 'sup-cm-cabinet',
      label: 'Кабинет · связь',
      order: 4,
      staticScore: 7.1,
      liveScore: 8.5,
      summary: 'CommsPillarCard supplier, clean PG procurement section-group (core-40).',
      good: [
        'sup-cm-cabinet-po-inbox parity',
        'Clean PG sup-op-procurement section-group (core-40)',
        'sup-cm-cabinet-thread-search',
        'sup-cm-thread-search workspace',
        'sup-cm-banner + inbox parity',
        'sup-cm-* hub links (волны 68–70)',
        'Brand push strip (`sup-cm-cabinet-brand-push-strip`) + chat/entities/supply links',
        'Insight card',
        'Core redirect preserve hash',
        'comms-pillar-inbox-all supplier',
        'CommsPillarCard compact-only',
        'Очередь передачи в hub card',
        'Cabinet spine peer procurement→brand chat (`sup-cm-cabinet-spine-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.factory.supplierCoreCabinet}?pillar=comms&collection=${encodeURIComponent(d.collectionId)}`,
    },
  ],
};
