import type { StagesDependenciesTabContentBuildArgs } from '@/components/brand/production/stages-dependencies-tab-content-build-args';
import type { Workshop2StagesDependenciesProcessTabProps } from '@/components/brand/production/Workshop2StagesDependenciesProcessTab';

export function buildStagesDependenciesTabsProcessProps(
  ctx: StagesDependenciesTabContentBuildArgs
): Workshop2StagesDependenciesProcessTabProps {
  const {
    depsPinned,
    setDepsPinned,
    depsOpen,
    setDepsOpen,
    depsExpanded,
    focusArticle,
    chainFocusStepId,
    steps,
    toggleChainFocus,
    viewArticles,
    depsSchemaChunks,
    productionProfileId,
    setDepsNodeInfoStepId,
    matrixPinned,
    setMatrixPinned,
    matrixOpen,
    setMatrixOpen,
    matrixExpanded,
    matrixStageFilterQ,
    onMatrixSearchChange,
    clearMatrixFilters,
    matrixPhaseParam,
    matrixTextQParam,
    scrollToCurrentMatrixStage,
    matrixPhaseOptions,
    setMatrixPhaseFilter,
    focusSkuMatrixPhase,
    aggregateStatus,
    isBlocked,
    matrixStepsFiltered,
    flowDoc,
    effectiveSkuIds,
    markStatus,
    openSkuPanelForStep,
    router,
    mergeCollectionQuery,
    collectionQuery,
    floorHref,
    mergeModuleHref,
    getProductionFloorTabTitle,
    navigateToStageModule,
  } = ctx;

  return {
    depsPinned,
    onDepsPinnedChange: setDepsPinned,
    depsOpen,
    onDepsOpenChange: setDepsOpen,
    depsExpanded,
    focusArticle,
    chainFocusStepId,
    steps,
    toggleChainFocus,
    viewArticles,
    depsSchemaChunks,
    productionProfileId,
    onOpenDepsNodeInfo: setDepsNodeInfoStepId,
    matrixPinned,
    onMatrixPinnedChange: setMatrixPinned,
    matrixOpen,
    onMatrixOpenChange: setMatrixOpen,
    matrixExpanded,
    matrixStageFilterQ,
    onMatrixSearchChange,
    clearMatrixFilters,
    matrixPhaseParam,
    matrixTextQParam,
    scrollToCurrentMatrixStage,
    matrixPhaseOptions,
    setMatrixPhaseFilter,
    focusSkuMatrixPhase,
    aggregateStatus,
    isBlocked,
    matrixStepsFiltered,
    flowDoc,
    effectiveSkuIds,
    markStatus,
    openSkuPanelForStep,
    routerPush: (href) => router.push(href),
    mergeCollectionQuery,
    collectionQuery,
    floorHref,
    mergeModuleHref,
    getProductionFloorTabTitle,
    navigateToStageModule,
  };
}
