/**
 * Явная матрица требований к полям ТЗ по листу справочника L1›L2›L3 (ключ = нормализованные сегменты).
 * Не править вручную — пересборка: `npm run gen:tz-leaf-requirements`.
 */
export type TzLeafExtraRequirements = {
  collectionSeasonRequired: boolean;
  packagingDimensionsRequired: boolean;
  customsHsDeclarationRequired: boolean;
  certificationMarksRequired: boolean;
};

/** Плейсхолдер «—» и пустая строка → пустой сегмент в ключе. */
export function handbookSegmentNorm(segment: string): string {
  const t = (segment ?? '').trim();
  if (t === '' || t === '—' || t === '–' || t === '-') return '';
  return t;
}

export function tzLeafKey(l1Name: string, l2Name: string, l3Name: string): string {
  return `${handbookSegmentNorm(l1Name)}›${handbookSegmentNorm(l2Name)}›${handbookSegmentNorm(l3Name)}`;
}

export const TZ_LEAF_EXTRA_REQUIREMENTS: Record<string, TzLeafExtraRequirements> = {
  'Аксессуары для новорождённых›Аксессуары›Бутылочки': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары для новорождённых›Аксессуары›Гигиена и купание': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары для новорождённых›Аксессуары›Пелёнки': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары для новорождённых›Аксессуары›Переноски и слинги': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары для новорождённых›Аксессуары›Подгузники': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары для новорождённых›Аксессуары›Поильники': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары для новорождённых›Аксессуары›Прочее': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары для новорождённых›Аксессуары›Соски и пустышки': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары для новорождённых›Коляски›Аксессуары для колясок': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары для новорождённых›Коляски›Коляски': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары›Галстуки и бабочки›Бабочки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары›Галстуки и бабочки›Галстуки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары›Зонты›': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары›Кожгалантерея мелкая›': { collectionSeasonRequired: false, packagingDimensionsRequired: false, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары›Маски и бафы›Балаклавы': { collectionSeasonRequired: false, packagingDimensionsRequired: false, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары›Маски и бафы›Бафы': { collectionSeasonRequired: false, packagingDimensionsRequired: false, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары›Маски и бафы›Маски': { collectionSeasonRequired: false, packagingDimensionsRequired: false, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары›Очки›': { collectionSeasonRequired: false, packagingDimensionsRequired: false, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары›Перчатки и варежки›Варежки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары›Перчатки и варежки›Перчатки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары›Платки›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары›Ремни и подтяжки›Подтяжки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары›Ремни и подтяжки›Ремни': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары›Тех-аксессуары›': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары›Украшения›': { collectionSeasonRequired: false, packagingDimensionsRequired: false, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Аксессуары›Шарфы›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Головные уборы›Береты›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Головные уборы›Кепки›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Головные уборы›Панамы›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Головные уборы›Шапки›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Головные уборы›Шляпы›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Дом и стиль жизни›Аксессуары›': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Дом и стиль жизни›Декор›': { collectionSeasonRequired: false, packagingDimensionsRequired: false, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Дом и стиль жизни›Питомцы›Лежанки': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Дом и стиль жизни›Питомцы›Одежда': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Дом и стиль жизни›Питомцы›Переноски': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Дом и стиль жизни›Питомцы›Поводки': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Дом и стиль жизни›Текстиль›Коврики для ванной': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Дом и стиль жизни›Текстиль›Пледы': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Дом и стиль жизни›Текстиль›Полотенца': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Дом и стиль жизни›Текстиль›Постельное': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Дом и стиль жизни›Текстиль›Скатерти': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Дом и стиль жизни›Текстиль›Шторы': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Дом и стиль жизни›Lifestyle-гаджеты›': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Игрушки (детские)››': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Красота и уход›Косметика›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Красота и уход›Парфюмерия›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Красота и уход›Уход›': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Носочно-чулочные›Гетры›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Носочно-чулочные›Гольфы›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Носочно-чулочные›Колготки›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Носочно-чулочные›Носки›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Носочно-чулочные›Чулки›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Ботинки›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Домашняя обувь›': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Кроссовки›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Мокасины и топсайдеры›Мокасины': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Мокасины и топсайдеры›Топсайдеры': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Мюли›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Сабо›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Сандалии и шлёпанцы›Босоножки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Сандалии и шлёпанцы›Сандалии': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Сандалии и шлёпанцы›Шлепанцы': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Сапоги›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Слипоны›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Спортивная›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Туфли›Балетки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Туфли›Классические / лодочки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Угги и унты›Валенки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Угги и унты›Угги': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Угги и унты›Унты': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Обувь›Эспадрильи›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Брюки›Джоггеры': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Брюки›Карго': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Брюки›Классические': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Брюки›Спортивные': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Брюки›Чиносы': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Верхняя одежда›Бомберы': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Верхняя одежда›Ветровки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Верхняя одежда›Дождевики': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Верхняя одежда›Жилеты': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Верхняя одежда›Комбинезоны': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Верхняя одежда›Куртки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Верхняя одежда›Лайнеры': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Верхняя одежда›Пальто': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Верхняя одежда›Парки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Верхняя одежда›Плащи': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Верхняя одежда›Подстёжки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Верхняя одежда›Пончо': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Верхняя одежда›Пуховики': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Верхняя одежда›Тренчи': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Верхняя одежда›Шубы': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Джинсы›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Костюмы и жакеты›Блейзеры': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Костюмы и жакеты›Жилеты': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Костюмы и жакеты›Костюмы': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Костюмы и жакеты›Пиджаки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Костюмы и жакеты›Смокинги': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Костюмы и жакеты›Фраки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Нижнее бельё›': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Пижамы и домашняя одежда›Комплекты': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Пижамы и домашняя одежда›Лонгсливы': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Пижамы и домашняя одежда›Халаты': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Платья и сарафаны›Платья': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Платья и сарафаны›Сарафаны': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Пляжная мода›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Рубашки и блузы›Блузы': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Рубашки и блузы›Рубашки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Спортивная одежда›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Топы и футболки›Кроп-топы': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Топы и футболки›Майки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Топы и футболки›Поло': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Топы и футболки›Топы': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Топы и футболки›Футболки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Трикотаж›Водолазки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Трикотаж›Кардиганы': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Трикотаж›Свитеры': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Трикотаж›Худи': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Трикотаж›Юбки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Одежда›Юбки›': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Сумки›Вечерние›': { collectionSeasonRequired: true, packagingDimensionsRequired: false, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Сумки›Косметички›Несессеры': { collectionSeasonRequired: true, packagingDimensionsRequired: false, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Сумки›Повседневные›Клатч': { collectionSeasonRequired: true, packagingDimensionsRequired: false, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Сумки›Повседневные›Кросс-боди': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Сумки›Повседневные›Поясная': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Сумки›Повседневные›Рюкзак': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Сумки›Повседневные›Тот': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Сумки›Повседневные›Шоппер': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Сумки›Рабочие›Для ноутбука': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Сумки›Рабочие›Портфель': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Сумки›Спортивные и дорожные›Дорожные сумки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Сумки›Спортивные и дорожные›Спортивные сумки': { collectionSeasonRequired: true, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
  'Сумки›Чемоданы›': { collectionSeasonRequired: false, packagingDimensionsRequired: true, customsHsDeclarationRequired: true, certificationMarksRequired: true },
};

const TZ_EXTRA_NONE: TzLeafExtraRequirements = {
  collectionSeasonRequired: false,
  packagingDimensionsRequired: false,
  customsHsDeclarationRequired: false,
  certificationMarksRequired: false,
};

/** Лист не из справочника — доп. поля ТЗ не навязываем (остаётся только GLOBAL_TZ_REQUIRED у вызывающего). */
export function getTzLeafExtraRequirements(l1Name: string, l2Name: string, l3Name: string): TzLeafExtraRequirements {
  const k = tzLeafKey(l1Name, l2Name, l3Name);
  return TZ_LEAF_EXTRA_REQUIREMENTS[k] ?? TZ_EXTRA_NONE;
}
