/**
 * Явная матрица требований к полям ТЗ по листу справочника L1›L2›L3 (ключ = нормализованные сегменты).
 * Не править вручную — пересборка: `npm run gen:tz-leaf-requirements`.
 */
export type TzLeafExtraRequirements = {
  collectionSeasonRequired: boolean;
  packagingDimensionsRequired: boolean;
  customsHsDeclarationRequired: boolean;
  certificationMarksRequired: boolean;
};

/** Плейсхолдер «—» и пустая строка → пустой сегмент в ключе. */
export function handbookSegmentNorm(segment: string): string {
  const t = (segment ?? '').trim();
  if (t === '' || t === '—' || t === '–' || t === '-') return '';
  return t;
}

export function tzLeafKey(l1Name: string, l2Name: string, l3Name: string): string {
  return `${handbookSegmentNorm(l1Name)}›${handbookSegmentNorm(l2Name)}›${handbookSegmentNorm(l3Name)}`;
}

export const TZ_LEAF_EXTRA_REQUIREMENTS: Record<string, TzLeafExtraRequirements> = {
  'Аксессуары для новорождённых›Аксессуары›Бутылочки': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары для новорождённых›Аксессуары›Гигиена и купание': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары для новорождённых›Аксессуары›Пелёнки': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары для новорождённых›Аксессуары›Переноски и слинги': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары для новорождённых›Аксессуары›Подгузники': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары для новорождённых›Аксессуары›Поильники': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары для новорождённых›Аксессуары›Прочее': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары для новорождённых›Аксессуары›Соски и пустышки': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары для новорождённых›Коляски›Аксессуары для колясок': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары для новорождённых›Коляски›Коляски': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Галстуки и бабочки›Бабочки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Галстуки и бабочки›Галстуки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Галстуки и бабочки›Зажимы для галстука': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Зонты›Складные': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Зонты›Трости': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Кожгалантерея мелкая›Визитницы': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Кожгалантерея мелкая›Ключницы': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Кожгалантерея мелкая›Кошельки': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Кожгалантерея мелкая›Обложки для документов': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Кожгалантерея мелкая›Портмоне': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Маски и бафы›Балаклавы': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Маски и бафы›Бафы': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Маски и бафы›Маски': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Очки›Оправы': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Очки›Солнцезащитные': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Очки›Футляры для очков': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Перчатки и варежки›Варежки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Перчатки и варежки›Митенки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Перчатки и варежки›Перчатки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Платки›Банданы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Платки›Косынки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Платки›Шейные платки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Ремни и подтяжки›Подтяжки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Ремни и подтяжки›Пояса': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Ремни и подтяжки›Ремни': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Тех-аксессуары›Ремешки для часов': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Тех-аксессуары›Чехлы для наушников': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Тех-аксессуары›Чехлы для телефонов': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Украшения›Браслеты': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Украшения›Броши': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Украшения›Колье': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Украшения›Кольца': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Украшения›Подвески': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Украшения›Серьги': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Украшения›Цепочки': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Шарфы›Горжетки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Шарфы›Палантины': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Шарфы›Снуды': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Аксессуары›Шарфы›Шарфы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Береты›Классические': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Береты›Объемные': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Кепки›Бейсболки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Кепки›Кепки-уточки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Кепки›Снепбеки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Кепки›Тракеры': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Панамы›Панамы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Панамы›Шляпы-ведро': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Шапки›Бини': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Шапки›Капоры': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Шапки›С помпоном': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Шапки›Ушанки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Шляпы›Канотье': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Шляпы›Котелки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Шляпы›Трилби': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Шляпы›Федоры': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Шляпы›Цилиндры': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Головные уборы›Шляпы›Широкополые': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Аксессуары›Ароматы для дома': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Аксессуары›Диффузоры': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Аксессуары›Органайзеры': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Аксессуары›Саше': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Декор›Вазы': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Декор›Зеркала': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Декор›Картины': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Декор›Подсвечники': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Декор›Постеры': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Декор›Свечи': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Декор›Статуэтки': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Питомцы›Игрушки': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Питомцы›Лежанки': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Питомцы›Миски': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Питомцы›Одежда': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Питомцы›Ошейники': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Питомцы›Переноски': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Питомцы›Поводки': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Текстиль›Коврики для ванной': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Текстиль›Пледы': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Текстиль›Полотенца': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Текстиль›Постельное': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Текстиль›Салфетки': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Текстиль›Скатерти': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Текстиль›Шторы': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Lifestyle-гаджеты›Будильники': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Lifestyle-гаджеты›Лампы': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Lifestyle-гаджеты›Массажеры': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Дом и стиль жизни›Lifestyle-гаджеты›Увлажнители': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Игрушки (детские)›Игрушки›Конструкторы': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Игрушки (детские)›Игрушки›Куклы': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Игрушки (детские)›Игрушки›Машинки': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Игрушки (детские)›Игрушки›Мягкие игрушки': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Игрушки (детские)›Игрушки›Настольные игры': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Игрушки (детские)›Игрушки›Развивающие': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Косметика›Для бровей': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Косметика›Для глаз': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Косметика›Для губ': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Косметика›Для лица': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Косметика›Кисти и спонжи': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Косметика›Палетки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Парфюмерия›Духи': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Парфюмерия›Одеколоны': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Парфюмерия›Парфюмерная вода': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Парфюмерия›Спреи для тела': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Парфюмерия›Туалетная вода': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Уход›Для волос': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Уход›Для лица': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Уход›Для ног': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Уход›Для рук': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Уход›Для тела': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Красота и уход›Уход›Солнцезащитные средства': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Носочно-чулочные›Гетры›Вязаные': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Носочно-чулочные›Гетры›Спортивные': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Носочно-чулочные›Гольфы›Капроновые': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Носочно-чулочные›Гольфы›Хлопковые': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Носочно-чулочные›Колготки›Капроновые': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Носочно-чулочные›Колготки›Фантазийные': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Носочно-чулочные›Колготки›Хлопковые': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Носочно-чулочные›Колготки›Шерстяные': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Носочно-чулочные›Носки›Классические': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Носочно-чулочные›Носки›Короткие': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Носочно-чулочные›Носки›Следки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Носочно-чулочные›Носки›Спортивные': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Носочно-чулочные›Чулки›Компрессионные': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Носочно-чулочные›Чулки›Под пояс': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Носочно-чулочные›Чулки›С кружевом': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Ботинки›Берцы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Ботинки›Дезерты': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Ботинки›Демисезонные': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Ботинки›Зимние': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Ботинки›Тимберленды': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Ботинки›Треккинговые': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Ботинки›Челси': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Домашняя обувь›Тапочки': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Домашняя обувь›Чуни': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Кроссовки›Повседневные': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Кроссовки›Сникерсы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Кроссовки›Спортивные': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Кроссовки›Хайтопы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Мокасины и топсайдеры›Мокасины': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Мокасины и топсайдеры›Слипоны': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Мокасины и топсайдеры›Топсайдеры': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Мокасины и топсайдеры›Эспадрильи': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Сандалии и шлёпанцы›Босоножки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Сандалии и шлёпанцы›Вьетнамки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Сандалии и шлёпанцы›Мюли': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Сандалии и шлёпанцы›Сабо': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Сандалии и шлёпанцы›Сандалии': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Сандалии и шлёпанцы›Шлепанцы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Сапоги›Ботфорты': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Сапоги›Демисезонные': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Сапоги›Зимние': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Сапоги›Казаки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Сапоги›Полусапоги': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Сапоги›Резиновые': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Туфли›Балетки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Туфли›Броги': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Туфли›Дерби': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Туфли›Классические / лодочки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Туфли›Лоферы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Туфли›Оксфорды': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Угги и унты›Валенки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Угги и унты›Дутики': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Угги и унты›Угги': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Обувь›Угги и унты›Унты': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Брюки›Бермуды': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Брюки›Джоггеры': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Брюки›Карго': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Брюки›Классические': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Брюки›Леггинсы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Брюки›Спортивные': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Брюки›Чиносы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Брюки›Шорты': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Анораки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Бомберы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Ветровки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Дождевики': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Дубленки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Жилеты': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Комбинезоны': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Косухи': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Куртки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Лайнеры': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Пальто': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Парки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Плащи': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Подстёжки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Пончо': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Пуховики': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Тренчи': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Верхняя одежда›Шубы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Джинсы›Бойфренды': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Джинсы›Зауженные': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Джинсы›Клеш': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Джинсы›Мом': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Джинсы›Прямые': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Джинсы›Скинни': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Джинсы›Широкие': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Костюмы и жакеты›Блейзеры': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Костюмы и жакеты›Жилеты': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Костюмы и жакеты›Костюмы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Костюмы и жакеты›Пиджаки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Костюмы и жакеты›Смокинги': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Костюмы и жакеты›Фраки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Нижнее бельё›Боди': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Нижнее бельё›Бюстгальтеры': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Нижнее бельё›Бюстье': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Нижнее бельё›Комбинации': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Нижнее бельё›Корсеты': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Нижнее бельё›Термобелье': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Нижнее бельё›Трусы': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Пижамы и домашняя одежда›Комплекты': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Пижамы и домашняя одежда›Ночные сорочки': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Пижамы и домашняя одежда›Пижамы': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Пижамы и домашняя одежда›Халаты': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Платья и сарафаны›Платья': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Платья и сарафаны›Сарафаны': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Платья и сарафаны›Туники': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Пляжная мода›Парео': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Пляжная мода›Плавки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Пляжная мода›Пляжные туники': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Пляжная мода›Раздельные купальники': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Пляжная мода›Слитные купальники': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Рубашки и блузы›Блузы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Рубашки и блузы›Рубашки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Рубашки и блузы›Сорочки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Спортивная одежда›Рашгарды': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Спортивная одежда›Спортивные костюмы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Спортивная одежда›Спортивные топы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Спортивная одежда›Тайтсы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Спортивная одежда›Шорты для плавания': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Топы и футболки›Кроп-топы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Топы и футболки›Лонгсливы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Топы и футболки›Майки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Топы и футболки›Поло': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Топы и футболки›Топы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Топы и футболки›Футболки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Трикотаж›Водолазки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Трикотаж›Джемперы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Трикотаж›Кардиганы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Трикотаж›Пуловеры': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Трикотаж›Свитеры': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Трикотаж›Свитшоты': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Трикотаж›Худи': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Юбки›Макси': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Юбки›Миди': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Одежда›Юбки›Мини': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Вечерние›Клатчи': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Вечерние›Минодьеры': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Вечерние›Сумки-конверты': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Косметички›Бьюти-кейсы': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Косметички›Косметички': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Косметички›Несессеры': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Повседневные›Клатч': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: false,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Повседневные›Кросс-боди': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Повседневные›Поясная': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Повседневные›Рюкзак': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Повседневные›Сумка-багет': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Повседневные›Сумка-мешок': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Повседневные›Тот': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Повседневные›Шоппер': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Рабочие›Для ноутбука': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Рабочие›Папки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Рабочие›Портфель': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Рабочие›Сумка-портфель': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Спортивные и дорожные›Дафл': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Спортивные и дорожные›Дорожные сумки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Спортивные и дорожные›Рюкзаки туристические': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Спортивные и дорожные›Спортивные сумки': {
    collectionSeasonRequired: true,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Чемоданы›Кейсы': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Чемоданы›На колесах': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
  'Сумки›Чемоданы›Сумки-тележки': {
    collectionSeasonRequired: false,
    packagingDimensionsRequired: true,
    customsHsDeclarationRequired: true,
    certificationMarksRequired: true,
  },
};

const TZ_EXTRA_NONE: TzLeafExtraRequirements = {
  collectionSeasonRequired: false,
  packagingDimensionsRequired: false,
  customsHsDeclarationRequired: false,
  certificationMarksRequired: false,
};

/** Лист не из справочника — доп. поля ТЗ не навязываем (остаётся только GLOBAL_TZ_REQUIRED у вызывающего). */
export function getTzLeafExtraRequirements(
  l1Name: string,
  l2Name: string,
  l3Name: string
): TzLeafExtraRequirements {
  const k = tzLeafKey(l1Name, l2Name, l3Name);
  return TZ_LEAF_EXTRA_REQUIREMENTS[k] ?? TZ_EXTRA_NONE;
}
