import { defineConfig, devices } from '@playwright/test';

const CORE_PORT = process.env.PLAYWRIGHT_CORE_PORT ?? '3001';
const CORE_BASE_URL = process.env.PLAYWRIGHT_BASE_URL ?? `http://127.0.0.1:${CORE_PORT}`;

export default defineConfig({
  testDir: './e2e',
  testMatch: [
    '**/core-01-platform-smoke.spec.ts',
    '**/core-02-demo-golden-path.spec.ts',
    '**/core-03-interactive-handoff.spec.ts',
    '**/core-04-legacy-redirects.spec.ts',
    '**/core-05-readiness-slimcore.spec.ts',
    '**/core-06-collections-fw-empty.spec.ts',
    '**/core-07-pg-interactive-bootstrap.spec.ts',
    '**/core-08-section-audit-smoke.spec.ts',
    '**/core-09-chain-status-sse.spec.ts',
    '**/core-10-no-bootstrap-honesty.spec.ts',
    '**/core-11-mes-release-stages.spec.ts',
    '**/core-12-bulk-accept-registry.spec.ts',
    '**/core-13-comms-cross-nav.spec.ts',
    '**/core-14-comms-banner-dedupe.spec.ts',
    '**/core-15-clean-pg-registry.spec.ts',
    '**/core-16-shop-production-visibility.spec.ts',
    '**/core-17-pg-primary-mode.spec.ts',
    '**/core-18-clean-pg-spine-golden-path.spec.ts',
    '**/core-19-clean-pg-spine-full-chain.spec.ts',
    '**/core-20-clean-pg-comms-spine.spec.ts',
    '**/core-21-comms-section-groups.spec.ts',
    '**/core-22-empty-checkout-mfr-po-inbox.spec.ts',
    '**/core-23-calendar-create-task-thread.spec.ts',
    '**/core-24-clean-pg-14-cell-matrix.spec.ts',
    '**/core-25-comms-notifications-supplier-quote.spec.ts',
    '**/core-26-brand-export-fw27-audit-path.spec.ts',
    '**/core-27-pg-hub-wms-confirm.spec.ts',
    '**/core-28-hub-chain-linesheet-batch.spec.ts',
    '**/core-29-publish-audit-disclosure-import.spec.ts',
    '**/core-30-bulk-section-export.spec.ts',
    '**/core-31-supplier-comms-peer-insight.spec.ts',
    '**/core-32-joor-import-registry-export.spec.ts',
    '**/core-33-operational-list-pg-primary.spec.ts',
    '**/core-34-clean-pg-erp-retry.spec.ts',
    '**/core-35-comms-sse-unread-bump.spec.ts',
    '**/core-36-supplier-delivery-confirm.spec.ts',
    '**/core-37-brand-create-article-wizard.spec.ts',
    '**/core-38-shop-showroom-empty-onboarding.spec.ts',
    '**/core-39-clean-pg-section-deep.spec.ts',
    '**/core-40-clean-pg-comms-four-roles.spec.ts',
    '**/core-41-batch-publish-audit-roundtrip.spec.ts',
    '**/core-42-clean-pg-mfr-handoff-shop-floor.spec.ts',
    '**/core-43-clean-pg-po-calendar-export-wms.spec.ts',
    '**/core-44-brand-dev-disclosure-mfr-calendar.spec.ts',
    '**/core-45-brand-showroom-unified-clean-pg-tracking.spec.ts',
    '**/core-46-linesheet-audit-order-comms-thread.spec.ts',
    '**/core-47-pg-collections-retailers-tier.spec.ts',
    '**/core-48-mfr-sup-interaction-comms-thread.spec.ts',
    '**/core-49-brand-op-minimums-clean-pg.spec.ts',
    '**/core-51-prebook-registry.spec.ts',
    '**/core-52-p0-wave-gaps.spec.ts',
    '**/core-53-p0-tz-margin-investor.spec.ts',
    '**/core-54-dual-session-wave-a.spec.ts',
    '**/core-55-manufacturer-erp-clean-pg.spec.ts',
    '**/core-56-logistics-cross-role-tracking.spec.ts',
    '**/core-57-po-status-sse-second-actor.spec.ts',
    '**/core-58-range-planner-tier-drag.spec.ts',
    '**/core-59-erp-retry-ux.spec.ts',
    '**/core-60-wave-c-empty-pdf-comms.spec.ts',
    '**/core-61-wms-reserve-redis.spec.ts',
    '**/core-62-wave-d-dossier-prefs.spec.ts',
    '**/core-63-wave-d-persist-typecheck.spec.ts',
    '**/core-64-wave-d-investor-attr.spec.ts',
    '**/core-65-wave-d-sketch-tz-hooks.spec.ts',
    '**/core-66-wave-d-tz-signoff-tasks.spec.ts',
    '**/core-67-wave-d-material-handbook-hooks.spec.ts',
    '**/core-68-wave-d-section-rows-orchestration.spec.ts',
    '**/core-69-wave-e-tech-debt-passport.spec.ts',
    '**/core-70-wave-f-send-handoff-dev-chrome.spec.ts',
    '**/core-71-wave-g-handbook-nav-split.spec.ts',
    '**/core-72-wave-h-section-readiness-flow.spec.ts',
    '**/core-73-wave-i-tz-gates-roles.spec.ts',
    '**/core-74-wave-j-passport-export.spec.ts',
    '**/core-75-wave-k-visuals-nav.spec.ts',
    '**/core-76-wave-l-tz-sample-readiness.spec.ts',
    '**/core-77-wave-m-tz-notify-cabinet.spec.ts',
    '**/core-78-wave-n-route-urls-tsc.spec.ts',
    '**/core-79-wave-o-handbook-metrics.spec.ts',
    '**/core-80-wave-p-journal-types.spec.ts',
    '**/core-81-wave-q-continue-runway-types.spec.ts',
    '**/core-82-wave-r-sketch-pin-library.spec.ts',
    '**/core-83-wave-s-handbook-mutations.spec.ts',
    '**/core-84-wave-t-mat-shell-zones.spec.ts',
    '**/core-85-wave-u-tz-nav-zones.spec.ts',
    '**/core-86-wave-v-section-layout-zones.spec.ts',
    '**/core-87-wave-w-props-bundles.spec.ts',
    '**/core-88-wave-x-panel-tail.spec.ts',
    '**/core-89-wave-y-section-body-flat.spec.ts',
    '**/core-90-pillar-workspace-pcf.spec.ts',
    '**/core-91-hub-layout-viewports.spec.ts',
    '**/core-92-cabinet-layout-viewports.spec.ts',
    '**/core-93-shop-matrix-smoke.spec.ts',
  ],
  timeout: 120_000,
  fullyParallel: false,
  retries: 1,
  workers: 1,
  reporter: [['list']],
  use: {
    baseURL: CORE_BASE_URL,
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], viewport: { width: 1280, height: 900 } },
    },
  ],
  webServer: process.env.PLAYWRIGHT_SKIP_WEBSERVER
    ? undefined
    : {
        command: 'bash scripts/start-dev-core-e2e.sh',
        url: `${CORE_BASE_URL}/platform`,
        reuseExistingServer: true,
        timeout: 180_000,
        stdout: 'pipe',
        stderr: 'pipe',
      },
});
