/**
 * [Phase 2 — Control contracts]
 * Каталог кодов обоснования (Reason Codes) для рисков, блокеров и действий.
 * Обеспечивает explainability и типизацию сигналов управления.
 */

export const CONTROL_REASON_CODES = {
  // Order reasons
  AWAITING_BRAND_APPROVAL: 'AWAITING_BRAND_APPROVAL',
  PAYMENT_OVERDUE: 'PAYMENT_OVERDUE',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  
  // Article / Readiness reasons
  ARTICLE_INCOMPLETE: 'ARTICLE_INCOMPLETE',
  ARTICLE_BLOCKER: 'ARTICLE_BLOCKER',
  TECH_PACK_PENDING: 'TECH_PACK_PENDING',
  MATERIALS_NOT_SOURCED: 'MATERIALS_NOT_SOURCED',
  PRICING_MISSING: 'PRICING_MISSING',
  
  // Production / Execution reasons
  PRODUCTION_DELAY: 'PRODUCTION_DELAY',
  QC_FAILED: 'QC_FAILED',
  PRODUCTION_COMPLETED: 'PRODUCTION_COMPLETED',
  REWORK_REQUIRED: 'REWORK_REQUIRED',
  
  // Collection reasons
  COLLECTION_NOT_READY: 'COLLECTION_NOT_READY',
  
  // Sample reasons
  SAMPLE_PENDING: 'SAMPLE_PENDING',
  SAMPLE_REJECTED: 'SAMPLE_REJECTED',
  
  // Inventory reasons
  STOCK_OUT: 'STOCK_OUT',
  STOCK_LOW: 'STOCK_LOW',
  COMPLIANCE_HOLD: 'COMPLIANCE_HOLD',
  INVENTORY_DISCREPANCY: 'INVENTORY_DISCREPANCY',
  GRAIN_LOCKED: 'GRAIN_LOCKED',

  // New reasons for aggregation
  INVENTORY_REBALANCE_REQUIRED: 'INVENTORY_REBALANCE_REQUIRED',
  PREORDER_QUOTA_LOW: 'PREORDER_QUOTA_LOW',
  PREORDER_QUOTA_EXCEEDED: 'PREORDER_QUOTA_EXCEEDED',

  // Predictive reasons
  PREDICTIVE_DELAY_RISK: 'PREDICTIVE_DELAY_RISK',
  PREDICTIVE_STOCKOUT_RISK: 'PREDICTIVE_STOCKOUT_RISK',
} as const;

export type ControlReasonCode = keyof typeof CONTROL_REASON_CODES;
