
export const colorPalette = [
  { name: 'Черный', hex: '#000000' },
  { name: 'Белый', hex: '#FFFFFF' },
  { name: 'Серый', hex: '#808080' },
  { name: 'Бежевый', hex: '#F5F5DC' },
  { name: 'Коричневый', hex: '#A52A2A' },
  { name: 'Красный', hex: '#FF0000' },
  { name: 'Синий', hex: '#0000FF' },
  { name: 'Зеленый', hex: '#008000' },
  { name: 'Желтый', hex: '#FFFF00' },
  { name: 'Оранжевый', hex: '#FFA500' },
  { name: 'Фиолетовый', hex: '#800080' },
  { name: 'Розовый', hex: '#FFC0CB' },
  { name: 'Голубой', hex: '#ADD8E6' },
  { name: 'Темно-синий', hex: '#00008B' },
  { name: 'Хаки', hex: '#F0E68C' },
  { name: 'Оливковый', hex: '#808000' },
  { name: 'Бордовый', hex: '#800000' },
  { name: 'Золото', hex: '#FFD700' },
  { name: 'Серебро', hex: '#C0C0C0' },
  { name: 'Пудрово-розовый', hex: '#FADADD' },
  { name: 'Шампань', hex: '#F7E7CE' },
  { name: 'Серый меланж', hex: '#B2BEB5' },
];
