/**
 * Placeholder Images with Local SVG Data URIs
 * These are embedded as data URIs for guaranteed display without external dependencies
 */

export interface PlaceholderImage {
  id: string;
  description: string;
  imageUrl: string;
  imageHint: string;
  category?: string;
  hashtags?: string[];
  date?: string;
  duration?: number;
  hosts?: string[];
  guests?: string[];
}

export const PlaceHolderImages: PlaceholderImage[] = [
  {
    id: 'hero-1',
    description: 'A stylish woman in a modern outfit posing against a minimalist background.',
    imageUrl: '/images/hero.svg',
    imageHint: 'fashion model',
  },
  {
    id: 'ugc-client-1',
    description: 'Мой новый образ от @Gucci! В восторге от качества.',
    imageUrl: '/images/story-1.svg',
    imageHint: 'portrait person',
    category: 'UGC',
    hashtags: ['#Gucci', '#DailyLook', '#Syntha'],
    date: '2025-07-25T10:00:00Z',
    duration: 15,
  },
  {
    id: 'story-1',
    description: 'Стиль дня',
    imageUrl: '/images/story-1.svg',
    imageHint: 'portrait person',
    category: 'Новинки',
    hashtags: ['#Streetstyle', '#DailyLook'],
    date: '2025-07-20T10:00:00Z',
    duration: 15,
  },
  {
    id: 'story-2',
    description: 'Новинки недели',
    imageUrl: '/images/story-2.svg',
    imageHint: 'portrait person',
    category: 'Новинки',
    hashtags: ['#NewIn', '#SS24'],
    date: '2025-07-18T15:00:00Z',
    duration: 25,
  },
  {
    id: 'story-3',
    description: 'За кулисами',
    imageUrl: '/images/story-3.svg',
    imageHint: 'portrait person',
    category: 'Интервью',
    hashtags: ['#BehindTheScenes', '#Syntha'],
    date: '2025-06-25T12:00:00Z',
    duration: 45,
  },
  {
    id: 'story-4',
    description: 'Образ от @anna_looks',
    imageUrl: '/images/story-4.svg',
    imageHint: 'portrait person',
    category: 'Мастер-классы',
    hashtags: ['#StylingTips', '#Minimalism'],
    date: '2025-06-15T18:00:00Z',
    duration: 30,
  },
  {
    id: 'story-5',
    description: 'Коллаборация',
    imageUrl: '/images/story-5.svg',
    imageHint: 'portrait person',
    category: 'Коллекции',
    hashtags: ['#Collaboration', '#APC'],
    date: '2025-07-21T11:00:00Z',
    duration: 20,
  },
  {
    id: 'story-6',
    description: 'Тренды сезона',
    imageUrl: '/images/story-6.svg',
    imageHint: 'portrait person',
    category: 'Мастер-классы',
    hashtags: ['#Trends', '#FW24'],
    date: '2025-07-22T14:00:00Z',
    duration: 35,
  },
  {
    id: 'live-1',
    description: 'Презентация новой коллекции',
    imageUrl: '/images/live-1.svg',
    imageHint: 'live shopping',
    category: 'Новинки',
    hashtags: ['#NewCollection', '#Live', '#FW24'],
    date: '2025-11-19T19:00:00Z',
  },
  {
    id: 'live-2',
    description: 'Эксклюзивный дроп',
    imageUrl: '/images/live-2.svg',
    imageHint: 'fashion boutique',
    category: 'Коллекции',
    hashtags: ['#Exclusive', '#AcneStudios'],
    date: '2025-11-19T20:00:00Z',
  },
  {
    id: 'live-3',
    description: 'Беседы о стиле',
    imageUrl: '/images/live-3.svg',
    imageHint: 'fashion model',
    category: 'Интервью',
    hashtags: ['#StyleTalk', '#QandA'],
    date: '2025-11-19T21:00:00Z',
  },
  {
    id: 'live-4',
    description: 'За кулисами съемки',
    imageUrl: '/images/live-4.svg',
    imageHint: 'fashion backstage',
    category: 'Мастер-классы',
    hashtags: ['#Backstage', '#Photoshoot'],
    date: '2025-11-19T22:00:00Z',
  },
  {
    id: 'upcoming-1',
    description: 'Интервью с дизайнером',
    imageUrl: '/images/live-1.svg',
    imageHint: 'fashion designer',
    category: 'Интервью',
    hashtags: ['#Designer', '#Interview'],
    date: '2025-11-28T19:00:00Z',
  },
  {
    id: 'upcoming-2',
    description: 'Мастер-класс по стилизации',
    imageUrl: '/images/live-2.svg',
    imageHint: 'stylist work',
    category: 'Мастер-классы',
    hashtags: ['#StylingTips', '#Masterclass'],
    date: '2025-12-01T18:00:00Z',
  },
  {
    id: 'upcoming-3',
    description: 'Анонс коллаборации',
    imageUrl: '/images/live-3.svg',
    imageHint: 'fashion collaboration',
    category: 'Коллекции',
    hashtags: ['#Collaboration', '#JilSander'],
    date: '2025-12-05T20:00:00Z',
  },
  {
    id: 'podcast-live-1',
    description: 'Модные тренды 2026: что нас ждет?',
    imageUrl: '/images/live-1.svg',
    imageHint: 'podcast microphone',
    category: 'Подкасты',
    hashtags: ['#Тренды', '#БудущееМоды'],
    date: '2025-11-19T18:00:00Z',
    hosts: ['Анна Новикова', 'Иван Петров'],
    guests: ['Виктория Стильная'],
  },
  {
    id: 'podcast-upcoming-1',
    description: 'Устойчивая мода: миф или реальность?',
    imageUrl: '/images/live-2.svg',
    imageHint: 'sustainable fashion',
    category: 'Подкасты',
    hashtags: ['#ESG', '#Sustainability'],
    date: '2025-12-02T18:00:00Z',
    hosts: ['Анна Новикова'],
    guests: ['Сергей Экологов'],
  },
  {
    id: 'podcast-past-1',
    description: 'История Vogue: от журнала до медиаимперии',
    imageUrl: '/images/live-3.svg',
    imageHint: 'vintage magazine',
    category: 'Подкасты',
    hashtags: ['#ИсторияМоды', '#Vogue'],
    date: '2024-07-18T18:00:00Z',
    hosts: ['Иван Петров'],
    guests: [],
    duration: 45,
  },
  {
    id: 'banner-1',
    description: 'Promotional Banner',
    imageUrl: '/images/banner.svg',
    imageHint: 'sustainable fashion',
  },
  {
    id: 'avatar-3d',
    description: '3D Avatar',
    imageUrl: '/images/story-1.svg',
    imageHint: '3d model',
  },
  {
    id: 'nft-1',
    description: "Цифровая куртка 'Киберпанк'",
    imageUrl: '/images/story-2.svg',
    imageHint: 'digital fashion',
  },
  {
    id: 'nft-2',
    description: "Кроссовки 'Гравитация'",
    imageUrl: '/images/story-3.svg',
    imageHint: 'sci-fi sneakers',
  },
  {
    id: 'nft-3',
    description: 'Голографический визор',
    imageUrl: '/images/story-4.svg',
    imageHint: 'holographic glasses',
  },
];
