import type { CoreChainRoleId, CoreHubPillarId } from '@/lib/platform-core-hub-matrix';

/** Записи от агентов / Cursor — дополняйте массив ниже. */
export type PlatformCorePlannerAgentItem = {
  id: string;
  kind?: 'improve' | 'add' | 'stage' | 'existing';
  priority?: 'P0' | 'P1' | 'P2';
  title: string;
  roleId?: CoreChainRoleId;
  pillarId?: CoreHubPillarId;
  href?: string;
  status?: 'open' | 'in_progress' | 'done';
};

/**
 * Скан Platform Core / workshop2 spine (2026-06): блокеры сквозной цепочки в одной БД.
 * Evidence — пути в монорепо `_ai-share/synth-1-full`.
 */
export const PLATFORM_CORE_PLANNER_AGENT_ITEMS: PlatformCorePlannerAgentItem[] = [
  {
    id: 'agent-comms-chat-memory',
    kind: 'improve',
    priority: 'P2',
    title: 'Чат contextual: PG primary (закрыто: core-52 POST→GET round-trip)',
    roleId: 'brand',
    pillarId: 'comms',
    href: '/brand/messages',
    status: 'done',
  },
  {
    id: 'agent-comms-sender-hardcoded',
    kind: 'improve',
    priority: 'P1',
    title: "Contextual sender fallback «Участник» (workshop2-contextual-message-sender, не Current User)",
    roleId: 'brand',
    pillarId: 'comms',
    href: '/brand/messages',
    status: 'done',
  },
  {
    id: 'agent-comms-no-realtime',
    kind: 'add',
    priority: 'P1',
    title: 'Contextual chat SSE + poll fallback (`/api/messages/contextual/stream`, contextual-chat-sse-live-badge)',
    roleId: 'brand',
    pillarId: 'comms',
    href: '/brand/messages',
    status: 'done',
  },
  {
    id: 'agent-brand-tasks-localstorage',
    kind: 'improve',
    priority: 'P1',
    title: 'Tasks Kanban в localStorage (brand_tasks_kanban_v1), не API/PG (закрыто: PG API)',
    roleId: 'brand',
    pillarId: 'development',
    href: '/brand/tasks',
    status: 'done',
  },
  {
    id: 'agent-b2b-orders-json-snapshot',
    kind: 'improve',
    priority: 'P2',
    title: 'B2B operational orders: PG-primary (закрыто: core-33/52)',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/orders',
    status: 'done',
  },
  {
    id: 'agent-b2b-invoice-pdf-stub',
    kind: 'improve',
    priority: 'P1',
    title: 'Invoice PDF — jsPDF schet-offerta.pdf API (закрыто: core-52)',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/orders',
    status: 'done',
  },
  {
    id: 'agent-b2b-orders-no-pg',
    kind: 'add',
    priority: 'P2',
    title: 'Native B2B orders PG SoT (закрыто: workshop2_b2b_orders + core-33/52)',
    roleId: 'brand',
    pillarId: 'collection_order',
    href: '/brand/b2b-orders',
    status: 'done',
  },
  {
    id: 'agent-spine-no-single-pg-e2e',
    kind: 'add',
    priority: 'P2',
    title: 'E2E в одной БД (закрыто: core-15/52 contextual PG)',
    pillarId: 'development',
    href: '/',
    status: 'done',
  },
  {
    id: 'agent-dossier-file-legacy',
    kind: 'improve',
    priority: 'P1',
    title:
      'phase1-dossier PG-only banner + fail-closed file fallback (workshop2-core-dossier-file-persist-banner)',
    roleId: 'brand',
    pillarId: 'development',
    href: '/brand/production/workshop2',
    status: 'done',
  },
  {
    id: 'agent-no-pg-json-fallback',
    kind: 'improve',
    priority: 'P1',
    title:
      'Без PG — dossier file persist banner + WORKSHOP2_PG_ONLY block (не prod-ready)',
    roleId: 'brand',
    pillarId: 'development',
    href: '/brand/production/workshop2',
    status: 'done',
  },
  {
    id: 'agent-brand-sc-linesheet-diff',
    kind: 'improve',
    priority: 'P1',
    title: 'Лайншиты · коллекция: UAT linesheet→showroom diff panel',
    roleId: 'brand',
    pillarId: 'sample_collection',
    href: '/brand/linesheets',
    status: 'done',
  },
  {
    id: 'agent-brand-sc-preview-qty',
    kind: 'improve',
    priority: 'P1',
    title: 'Витрина бренда: Preview qty в linesheet (brand-sc-linesheets-preview-qty-*)',
    roleId: 'brand',
    pillarId: 'sample_collection',
    href: '/brand/linesheets',
    status: 'done',
  },
  {
    id: 'agent-mfr-tz-pdf-bundle',
    kind: 'improve',
    priority: 'P1',
    title: 'Досье · техзадание: PDF bundle tz-handoff-summary.pdf в export-tz-bundle',
    roleId: 'manufacturer',
    pillarId: 'order_production',
    href: '/factory/production/dossier',
    status: 'done',
  },
  {
    id: 'agent-brand-create-article-wizard',
    kind: 'add',
    priority: 'P1',
    title: 'Wizard создания артикула: нет сквозного core-path (EMPTY27 / hub onboarding)',
    roleId: 'brand',
    pillarId: 'development',
    href: '/brand/production/workshop2',
    status: 'done',
  },
  {
    id: 'agent-comms-b2b-saved-templates',
    kind: 'improve',
    priority: 'P1',
    title: 'Чат · оптовый заказ: сохранение своих шаблонов (localStorage + slimCore bar)',
    roleId: 'brand',
    pillarId: 'comms',
    href: '/brand/messages',
    status: 'done',
  },
  {
    id: 'agent-supplier-quote-templates',
    kind: 'improve',
    priority: 'P1',
    title: 'Чат · заказ: Quote templates (shared slimCore templates + custom save)',
    roleId: 'supplier',
    pillarId: 'comms',
    href: '/supplier/messages',
    status: 'done',
  },
  {
    id: 'agent-shop-checkout-jwt',
    kind: 'improve',
    priority: 'P1',
    title: 'Checkout · отправка бренду: Production JWT guard на cart checkout API',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/checkout',
    status: 'done',
  },
  {
    id: 'agent-supplier-po-bundle-pdf',
    kind: 'improve',
    priority: 'P1',
    title: 'BOM × PO · прогресс: PO bundle PDF (po-bundle.pdf API)',
    roleId: 'supplier',
    pillarId: 'order_production',
    href: '/factory/production/materials',
    status: 'done',
  },
  {
    id: 'agent-brand-w2-publish-audit',
    kind: 'improve',
    priority: 'P1',
    title: 'Публикация · витрина: Publish audit log на W2 hub',
    roleId: 'brand',
    pillarId: 'sample_collection',
    href: '/brand/production/workshop2',
    status: 'done',
  },
  {
    id: 'agent-brand-cross-role-uat',
    kind: 'improve',
    priority: 'P1',
    title: 'Витрина бренда: UAT cross-role showroom→matrix via audit path',
    roleId: 'brand',
    pillarId: 'sample_collection',
    href: '/brand/showroom',
    status: 'done',
  },
  {
    id: 'agent-brand-matrix-qty-preview',
    kind: 'improve',
    priority: 'P1',
    title: 'Cross-role · матрица: Inline qty preview modal (brand-sc-matrix-qty-preview-dialog)',
    roleId: 'brand',
    pillarId: 'sample_collection',
    href: '/brand/showroom',
    status: 'done',
  },
  {
    id: 'agent-shop-batch-delivery-ack',
    kind: 'improve',
    priority: 'P1',
    title: 'Трекинг покупателя · PO: Batch acknowledge delivery (shop-co-buyer-delivery-batch-ack)',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/orders',
    status: 'done',
  },
  {
    id: 'agent-brand-cabinet-count-sync',
    kind: 'improve',
    priority: 'P1',
    title: 'Кабинет · лайншит и витрина: Синхрон counts mini/page (brand-sc-cabinet-published-sync)',
    roleId: 'brand',
    pillarId: 'sample_collection',
    href: '/brand/core-cabinet',
    status: 'done',
  },
  {
    id: 'agent-brand-cabinet-golden-path',
    kind: 'improve',
    priority: 'P1',
    title: 'Кабинет · лайншит и витрина: UAT cabinet → full pages (brand-sc-cabinet-golden-path)',
    roleId: 'brand',
    pillarId: 'sample_collection',
    href: '/brand/core-cabinet',
    status: 'done',
  },
  {
    id: 'agent-shop-cabinet-count-sync',
    kind: 'improve',
    priority: 'P1',
    title: 'Кабинет · витрина: Синхрон counts mini/page (shop-sc-cabinet-published-sync)',
    roleId: 'shop',
    pillarId: 'sample_collection',
    href: '/shop/core-cabinet',
    status: 'done',
  },
  {
    id: 'agent-shop-cabinet-golden-path',
    kind: 'improve',
    priority: 'P1',
    title: 'Каталог партнёров: UAT partners→showroom golden path (shop-sc-cabinet-golden-path)',
    roleId: 'shop',
    pillarId: 'sample_collection',
    href: '/shop/b2b/partners/discover',
    status: 'done',
  },
  {
    id: 'agent-shop-crm-invite',
    kind: 'improve',
    priority: 'P1',
    title: 'Реестр оптовых заказов: CRM/invite flow (shop-co-registry-partners-link + invite panel)',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/partners/discover',
    status: 'done',
  },
  {
    id: 'agent-brand-cross-role-checkout-uat',
    kind: 'improve',
    priority: 'P1',
    title: 'Cross-role · матрица: UAT brand peer → shop checkout e2e (core-52)',
    roleId: 'brand',
    pillarId: 'sample_collection',
    href: '/brand/showroom',
    status: 'done',
  },
  {
    id: 'agent-shop-season-matrix',
    kind: 'improve',
    priority: 'P1',
    title: 'Матрица оптового заказа: Сводная матрица сезона (shop-co-season-matrix-strip)',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/matrix',
    status: 'done',
  },
  {
    id: 'agent-shop-reserve-push',
    kind: 'improve',
    priority: 'P1',
    title: 'Push при смене reserve status (chain SSE + shop-co-tracking-reserve-*)',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/orders',
    status: 'done',
  },
  {
    id: 'agent-shop-showroom-quick-add-uat',
    kind: 'improve',
    priority: 'P1',
    title: 'Переход · матрица: UAT showroom quick-add → matrix scroll (core-52)',
    roleId: 'shop',
    pillarId: 'sample_collection',
    href: '/shop/b2b/showroom',
    status: 'done',
  },
  {
    id: 'agent-shop2-b2b-seed',
    kind: 'improve',
    priority: 'P1',
    title: 'Seed B2B для shop2 (B2B-DEMO-SHOP2-SS27, db:seed:workshop2-b2b-demo-order)',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/orders',
    status: 'done',
  },
];
