/** Подписи и tooltip для заголовков таблиц размерных сеток */
export const sizeChartHeaderDescriptions: Record<string, { title: string; tooltip: string }> = {
  ageBand: { title: 'Возраст / группа', tooltip: 'Возрастной интервал или группа роста' },
  productType: { title: 'Тип изделия', tooltip: 'Подтип в категории' },
  capacity: { title: 'Объём', tooltip: 'Ёмкость (мл) или примечание к объёму' },
  IT: { title: 'Размер IT', tooltip: 'Итальянская размерная шкала' },
  FR: { title: 'Размер FR', tooltip: 'Французская размерная шкала' },
  EU: { title: 'Размер EU', tooltip: 'Европейская размерная шкала' },
  US: { title: 'Размер US', tooltip: 'Американская размерная шкала' },
  UK: { title: 'Размер UK', tooltip: 'Британская размерная шкала' },
  RU: { title: 'Размер RU', tooltip: 'Российская размерная шкала (ГОСТ)' },
  JP: { title: 'Размер JP', tooltip: 'Японская размерная шкала' },
  Alpha: { title: 'Буквенный размер', tooltip: 'Буквенное обозначение (XS–XXL, XL+/XXL+ для увеличенных рядов, 3XL… — см. строку каталога)' },
  height: { title: 'Рост', tooltip: 'Рекомендуемый рост (см)' },
  bust: { title: 'Обхват груди', tooltip: 'Обхват груди (см)' },
  underbust: { title: 'Обхват под грудью', tooltip: 'Обхват под грудью (см)' },
  waist: { title: 'Обхват талии', tooltip: 'Обхват талии (см)' },
  hips: { title: 'Обхват бёдер', tooltip: 'Обхват бёдер (см)' },
  length: { title: 'Длина изделия', tooltip: 'Длина изделия (см)' },
  skirtLength: { title: 'Длина юбки', tooltip: 'Длина юбки по боковому шву или спереди (см)' },
  dressLength: { title: 'Длина платья', tooltip: 'Длина платья от плеча или от талии — указать в ТЗ (см)' },
  trouserOutseam: { title: 'Внешний шов брюк', tooltip: 'От пояса до низа штанины (см)' },
  shoulder: { title: 'Ширина плеч', tooltip: 'Ширина плеч (см)' },
  sleeve: { title: 'Длина рукава', tooltip: 'Длина рукава (см)' },
  armCircumference: { title: 'Обхват руки', tooltip: 'Обхват руки (см)' },
  back: { title: 'Длина спины', tooltip: 'Длина спины (см)' },
  heightBust: { title: 'Высота груди', tooltip: 'Высота линии груди (см)' },
  rise: { title: 'Высота посадки', tooltip: 'Высота посадки / расстояние от шага до пояса (см)' },
  inseam: { title: 'Внутренний шов', tooltip: 'Длина внутреннего шва брюк (см)' },
  kneeWidth: { title: 'Ширина по колену', tooltip: 'Ширина по линии колена (см)' },
  thighCircumference: { title: 'Обхват бедра', tooltip: 'Обхват бедра по самому широкому месту (см)' },
  hipHeight: { title: 'Высота бёдер', tooltip: 'Высота линии бёдер (см)' },
  braSizeEU: { title: 'Размер бюстгальтера (EU)', tooltip: 'Размер по европейской маркировке' },
  braSizeUKUS: { title: 'Размер бюстгальтера (UK/US)', tooltip: 'Размер по британской/американской маркировке' },
  difference: { title: 'Разница обхватов', tooltip: 'Разница «обхват грудь − под грудью» (см)' },
  cupEU: { title: 'Чашка (EU)', tooltip: 'Обозначение чашки, EU' },
  cupUKUS: { title: 'Чашка (UK/US)', tooltip: 'Обозначение чашки, UK/US' },
  cupRU: { title: 'Чашка (Россия)', tooltip: 'Обозначение чашки по привычной российской шкале' },
  footLength: { title: 'Длина стопы', tooltip: 'Длина стопы (см, по данным строки)' },
  width: { title: 'Ширина', tooltip: 'Ширина колодки / изделия (в таблице обуви часто в мм)' },
  fullness: { title: 'Полнота', tooltip: 'Полнота обуви (N, F и т.п.)' },
  heel: { title: 'Высота каблука', tooltip: 'Высота каблука (мм)' },
  sole: { title: 'Подошва', tooltip: 'Параметр подошвы (мм)' },
  drop: { title: 'Перепад подошвы', tooltip: 'Перепад (drop) подошвы (мм)' },
  shaftHeight: { title: 'Высота голенища', tooltip: 'Высота голенища сапога (см)' },
  shaftGirth: { title: 'Обхват голенища', tooltip: 'Обхват голенища (см)' },
  arch: { title: 'Свод стопы', tooltip: 'Тип или высота свода (по данным таблицы)' },
  fit: { title: 'Оковка', tooltip: 'Посадка по полноте стопы (узкая/стандартная и т.п.)' },
  flexIndex: { title: 'Гибкость подошвы', tooltip: 'Индекс гибкости подошвы' },
  comfortIndex: { title: 'Комфорт', tooltip: 'Индекс комфорта (по методике таблицы)' },
  weight: { title: 'Вес', tooltip: 'Масса пары (г)' },
  bellyAllowance: { title: 'Запас по животу', tooltip: 'Запас по обхвату (см)' },
  bottomDiameter: { title: 'Диаметр дна', tooltip: 'Диаметр дна (см)' },
  bottomLength: { title: 'Длина дна', tooltip: 'Длина дна (см)' },
  bottomWidth: { title: 'Ширина дна', tooltip: 'Ширина дна (см)' },
  drawstringPerimeter: { title: 'Периметр шнурка', tooltip: 'Периметр затяжки (см)' },
  fastenerDistance: { title: 'Расстояние до застёжки', tooltip: 'Расстояние до застёжки (см)' },
  handleDrop: { title: 'Высота ручки', tooltip: 'Высота падения ручки (см)' },
  internalCompartments: { title: 'Внутренние отделения', tooltip: 'Количество или тип отделений' },
  laptopCompartment: { title: 'Отдел для ноутбука', tooltip: 'Размер отделения под ноутбук' },
  openingWidth: { title: 'Ширина проёма', tooltip: 'Ширина проёма (см)' },
  seatingAllowance: { title: 'Запас по сиденью', tooltip: 'Запас по посадке (см)' },
  sideFolds: { title: 'Боковые складки', tooltip: 'Параметр складок (см)' },
  strapStep: { title: 'Шаг отверстий ремня', tooltip: 'Расстояние между отверстиями (см)' },
  strapThickness: { title: 'Толщина ремня', tooltip: 'Толщина ремня (мм)' },
  usableHeight: { title: 'Полезная высота', tooltip: 'Полезная внутренняя высота (см)' },
  comment: { title: 'Примечание', tooltip: 'Текстовое примечание к строке' },
  neckCircumference: { title: 'Обхват шеи', tooltip: 'Обхват шеи (см), для ТЗ' },
  armholeDepth: { title: 'Глубина проймы', tooltip: 'Глубина проймы (см)' },
  bicepsCircumference: { title: 'Обхват бицепса', tooltip: 'Обхват бицепса в широком месте (см)' },
  wristCircumference: { title: 'Обхват запястья', tooltip: 'Обхват запястья (см)' },
  chestHalfWidth: { title: 'Ширина половины груди', tooltip: 'Условная ширина половины груди спереди (см)' },
  hemCircumference: { title: 'Обхват низа', tooltip: 'Обхват по низу изделия (см)' },
  underbustLevel: { title: 'Линия под грудью', tooltip: 'Условная линия под грудью по горизонтали (см)' },
  hemWidth: { title: 'Ширина низа', tooltip: 'Ширина по низу юбки/брюк (см)' },
  waistBandHeight: { title: 'Высота пояса', tooltip: 'Высота поясной детали (см)' },
  hipDepth: { title: 'Глубина бёдер', tooltip: 'Параметр посадки по бёдрам (см)' },
  cuffOpening: { title: 'Обхват манжеты', tooltip: 'Обхват проёма манжеты (см)' },
  frontRise: { title: 'Передняя длина до пояса', tooltip: 'Высота посадки спереди (см)' },
  backRise: { title: 'Задняя длина до пояса', tooltip: 'Высота посадки сзади (см)' },
  flyLength: { title: 'Длина ширинки', tooltip: 'Длина линии ширинки (см)' },
  kneeCircumference: { title: 'Обхват колена', tooltip: 'Обхват по линии колена (см)' },
  outseamEstimate: { title: 'Длина бокового шва', tooltip: 'Оценка длины внешнего шва (см)' },
  kneeWidthTz: { title: 'Ширина по колену (ТЗ)', tooltip: 'Контроль ширины по колену для ТЗ (см)' },
  strapLengthTypical: { title: 'Длина бретели', tooltip: 'Типичная длина бретели (см)' },
  sideSeamHeight: { title: 'Высота бокового шва', tooltip: 'Участок бокового шва (см)' },
  gussetWidth: { title: 'Ширина ластовицы', tooltip: 'Ширина ластовицы / шагового шва (см)' },
  braGoreWidth: { title: 'Ширина гонка', tooltip: 'Ширина центральной перемычки бюстгальтера (см)' },
  legOpening: { title: 'Ширина проёма ноги', tooltip: 'Низ штанины или проём ноги (см)' },
  legOpeningSwim: { title: 'Проём ноги (пляж)', tooltip: 'Проём для плавок/купальника (см)' },
  sideTieLength: { title: 'Длина завязки', tooltip: 'Длина боковой завязки (см)' },
  hipLineHeight: { title: 'Высота линии бёдер', tooltip: 'Высота линии бёдер от пояса (см)' },
  riseDepth: { title: 'Глубина посадки', tooltip: 'Глубина посадки низа (см)' },
  bellyPanelHeight: { title: 'Высота панели для живота', tooltip: 'Высота растягивающей панели (см)' },
  elasticZoneWaist: { title: 'Зона резинки по талии', tooltip: 'Диапазон обхвата в зоне резинки (см)' },
  sidePanelEase: { title: 'Запас боковой панели', tooltip: 'Запас по боковой панели (см)' },
  seatingEase: { title: 'Запас для сидения', tooltip: 'Дополнительный запас для посадки (см)' },
  sleeveOpeningElastic: { title: 'Проём рукава (эластик)', tooltip: 'Обхват проёма рукава с резинкой (см)' },
  thighOpeningComfort: { title: 'Проём бедра', tooltip: 'Комфортный обхват зоны бедра (см)' },
  magneticClosureSpacing: { title: 'Шаг магнитов', tooltip: 'Расстояние между точками магнитной застёжки (см)' },
  instepCircumference: { title: 'Обхват подъёма', tooltip: 'Обхват стопы по подъёму (см)' },
  toeBoxWidth: { title: 'Ширина носка', tooltip: 'Ширина зоны пальцев (см)' },
  insoleLength: { title: 'Длина стельки', tooltip: 'Контрольная длина стельки (см)' },
  ballGirth: { title: 'Обхват пучка', tooltip: 'Обхват по широкой части стопы (см)' },
  ankleCircumference: { title: 'Обхват щиколотки', tooltip: 'Обхват в зоне щиколотки (см)' },
  calfReferenceHeight: { title: 'Высота обхвата икры', tooltip: 'Высота снятия обхвата голени (см)' },
  ankleShaftTransition: { title: 'Переход голенище–щиколотка', tooltip: 'Обхват в зоне перехода (см)' },
  type: { title: 'Тип', tooltip: 'Тип изделия' },
  headCircumference: { title: 'Обхват головы', tooltip: 'Обхват головы (см)' },
  domeDepth: { title: 'Глубина купола', tooltip: 'Глубина купола (см)' },
  crownDiameter: { title: 'Диаметр тульи', tooltip: 'Диаметр тульи (см)' },
  brimWidth: { title: 'Ширина полей', tooltip: 'Ширина полей головного убора (см)' },
  palmCircumference: { title: 'Обхват ладони', tooltip: 'Окружность ладони (см)' },
  gloveLength: { title: 'Длина перчатки', tooltip: 'Длина перчатки (см)' },
  cuff: { title: 'Манжета', tooltip: 'Ширина манжеты (см)' },
  strapLength: { title: 'Длина лямки/ремня', tooltip: 'Длина ремня или лямки (см)' },
  strapWidth: { title: 'Ширина лямки/ремня', tooltip: 'Ширина ремня или лямки (см)' },
  holes: { title: 'Отверстия', tooltip: 'Количество отверстий (шт.)' },
  firstHoleDistance: { title: 'До первого отверстия', tooltip: 'Расстояние до первого отверстия ремня (см)' },
  lensWidth: { title: 'Ширина линзы', tooltip: 'Ширина линзы (мм)' },
  lensHeight: { title: 'Высота линзы', tooltip: 'Высота линзы (мм)' },
  bridgeWidth: { title: 'Ширина перемычки', tooltip: 'Ширина перемычки оправы (мм)' },
  templeLength: { title: 'Длина дужки', tooltip: 'Длина заушника (мм)' },
  frameWidth: { title: 'Ширина оправы', tooltip: 'Ширина оправы (мм)' },
  diameter: { title: 'Диаметр', tooltip: 'Диаметр (мм)' },
  circumference: { title: 'Окружность', tooltip: 'Окружность (мм)' },
  caseDiameter: { title: 'Диаметр корпуса', tooltip: 'Диаметр корпуса часов (мм)' },
  caseThickness: { title: 'Толщина корпуса', tooltip: 'Толщина корпуса часов (мм)' },
  shaftLength: { title: 'Длина голенища', tooltip: 'Длина голенища (см)' },
  thickness: { title: 'Толщина', tooltip: 'Толщина (den или мм — по контексту таблицы)' },
  domeDiameter: { title: 'Диаметр купола', tooltip: 'Диаметр купола (см)' },
  ribs: { title: 'Количество спиц', tooltip: 'Количество спиц зонта (шт.)' },
  depth: { title: 'Глубина', tooltip: 'Глубина (см)' },
  leatherThickness: { title: 'Толщина кожи', tooltip: 'Толщина кожи (мм)' },
  beltLength: { title: 'Длина ремня', tooltip: 'Длина ремня (см)' },
  materialThickness: { title: 'Толщина материала', tooltip: 'Толщина материала (мм)' },
  soleThickness: { title: 'Подошва', tooltip: 'Толщина / тип подошвы (мм), для пинеток — мягкий слой' },
};

/** Таблица сумок: те же ключи колонок, что у одежды/обуви, но другой смысл (height ≠ рост). */
export const sizeChartBagsHeaderOverlay: Record<string, { title: string; tooltip: string }> = {
  type: { title: 'Тип сумки', tooltip: 'Формат / силуэт по размерной сетке' },
  height: { title: 'Высота', tooltip: 'Высота корпуса (см)' },
  width: { title: 'Ширина (фасад)', tooltip: 'Ширина по лицевой стороне (см)' },
  depth: { title: 'Глубина', tooltip: 'Глубина корпуса (см)' },
  weight: { title: 'Вес, г', tooltip: 'Масса изделия (г)' },
};
