/** Шаги цепочки коллекции: первое содержательное сохранение → матрица SKU «в работе». */
export const BRAND_PRODUCTION_HUB_MODULE_KICKOFF_STEP_IDS = new Set([
  'brief',
  'assortment-map',
  'collection-hub',
  'costing',
  'materials',
  'photo-ref',
  'tech-pack',
  'gate-all-stakeholders',
  'supply-path',
  'samples',
  'b2b-linesheets',
  'production-window',
  'po',
  'floor-ops',
  'supplies-bind',
  'nesting-cut',
  'floor-execution',
  'qc',
  'ready-made',
  'wholesale-prep',
  'b2b-ship-stores',
  'sustainability',
]);
