/**
 * Начальные демо-данные для `production-page-main` (legacy Production control).
 * Вынесено из компонента, чтобы снизить размер файла.
 *
 * Импорт в приложении — через `production-page-main-demo-seed.resolve.ts`
 * (флаг `production-page-main-demo-env.ts`).
 */

/* eslint-disable @typescript-eslint/no-explicit-any -- демо-сид для прототипа */

export const INITIAL_SKUS = [
    {
      name: 'Платье "Midnight"',
      id: 'TP-9921',
      ver: '2.4',
      collection: 'SS26',
      audienceId: 'women',
      catLevel1Id: 'women-apparel',
      catLevel2Id: 'women-dresses',
      catLevel3Id: 'women-midi',
      attributes: { sil: 'Приталенный', color: 'Black' },
      price: '4,500 ₽',
      status: 'Production',
      master: true,
      deadline: '2026-06-10',
    },
    {
      name: 'Топ "White Silk"',
      id: 'TP-9922',
      ver: '1.0',
      collection: 'SS26',
      audienceId: 'women',
      catLevel1Id: 'women-apparel',
      catLevel2Id: 'women-tops',
      catLevel3Id: 'women-blouses',
      attributes: { color: 'White' },
      price: '2,100 ₽',
      status: 'Development',
      master: true,
      deadline: '2026-06-15',
    },
    {
      name: 'Шорты "Linen Breezy"',
      id: 'TP-9923',
      ver: '1.2',
      collection: 'SS26',
      audienceId: 'men',
      catLevel1Id: 'men-apparel',
      catLevel2Id: 'men-tops',
      catLevel3Id: 'men-tshirts',
      attributes: { color: 'Beige' },
      price: '3,200 ₽',
      status: 'Sampling',
      master: true,
      deadline: '2026-06-20',
    },
    {
      name: 'Худи "Eco-Life"',
      id: 'TP-8812',
      ver: '1.1',
      collection: 'DROP-UZ',
      audienceId: 'unisex',
      catLevel1Id: 'unisex-apparel',
      catLevel2Id: 'unisex-tops',
      catLevel3Id: 'unisex-hoodies',
      attributes: { color: 'Green' },
      price: '2,800 ₽',
      status: 'Production',
      master: true,
      deadline: '2026-04-15',
    },
    {
      name: 'Брюки "Cargo Pro"',
      id: 'TP-7734',
      ver: '3.0',
      collection: 'BASIC',
      audienceId: 'men',
      catLevel1Id: 'men-apparel',
      catLevel2Id: 'men-bottoms',
      catLevel3Id: 'men-cargo',
      attributes: { color: 'Khaki' },
      price: '3,200 ₽',
      status: 'Stock',
      master: true,
      deadline: '2026-12-01',
    },
    {
      name: 'Футболка "Base"',
      id: 'TP-1102',
      ver: '1.0',
      collection: 'BASIC',
      audienceId: 'unisex',
      catLevel1Id: 'unisex-apparel',
      catLevel2Id: 'unisex-tops',
      catLevel3Id: 'unisex-tshirts',
      attributes: { color: 'White' },
      price: '1,200 ₽',
      status: 'Stock',
      master: true,
      deadline: '2026-12-01',
    },
    {
      name: 'Куртка "Urban Shield"',
      id: 'TP-4401',
      ver: '0.8',
      collection: 'ARCHIVE',
      audienceId: 'men',
      catLevel1Id: 'men-apparel',
      catLevel2Id: 'men-outerwear',
      catLevel3Id: 'men-jackets',
      attributes: { color: 'Grey' },
      price: '8,900 ₽',
      status: 'Development',
      master: true,
      deadline: '2026-03-30',
    },
];

export const INITIAL_COLLECTIONS = [
    {
      id: 'SS26',
      name: 'Summer Solstice 2026',
      status: 'Production',
      items: 12,
      readiness: '65%',
      budget: '4.2M ₽',
      type: 'Коллекция',
      priority: 'High',
      deadline: '2026-05-15',
      responsible: 'Анна К.',
      season: 'SS26',
      tag: 'Основная',
    },
    {
      id: 'DROP-UZ',
      name: 'Urban Zen Drop',
      status: 'Development',
      items: 5,
      readiness: '20%',
      budget: '850k ₽',
      type: 'Дроп',
      priority: 'Standard',
      deadline: '2026-04-10',
      responsible: 'Игорь М.',
      season: 'FW26',
      tag: 'Дроп',
    },
    {
      id: 'BASIC',
      name: 'Core Basics (Replenish)',
      status: 'Active',
      items: 24,
      readiness: '100%',
      budget: '1.2M ₽',
      type: 'Сток',
      priority: 'Low',
      deadline: '—',
      responsible: 'Елена С.',
      tag: 'Сток',
    },
];

  // Бюджет коллекции: план, факт, остаток по статьям
export const INITIAL_COLLECTION_BUDGETS = [
    {
      collectionId: 'SS26',
      categories: [
        { id: 'materials', label: 'Материалы', plan: 1800000, fact: 1190400, unit: '₽' },
        { id: 'sewing', label: 'Пошив', plan: 2100000, fact: 890000, unit: '₽' },
        { id: 'logistics', label: 'Логистика', plan: 300000, fact: 215000, unit: '₽' },
      ],
      totalPlan: 4200000,
      totalFact: 2295400,
    },
    {
      collectionId: 'DROP-UZ',
      categories: [
        { id: 'materials', label: 'Материалы', plan: 380000, fact: 120000, unit: '₽' },
        { id: 'sewing', label: 'Пошив', plan: 400000, fact: 0, unit: '₽' },
        { id: 'logistics', label: 'Логистика', plan: 70000, fact: 15000, unit: '₽' },
      ],
      totalPlan: 850000,
      totalFact: 135000,
    },
    {
      collectionId: 'BASIC',
      categories: [
        { id: 'materials', label: 'Материалы', plan: 600000, fact: 580000, unit: '₽' },
        { id: 'sewing', label: 'Пошив', plan: 500000, fact: 495000, unit: '₽' },
        { id: 'logistics', label: 'Логистика', plan: 100000, fact: 98000, unit: '₽' },
      ],
      totalPlan: 1200000,
      totalFact: 1173000,
    },
];

export const INITIAL_MATERIALS_LIST = [
    {
      name: 'Шелк Сатин (Black)',
      roll: '#0921',
      length: '45.5 м',
      width: '145 см',
      defects: 2,
      status: 'Stock',
      collection: 'SS26',
    },
    {
      name: 'Шелк Сатин (Black)',
      roll: '#0922',
      length: '50.0 м',
      width: '145 см',
      defects: 0,
      status: 'Factory',
      collection: 'SS26',
    },
];

export const INITIAL_SFC_OPERATIONS = [
    {
      op: 'Закупка сырья (Основная ткань)',
      plan: '100% лот',
      fact: '100% лот',
      diff: '0%',
      cost: '150,000 ₽',
      status: 'success',
      confirmed: true,
      date: '01.03.2026',
      type: 'supply',
      collection: 'SS26',
    },
    {
      op: 'Передача на аутсорс (Принт)',
      plan: '500 ед',
      fact: '500 ед',
      diff: '0%',
      cost: '45,000 ₽',
      status: 'success',
      confirmed: true,
      date: '05.03.2026',
      type: 'outsource',
      collection: 'SS26',
    },
    {
      op: 'Крой коллекции',
      plan: '15.0м',
      fact: '15.5м',
      diff: '+3%',
      cost: '4,500 ₽',
      status: 'warning',
      confirmed: true,
      date: '08.03.2026',
      comment: 'Перерасход из-за раскладки',
      type: 'sewing',
      collection: 'SS26',
    },
    {
      op: 'Пошив Proto 1',
      plan: '45.0м',
      fact: '42.0м',
      diff: '-6%',
      cost: '12,000 ₽',
      status: 'success',
      confirmed: false,
      type: 'sewing',
      collection: 'SS26',
    },
    {
      op: 'Отгрузка на склад (Поставка #1)',
      plan: '200 ед',
      fact: '-',
      diff: '-',
      cost: '5,000 ₽',
      status: 'warning',
      confirmed: false,
      type: 'logistics',
      collection: 'SS26',
    },
];

export const INITIAL_CALENDAR_EVENTS = [
    {
      id: '1',
      date: '2026-03-15',
      title: 'Поставка Silk Satin',
      type: 'logistics',
      collection: 'SS26',
      status: 'pending',
      description: 'Ожидаем машину из Турции к 10:00',
      responsible: 'Анна К.',
    },
    {
      id: '2',
      date: '2026-03-20',
      title: 'Финальная примерка Proto 2',
      type: 'milestone',
      collection: 'SS26',
      status: 'urgent',
      description: 'Важно проверить посадку рукава',
      responsible: 'Игорь М.',
    },
    {
      id: '3',
      date: '2026-03-25',
      title: 'Оплата за пошив (Аванс)',
      type: 'finance',
      collection: 'SS26',
      status: 'pending',
      description: 'Счет #203 от фабрики Global',
      responsible: 'Елена С.',
    },
];

export const INITIAL_PRODUCTION_LOSSES = [
    {
      type: 'material',
      item: 'Silk Satin (Black)',
      collection: 'SS26',
      qty: '2.4 м',
      reason: 'Брак при раскрое',
      cost: '12,400 ₽',
      date: '08.03',
      status: 'pending',
      responsible: 'Анна К.',
      category: 'defect',
    },
    {
      type: 'model',
      item: 'Dress "Midnight"',
      collection: 'SS26',
      qty: '1 ед',
      reason: 'Критический дефект шва',
      cost: '4,500 ₽',
      date: '09.03',
      status: 'confirmed',
      responsible: 'Игорь М.',
      category: 'defect',
    },
    {
      type: 'material',
      item: 'Хлопок белый',
      collection: 'SS26',
      qty: '5 м',
      reason: 'Перерасход при раскладке',
      cost: '3,200 ₽',
      date: '07.03',
      status: 'confirmed',
      responsible: 'Анна К.',
      category: 'overrun',
    },
    {
      type: 'model',
      item: 'Топ SS26-01',
      collection: 'DROP-UZ',
      qty: '2 ед',
      reason: 'Списание по акту',
      cost: '8,100 ₽',
      date: '05.03',
      status: 'confirmed',
      responsible: 'Елена С.',
      category: 'writeoff',
    },
];

export const INITIAL_PRODUCTION_ORDERS = [
    {
      id: 'PO-2026-001',
      collection: 'SS26',
      factory: 'Global Textiles',
      skus: ['TP-9921'],
      qty: 500,
      status: 'In Production',
      date: '01.03.2026',
      payment: 'Аванс 50%',
      paymentStatus: 'advance',
      total: 350000,
      dueDate: '12.03.2026',
      sizeMatrix: { XS: 50, S: 100, M: 150, L: 100, XL: 50 },
      colors: ['Black', 'White'],
      responsible: 'Анна К.',
    },
    {
      id: 'PO-2026-002',
      collection: 'SS26',
      factory: 'Smart Tailor',
      skus: ['TP-9922', 'TP-9923'],
      qty: 300,
      status: 'Confirmed',
      date: '05.03.2026',
      payment: 'Ожидает',
      paymentStatus: 'pending',
      total: 180000,
      dueDate: '15.03.2026',
      sizeMatrix: { S: 80, M: 120, L: 100 },
      colors: ['Navy', 'Beige'],
      responsible: 'Игорь М.',
    },
    {
      id: 'PO-2026-003',
      collection: 'DROP-UZ',
      factory: 'Global Textiles',
      skus: ['TP-8812'],
      qty: 200,
      status: 'Shipped',
      date: '28.02.2026',
      payment: 'Оплачено',
      paymentStatus: 'paid',
      total: 120000,
      sizeMatrix: { M: 100, L: 100 },
      colors: ['Black'],
      responsible: 'Елена С.',
    },
];

export const INITIAL_SAMPLE_STATUSES = [
    {
      skuId: 'TP-9921',
      skuName: 'Платье "Midnight"',
      collection: 'SS26',
      stage: 'PP',
      stageLabel: 'Pre-Production',
      status: 'approved',
      dueDate: '20.03.2026',
      factory: 'Global Textiles',
      slaOverdue: false,
      tracking: { status: 'at_brand', eta: null },
    },
    {
      skuId: 'TP-9922',
      skuName: 'Топ "White Silk"',
      collection: 'SS26',
      stage: 'Proto2',
      stageLabel: 'Proto 2',
      status: 'in_review',
      dueDate: '15.03.2026',
      factory: 'Smart Tailor',
      slaOverdue: true,
      tracking: { status: 'in_transit', eta: '14.03.2026' },
    },
    {
      skuId: 'TP-9923',
      skuName: 'Шорты "Linen Breezy"',
      collection: 'SS26',
      stage: 'Proto1',
      stageLabel: 'Proto 1',
      status: 'waiting',
      dueDate: '18.03.2026',
      factory: 'Smart Tailor',
      slaOverdue: false,
      tracking: { status: 'at_factory' },
    },
    {
      skuId: 'TP-8812',
      skuName: 'Куртка Urban',
      collection: 'DROP-UZ',
      stage: 'SizeSet',
      stageLabel: 'Size Set',
      status: 'approved',
      dueDate: '10.03.2026',
      factory: 'Global Textiles',
      slaOverdue: false,
      tracking: { status: 'qc' },
    },
];

export const INITIAL_AUDIT_LOG = [
    {
      id: 1,
      action: 'bom',
      actionLabel: 'BOM обновлён',
      entity: 'TP-9921',
      collection: 'SS26',
      user: 'Анна К.',
      time: '09.03 14:20',
      detail: 'Добавлен материал Silk Satin',
    },
    {
      id: 2,
      action: 'sample',
      actionLabel: 'Сэмпл утверждён',
      entity: 'TP-8812',
      collection: 'DROP-UZ',
      user: 'Игорь М.',
      time: '08.03 11:00',
      detail: 'PP Sample approved',
    },
    {
      id: 3,
      action: 'po',
      actionLabel: 'PO создан',
      entity: 'PO-2026-002',
      collection: 'SS26',
      user: 'Анна К.',
      time: '05.03 16:45',
      detail: '300 ед., Smart Tailor',
    },
    {
      id: 4,
      action: 'status',
      actionLabel: 'Статус изменён',
      entity: 'PO-2026-001',
      collection: 'SS26',
      user: 'Система',
      time: '09.03 09:15',
      detail: 'In Production → Shipment Ready',
    },
    {
      id: 5,
      action: 'bom',
      actionLabel: 'BOM обновлён',
      entity: 'TP-9922',
      collection: 'SS26',
      user: 'Анна К.',
      time: '07.03 16:30',
      detail: 'Изменён расход ткани (-0.2м)',
    },
    {
      id: 6,
      action: 'sample',
      actionLabel: 'Сэмпл на проверку',
      entity: 'TP-9923',
      collection: 'SS26',
      user: 'Smart Tailor',
      time: '06.03 14:00',
      detail: 'Proto 1 отправлен на approval',
    },
];

export const INITIAL_REQUISITIONS = [
    {
      id: 'REQ-001',
      collection: 'SS26',
      material: 'Silk Satin Black',
      qty: 120,
      unit: 'м',
      status: 'Quotes',
      supplier: null,
    },
    {
      id: 'REQ-002',
      collection: 'SS26',
      material: 'YKK Zipper #5',
      qty: 500,
      unit: 'шт',
      status: 'PO Created',
      supplier: 'YKK Russia',
    },
];

export const INITIAL_PRODUCTION_DOCUMENTS = [
    {
      type: 'tz',
      name: 'ТЗ SS26 Summer Solstice',
      collection: 'SS26',
      date: '15.02.2026',
      status: 'Утверждено',
    },
    {
      type: 'contract',
      name: 'Контракт с Global Textiles',
      collection: 'SS26',
      date: '01.02.2026',
      status: 'Подписан',
    },
    {
      type: 'invoice',
      name: 'Инвойс PO-2026-001',
      collection: 'SS26',
      date: '08.03.2026',
      status: 'Ожидает оплаты',
    },
    {
      type: 'qc',
      name: 'QC Report #902',
      collection: 'SS26',
      date: '09.03.2026',
      status: 'PASSED',
    },
    {
      type: 'cmr',
      name: 'CMR SHIP-9921',
      collection: 'SS26',
      date: '10.03.2026',
      status: 'В пути',
    },
];

export const INITIAL_NOTIFICATIONS_LIST = [
    {
      id: '1',
      type: 'sla',
      title: 'Сэмпл TP-9922: просрочка SLA Proto 2',
      time: '2 ч назад',
      read: false,
    },
    {
      id: '2',
      type: 'deadline',
      title: 'Сэмпл TP-9922: дедлайн через 4 дня',
      time: '2 ч назад',
      read: false,
    },
    {
      id: '3',
      type: 'status',
      title: 'PO-2026-001: фабрика обновила статус',
      time: '5 ч назад',
      read: false,
    },
    { id: '4', type: 'finance', title: 'Платёж 350 000 ₽ — 12.03.2026', time: 'Вчера', read: true },
    { id: '5', type: 'qc', title: 'QC-901: обнаружено 2 дефекта', time: 'Вчера', read: true },
];

  // Chat State
export const INITIAL_CHAT_MESSAGES = [
    {
      id: '1',
      sender: 'Production Manager',
      text: 'Поставка SS26: Ткань Silk Satin прибыла на таможню. Анна, проверьте документы.',
      time: '10:30',
      collection: 'SS26',
      avatar: 'AM',
    },
    {
      id: '2',
      sender: 'Factory Boss (Global)',
      text: 'Образцы для Drop-UZ готовы к отправке. Ждем курьера.',
      time: '11:15',
      collection: 'DROP-UZ',
      avatar: 'GB',
    },
    {
      id: '3',
      sender: 'Buyer',
      text: 'Нужно уточнить бюджет по Basic коллекции. Перерасход по логистике на 5%.',
      time: 'Yesterday',
      collection: 'BASIC',
      avatar: 'ES',
    },
    {
      id: '4',
      sender: 'QC Specialist',
      text: 'В партии SS26 обнаружен дефект шва на 2-х платьях. См. раздел Потери.',
      time: 'Today, 09:20',
      collection: 'SS26',
      avatar: 'QC',
    },
    {
      id: '5',
      sender: 'Designer',
      text: 'Лекала для новой куртки Urban Shield готовы в CLO3D.',
      time: 'Just now',
      collection: 'General',
      avatar: 'ID',
    },
];
