/**
 * Публичная обёртка над `production-page-main-demo-seed.ts`.
 * Флаг: `production-page-main-demo-env.ts` (`NEXT_PUBLIC_PRODUCTION_MAIN_USE_DEMO_SEED`).
 */
'use client';

import { PRODUCTION_MAIN_LEGACY_USE_DEMO_SEED } from '@/app/brand/production/production-page-main-demo-env';
import {
  INITIAL_AUDIT_LOG as FULL_AUDIT_LOG,
  INITIAL_CALENDAR_EVENTS as FULL_CALENDAR_EVENTS,
  INITIAL_CHAT_MESSAGES as FULL_CHAT_MESSAGES,
  INITIAL_COLLECTIONS as FULL_COLLECTIONS,
  INITIAL_COLLECTION_BUDGETS as FULL_COLLECTION_BUDGETS,
  INITIAL_MATERIALS_LIST as FULL_MATERIALS_LIST,
  INITIAL_NOTIFICATIONS_LIST as FULL_NOTIFICATIONS_LIST,
  INITIAL_PRODUCTION_DOCUMENTS as FULL_PRODUCTION_DOCUMENTS,
  INITIAL_PRODUCTION_LOSSES as FULL_PRODUCTION_LOSSES,
  INITIAL_PRODUCTION_ORDERS as FULL_PRODUCTION_ORDERS,
  INITIAL_REQUISITIONS as FULL_REQUISITIONS,
  INITIAL_SAMPLE_STATUSES as FULL_SAMPLE_STATUSES,
  INITIAL_SFC_OPERATIONS as FULL_SFC_OPERATIONS,
  INITIAL_SKUS as FULL_SKUS,
} from '@/app/brand/production/production-page-main-demo-seed';

export const INITIAL_SKUS = PRODUCTION_MAIN_LEGACY_USE_DEMO_SEED ? FULL_SKUS : [];

export const INITIAL_COLLECTIONS = PRODUCTION_MAIN_LEGACY_USE_DEMO_SEED ? FULL_COLLECTIONS : [];

export const INITIAL_COLLECTION_BUDGETS = PRODUCTION_MAIN_LEGACY_USE_DEMO_SEED
  ? FULL_COLLECTION_BUDGETS
  : [];

export const INITIAL_MATERIALS_LIST = PRODUCTION_MAIN_LEGACY_USE_DEMO_SEED
  ? FULL_MATERIALS_LIST
  : [];

export const INITIAL_SFC_OPERATIONS = PRODUCTION_MAIN_LEGACY_USE_DEMO_SEED
  ? FULL_SFC_OPERATIONS
  : [];

export const INITIAL_CALENDAR_EVENTS = PRODUCTION_MAIN_LEGACY_USE_DEMO_SEED
  ? FULL_CALENDAR_EVENTS
  : [];

export const INITIAL_PRODUCTION_LOSSES = PRODUCTION_MAIN_LEGACY_USE_DEMO_SEED
  ? FULL_PRODUCTION_LOSSES
  : [];

export const INITIAL_PRODUCTION_ORDERS = PRODUCTION_MAIN_LEGACY_USE_DEMO_SEED
  ? FULL_PRODUCTION_ORDERS
  : [];

export const INITIAL_SAMPLE_STATUSES = PRODUCTION_MAIN_LEGACY_USE_DEMO_SEED
  ? FULL_SAMPLE_STATUSES
  : [];

export const INITIAL_AUDIT_LOG = PRODUCTION_MAIN_LEGACY_USE_DEMO_SEED ? FULL_AUDIT_LOG : [];

export const INITIAL_REQUISITIONS = PRODUCTION_MAIN_LEGACY_USE_DEMO_SEED ? FULL_REQUISITIONS : [];

export const INITIAL_PRODUCTION_DOCUMENTS = PRODUCTION_MAIN_LEGACY_USE_DEMO_SEED
  ? FULL_PRODUCTION_DOCUMENTS
  : [];

export const INITIAL_NOTIFICATIONS_LIST = PRODUCTION_MAIN_LEGACY_USE_DEMO_SEED
  ? FULL_NOTIFICATIONS_LIST
  : [];

export const INITIAL_CHAT_MESSAGES = PRODUCTION_MAIN_LEGACY_USE_DEMO_SEED ? FULL_CHAT_MESSAGES : [];
