import type { BrandProductionState } from './types';

/** Связанный граф: коллекция → артикулы → BOM → PO → QC → треды → B2B refs */
export function createSeedState(): BrandProductionState {
  const now = new Date().toISOString();
  return {
    currentUserId: 'u1',
    currentUserLabel: 'Мария (Продакшн)',
    currentRole: 'production',
    integration: {
      erpExportEnabled: false,
      erpType: '1c',
      webhookUrl: '',
      webhookSecretPlaceholder: '••••••••',
      factoryStatusWebhookEnabled: false,
    },
    collections: [
      {
        id: 'col-fw26',
        name: 'FW26 Основная',
        code: 'FW26-MAIN',
        status: 'active',
        targetFirstDropDate: '2026-07-01',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'col-ss26',
        name: 'SS26',
        code: 'SS26',
        status: 'draft',
        targetFirstDropDate: '2026-03-01',
        createdAt: now,
        updatedAt: now,
      },
    ],
    factories: [
      {
        id: 'fab-1',
        name: 'Фабрика «Север»',
        country: 'РФ',
        utilizationPct: 72,
        maxCapacityUnits: 50000,
      },
      {
        id: 'fab-2',
        name: 'CMT Istanbul',
        country: 'TR',
        utilizationPct: 55,
        maxCapacityUnits: 80000,
      },
    ],
    articles: [
      {
        id: 'art-1',
        collectionId: 'col-fw26',
        sku: 'FW26-JKT-001',
        name: 'Куртка Urban',
        lifecycleStage: 'manufacturing',
        dropId: 'drop1',
        goldSampleApproved: true,
        techPackVersion: 'v2.1',
        targetTechPackDate: '2026-01-15',
        targetCutDate: '2026-05-10',
        b2bReady: false,
        finishedGoodsQty: 0,
        linesheetReady: true,
      },
      {
        id: 'art-2',
        collectionId: 'col-fw26',
        sku: 'FW26-TRS-002',
        name: 'Брюки Wool',
        lifecycleStage: 'samples',
        dropId: 'drop1',
        goldSampleApproved: false,
        techPackVersion: 'v1.0',
        targetTechPackDate: '2026-02-01',
        targetCutDate: '2026-05-15',
        b2bReady: false,
        finishedGoodsQty: 0,
        linesheetReady: false,
      },
      {
        id: 'art-3',
        collectionId: 'col-fw26',
        sku: 'FW26-KNT-003',
        name: 'Свитер Cable',
        lifecycleStage: 'b2b_ready',
        dropId: 'drop2',
        goldSampleApproved: true,
        techPackVersion: 'v3.0',
        b2bReady: true,
        finishedGoodsQty: 1200,
        linesheetReady: true,
      },
    ],
    purchaseOrders: [
      {
        id: 'po-201',
        code: 'PO-2026-201',
        collectionId: 'col-fw26',
        factoryId: 'fab-1',
        status: 'in_production',
        confirmedAt: '2026-02-01T10:00:00Z',
        criticalPathEnd: '2026-06-28',
        atRisk: false,
        createdAt: '2026-01-20T08:00:00Z',
        lines: [
          {
            id: 'pol-1',
            articleId: 'art-1',
            dropId: 'drop1',
            sizeBreakdown: { S: 100, M: 200, L: 150, XL: 50 },
            totalQty: 500,
          },
        ],
      },
      {
        id: 'po-202',
        code: 'PO-2026-202',
        collectionId: 'col-fw26',
        factoryId: 'fab-2',
        status: 'sent',
        criticalPathEnd: '2026-07-05',
        atRisk: true,
        createdAt: '2026-02-08T09:00:00Z',
        lines: [
          {
            id: 'pol-2',
            articleId: 'art-2',
            dropId: 'drop1',
            sizeBreakdown: { '46': 80, '48': 120, '50': 100 },
            totalQty: 300,
          },
        ],
      },
    ],
    bomLines: [
      {
        id: 'bom-1',
        articleId: 'art-1',
        materialCode: 'FAB-WOOL-440',
        materialName: 'Шерсть 440 г/м',
        qtyPerUnit: 1.8,
        unit: 'м',
        supplierId: 'sup-1',
        supplierName: 'Ткани Плюс',
        purchaseStatus: 'reserved',
        etaToFactory: '2026-04-20',
        reservedQty: 900,
      },
      {
        id: 'bom-2',
        articleId: 'art-2',
        materialCode: 'FAB-COT-320',
        materialName: 'Хлопок 320',
        qtyPerUnit: 2.0,
        unit: 'м',
        supplierId: 'sup-2',
        supplierName: 'EuroTextile',
        purchaseStatus: 'ordered',
        etaToFactory: '2026-05-01',
        reservedQty: 0,
      },
    ],
    qcPlans: [
      {
        id: 'qcp-1',
        poId: 'po-201',
        articleId: 'art-1',
        type: 'final',
        scheduledAt: '2026-06-25T09:00:00Z',
        status: 'planned',
        checklistTemplateId: 'qc-apparel-final',
      },
    ],
    qcInspections: [
      {
        id: 'qci-1',
        planId: 'qcp-1',
        poId: 'po-201',
        articleId: 'art-1',
        result: 'pass',
        notes: 'Промежуточный осмотр',
        photoUrls: [],
        blocksShipment: false,
        inspectedAt: '2026-03-01T14:00:00Z',
        inspectorLabel: 'Иван QC',
      },
    ],
    threads: [
      {
        id: 'th-art-1',
        scope: 'article',
        scopeId: 'art-1',
        messages: [
          {
            id: 'm1',
            at: '2026-02-15T10:00:00Z',
            authorRole: 'production',
            authorLabel: 'Мария',
            body: 'Обновили техпак v2.1 — уточнены швы по плечу.',
            techPackVersion: 'v2.1',
          },
          {
            id: 'm2',
            at: '2026-02-16T08:00:00Z',
            authorRole: 'design',
            authorLabel: 'Анна',
            body: 'Ок, подтверждаю.',
          },
        ],
      },
      {
        id: 'th-po-201',
        scope: 'po',
        scopeId: 'po-201',
        messages: [
          {
            id: 'm3',
            at: '2026-02-20T11:00:00Z',
            authorRole: 'production',
            authorLabel: 'Мария',
            body: 'Подтвердите дату раскроя до 12 мая.',
          },
        ],
      },
    ],
    auditLog: [
      {
        id: 'a1',
        at: '2026-02-01T10:00:00Z',
        userId: 'u1',
        userLabel: 'Мария',
        entityType: 'PO',
        entityId: 'po-201',
        action: 'status_change',
        fromValue: 'sent',
        toValue: 'confirmed',
      },
      {
        id: 'a2',
        at: '2026-02-05T14:00:00Z',
        userId: 'u1',
        userLabel: 'Мария',
        entityType: 'Article',
        entityId: 'art-1',
        action: 'lifecycle_change',
        fromValue: 'po',
        toValue: 'manufacturing',
      },
    ],
    b2bOrderRefs: [
      {
        id: 'b2b-1',
        collectionId: 'col-fw26',
        articleSku: 'FW26-KNT-003',
        qty: 400,
        status: 'confirmed',
        orderRef: 'B2B-8842',
      },
    ],
  };
}
