import type { StoreContentPostV1 } from './types';

/** Автопилот генерации контента для локальных магазинов (VK/Telegram). */
export function generateStoreContentPosts(sku: string, productName: string): StoreContentPostV1[] {
  return [
    {
      id: 'POST-001',
      platform: 'Telegram',
      copyRu: `🔥 Новое поступление: ${productName}! Идеальный крой и премиальный хлопок. Ждем вас в нашем магазине в ТЦ "Галерея"! #fashion #newarrival`,
      mediaAssets: ['img-1.jpg'],
      scheduledDate: '2026-04-05 10:00',
      isAutoGenerated: true,
    },
    {
      id: 'POST-002',
      platform: 'VK',
      copyRu: `Весенняя коллекция уже на полках! 🌿 ${productName} — это сочетание стиля и комфорта. Приходите на примерку! 📍 Невский пр., 12`,
      mediaAssets: ['img-2.jpg', 'img-3.jpg'],
      scheduledDate: '2026-04-05 12:00',
      isAutoGenerated: true,
    },
  ];
}
